charts/datadog/Chart.yaml, charts/datadog/templates/cluster-agent-rbac.yaml
Update cluster-agent RBAC to collect new resources for the orchestrator explorer
=> Update DCA RBAC to collect new resources for the orchestrator explorer

charts/datadog/Chart.yaml, charts/datadog/templates/agent-psp.yaml, charts/datadog/templates/agent-scc.yaml, charts/datadog/values.yaml
Fix the typo "+allowHostPorts" 
- fixes #10
=> Fix typo in allowHostPorts

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/values.yaml
- Update default images tags
- Add missing changelog entries.
- Update PullRequest template to as for changelog.md update.
- Update contribution guidelines with: version bump and changelog 
- fixes #
=> [datadog] Update default images tags + changelog.md update

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/templates/agent-network-policy.yaml
Add NetworkPolicy ingress rules for dogstatsd and APM
=> Add NetworkPolicy ingress rules for dogstatsd and APM

charts/datadog-operator/.helmignore, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/crds/datadoghq.com_datadogagents_crd.yaml, charts/datadog-operator/crds/datadoghq.com_datadogmetrics_crd.yaml, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/templates/clusterrole_binding.yaml, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/templates/pod_disruption_budget.yaml, charts/datadog-operator/templates/role.yaml, charts/datadog-operator/templates/role_binding.yaml, charts/datadog-operator/templates/service_account.yaml, charts/datadog-operator/values.yaml, crds/datadoghq.com_datadogagents_crd.yaml, crds/datadoghq.com_datadogmetrics_crd.yaml
Add chart for `datadog-operator` in our main repository
Allows to use operator easily
=> Add datadog-operator chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Only a small typo in default values. Should I really bump the chart version for that? Or maybe it could be done in another PR with useful changes?
EDIT: I guess the CI answer is crystal clear, I'm bumping 😅
=> Fix typo in values of datadog chart

.github/CODEOWNERS
=> Add networks as codeowners for system-probe.yaml

.github/workflows/ci.yaml
=> Set chart-testing-action version to a v1.1.0. Unreleased v2 (master) has breaking changes

.github/workflows/release.yaml
=> Used fixed version for chart-releaser-action

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
There's an invalid link in the default values.yml
Fixes #85
=> fix: Event collection link in values.yml

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
=> [datadog] Switch to gcr.io

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/containers-common-env.yaml
Allow using a value passed in to fill in tags
- N/A
=> make dd tags a tpl value

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/agent-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-network-policy.yaml, charts/datadog/templates/agent-network-policy.yaml, charts/datadog/templates/cluster-agent-cilium-network-policy.yaml, charts/datadog/templates/cluster-agent-network-policy.yaml, charts/datadog/templates/kube-state-metrics-cilium-network-policy.yaml, charts/datadog/templates/kube-state-metrics-network-policy.yaml, charts/datadog/values.yaml
=> Add CiliumNetworkPolicy

README.md, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Make sure KSM targets Linux nodes
- fixes #
=> Make sure KSM targets Linux nodes

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
It allows the cluster-agent to access daemonsets
- fixes #426839
=> Allow access to apps/daemonsets

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-psp.yaml, charts/datadog/values.yaml
It fails to deploy on cluster where PodSecurityPolicy pluin is enabled.
- fixes #
- [x ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ x] Chart Version bumped
- [ x] `CHANGELOG.md` has beed updated
- [ x] Variables are documented in the `README.md`
=> Fixes issues deploying with PodSecurityPolicies enabled.

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/kube-state-metrics-network-policy.yaml
- fixes #
- [ x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ x] Chart Version bumped
- [ x] `CHANGELOG.md` has beed updated
- [ x] Variables are documented in the `README.md`
=> Update network policy for kube-state-metrics

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-init-linux.yaml, charts/datadog/templates/_containers-init-windows.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/_system-probe-init.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
=> Change default values to give best experience OOTB

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-network-policy.yaml
=> Open port 8000 for Admission Controller ingress

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1beta1.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogmetrics.yaml
Update the CRDs from their upstream project thanks to the `update-crds.sh` script.
=> Update the CRDs

.github/workflows/release.yaml
Update helm-chart-releaser to fix in index.yaml the "generated" field not being updated
- fixes #142
=> Update helm chart releaser to v1.2.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md
=> Release operator chart

.github/workflows/release.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md
Fix this https://github.com/DataDog/helm-charts/runs/2040371177?check_suite_focus=true
- fixes #
=> [datadog] Fix releaser and publish datadog 2.10.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/daemonset.yaml
- Add provider labels (deployments, daemonset and pods)
- Config warning on UDS configuration for dogstatsd - not supported in this env.
- fixes #
=> [datadog] GKE Autopilot config updates

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
The problems fixed here are similar to the one fixed in https://github.com/DataDog/helm-charts/pull/87.
=> fix some helper functions to support helm2

.github/workflows/ci.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Update `agent.customAgentConfig` config example in the `values.yaml`: removes reference to APM configuration.
- fixes #220
=> [datadog] update agent.customAgentConfig config example

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
Removing comment character in json string for the issue found in #225
- fixes #225
- include #226
=> [datadog] Fix seccomp json profile parsing

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
=> [datadog] KSM Core documentation

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/agent-clusterchecks-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-pdb.yaml, charts/datadog/templates/agent-clusterchecks-rbac.yaml, charts/datadog/templates/agent-network-policy.yaml, charts/datadog/templates/agent-services.yaml, charts/datadog/templates/checksd-configmap.yaml, charts/datadog/templates/cluster-agent-cilium-network-policy.yaml, charts/datadog/templates/cluster-agent-confd-configmap.yaml, charts/datadog/templates/cluster-agent-config-configmap.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-network-policy.yaml, charts/datadog/templates/cluster-agent-pdb.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/confd-configmap.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/datadog-yaml-configmap.yaml, charts/datadog/templates/install_info-configmap.yaml, charts/datadog/templates/kube-state-metrics-cilium-network-policy.yaml, charts/datadog/templates/kube-state-metrics-network-policy.yaml, charts/datadog/templates/rbac.yaml, charts/datadog/templates/secret-api-key.yaml, charts/datadog/templates/secret-application-key.yaml, charts/datadog/templates/secret-cluster-agent-token.yaml
Namespaces are unsettable on ~1/2 the resources
- fixes #217 
I'm not 100% sure I got them all - you might want to add some tests.
=> Add namespace to datadog helm chart templates

charts/datadog/CHANGELOG.md
=> Fix helm chart changelog

charts/datadog/README.md.gotmpl
Fix `README.md` generation in `datadog` chart. Update also the `README.md.gotmpl`.
- fixes #
=> [datadog] Fix Readme generation

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/rbac.yaml
=> OpenShift: Automatically use built-in SCCs instead of failing if create SCC option is not used

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
Update RBAC rules to allow collecting jobs & cronjobs from the DCA.
- fixes #
=> Add new RBAC rules for jobs and cronjobs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml
=> [dca] [rbac] Add new RBAC rules for daemonsets

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Remove usage of `lookup` function to detect OpenShift.
Fix #279 
=> Fix failures with Helm2 (remove one way of detecting cluster is OpenShift)

.github/workflows/release.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl, charts/datadog/values.yaml
Prepare moving to `main` as default branch
- fixes #
=> Prepare moving to `main` as default branch

.github/dependabot.yml
Signed-off-by: Spencer Gilbert <spencer.gilbert@datadoghq.com>
Enables dependabot to update Github actions automatically
- fixes #
=> Add dependabot config to keep actions up-to-date

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Per the issue https://github.com/DataDog/datadog-agent/issues/8895 
- fixes #
=> Default the version of the agent to 7.30.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
We should now use the official product names in the security agent configuration.
- fixes #
=> Update descriptions for securityAgent configuration

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-cilium-network-policy.yaml
Fix CiliumNetworkPolicy spec format. Tested against Cilium 1.10.3
- fixes #373
=> Fix cilium network policy for APM port

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/update-crds.sh
=> [datadog-crds] cleanup update-crds.sh script

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/update-crds.sh
Removes unnecessary if condition in update-crds script.
Reference: https://github.com/DataDog/helm-charts/pull/382/files/d4453f709884bd3ba1ae0b50c9f6d12a6cec5428#diff-5841bc7d6e34bd3008b80815f39d6ea4374297274eaa2b5d4d4d702386ad75be
=> [datadog-crds] Remove unnecessary if condition in update-crds script

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
=> Update Operator to 0.7.2 and CRDs to 0.4.4

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/update-crds.sh, crds/datadoghq.com_datadogagents.yaml
=> Reduce further DatadogAgent CRD size

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
=> Bump datadog-crds chart version in datadog and datadog-operator

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/kube-state-metrics-core-rbac.yaml
KSM Core in agent 7.33 supports VPA metrics
- fixes #
=> fix: add vpa permissions to ksm core rbacs

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl, charts/datadog/values.yaml
Rebase, fix conflicts, bump chart versions, update changelog of the below-mentioned contributors’ PR.
Those contributors’ PR changes are OK but they were pending conflict resolution.
* fixes #285
* fixes #298
* fixes #349
* fixes #427
* fixes #431
=> Rebase, fix conflicts, update changelog etc. of several pending PR

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
- Upgrade chart PL version to 1.18.0
=> [synthetics-pl] upgrade chart version

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
What this PR does / why we need it:
Upgrade chart PL version to 1.18.1
=> [synthetics] Upgrade chart PL version to 1.18.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_daemonset-volumes-windows.yaml
Retrofit doc team feedback from [here](https://github.com/DataDog/documentation/pull/12703#pullrequestreview-843047752).
=> Fix some typos in comments

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location has been updated to version 1.19.0, this PR updates the chart to reflect that.
- fixes #
=> [synthetics-private-location] update chart with new version of the PL

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-services.yaml
=> Rename the APM port in the local traffic policy service from `apm` to `traceport`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
Update RBACs for Kubernetes resource collection
- fixes #
=> Update cluster-agent RBAC for new resources

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/daemonset.yaml
* Improves how securityContext are set depending on the `targetSystem` option (fix #590).
- fixes #590
=> fix(datadog): improve securityContext on windows

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
=> Remove use of `concat` to restore Helm2 compatibility

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Fix scheduling of Helm check due to missing `helm.yaml` in Cluster Agent `confd`.
- fixes #
=> Fix scheduling of Helm check

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Update `cluster-agent` image to the latest stable version: `1.19.0`
=> feat(datadog): cluster-agent version 1.19.0

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogmetrics.yaml, crds/datadoghq.com_datadogmonitors.yaml
Update CRDs from Datadog Operator `v0.8.0`.
=> Update crds from operator 0.8.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml
Update chart for operator `v0.8.0`.
=> [datadog-operator] Update chart for operator 0.8.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
Fixes https://github.com/DataDog/datadog-agent/issues/11059 and https://github.com/DataDog/datadog-agent/issues/9952
=> Add renameat2 to seccomp profile

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds a configuration for CWS networks events.
- fixes #
=> CWS: add network config

.github/workflows/ci.yaml
Update kubernetes versions to the last patch release for each version used in the CI.
- fixes #
=> ci: update kubernetes versions in CI

.github/workflows/ci.yaml, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml
Fix documentation present in the `datadog-operator` chart `values.yaml` file to ease
`helm-docs` update proposed in #660 
- fixes #
=> [datadog-operator] fix values.yaml file docs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-network-policy.yaml, charts/datadog/templates/agent-network-policy.yaml
Use less gendered language, and slightly rework wording, in some notes
on pod / service annotations
=> docs: update note on annotations

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md
Follow up of #690 
- fixes https://github.com/DataDog/helm-charts/issues/689
=> Updating operator chart

.github/CODEOWNERS
Updates codeowners to use `ebpf-platform` team
=> Update CODEOWNERS to use ebpf-platform

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml, examples/datadog/agent_on_aks_values.yaml
Add parameter to activate specific label selectors on AKS
Fixes issue [ #10413](https://github.com/DataDog/datadog-agent/issues/10413)
=> Add parameter to activate specific label selectors on AKS

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
=> add required capability to make auth_token readable

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml
Follow up to #835.
Do not merge until 0.8.4 is released.
=> Updating Datadog Operator dependency on Datadog Monitor/Agent CRD

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/templates/configmap.yaml, charts/observability-pipelines-worker/values.yaml
Updating OPW image to the `1.0.0` tag, matching the chart version.
Small number of updates to point to the newly added OP documentation.
- fixes #
=> [observability pipelines worker] GA release

charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl
Updates the Helm uninstall command. 
- fixes #
[Helm's official documentation ]( https://helm.sh/docs/helm/helm_delete/)states that helm delete has been replaced with [helm uninstall](https://helm.sh/docs/helm/helm_uninstall/)
**Note:**
- [Helm v3 release](https://helm.sh/blog/helm-v3-beta/#notable-changes-since-helm-v2)
> Instead of using the --purge flag on helm uninstall the behavior is to use the --keep-history if you want to keep the history.
=> Update README.md - Helm uninstall command

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/_helpers.tpl
Fix commonLabels duplicated in Deployment
- fixes #840 
=> [synthetics-private-location] Fix commonLabels duplicated in Deployment

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/daemonset.yaml
=> Adding logic to not mount auth-token volume in autopilot

charts/datadog-crds/CHANGELOG.md
Add missing `0.6.0` changelog entry.
- fixes #
=> Fix missing changelog entry

charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/values.yaml
=> Fix operator readme typos

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Targets `nightly-2023-05-04` with the latest OPW changes.
- fixes #
=> [OPW] Release 1.2.0-rc.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
Allows to enable Data Streams Monitoring via configuration value.
- fixes #
=> dsm: Added an option to enable DSM

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
We need new permissions for the datadog cluster agent leader election
=> [helm][dca][rbac] Add `get`, `create`, `update` leases permission to dca

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Removes old comment about "private beta".
- fixes #
=> usm: Remove private beta comments

.github/workflows/no-ci.yaml, .gitlab-ci.yml
Add `.gitlab-ci.yml` file to run E2E tests (and other tests when they get added) 
- fixes #
=> Add gitlab CI

charts/datadog/CHANGELOG.md
Fix to the changelog entry that had the incorrect message for this version
=> [datadog] Update changelog message for v3.30.8

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
=> fix(datadog): update `collectedEventTypes` field documentation

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Add AP1 Site Comment in `values.yaml` of operator.
- fixes #
Fix PR of https://github.com/DataDog/helm-charts/pull/1081
=> Add ap1 to yalue.yaml of operator

test/datadog-operator/baseline_test.go
Ignore chart version in baseline tests. 
Verified by bumping operator chart version and running `make unit-test`.
- fixes #
=> Ignore chart version in baseline tests

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release `1.4.0`
- fixes OPB-1018
=> [observability-pipelines-worker] 1.4.0 release

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version `1.5.0`
- Resolves OPB-1064
=> [observability-pipelines-worker] 1.5.0 release

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go
Operator 1.2.0 release update.
- fixes #
=> Update Operator chart for 1.2.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Fix typos and extraneous lines that were noticed
- fixes #
=> [datadog] correct typos

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
=> [datadog] fix template for older Helm versions

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
OPW-109
* Official release of OPW 1.6.0
=> [observability-pipelines-worker] 1.6.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
=> Fix registry helper to prioritize .Values.registry

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/gke-autopilot-cri-less-values.yaml
=> [datadog] fix test values file in CI

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
Fixing type in warning message
=> [APM Onboarding] Fix chart checks

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
=> [observability-pipelines-worker] 1.7.0 release

charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go
Update Operator chart for 1.3.0 release
- fixes #
=> Update Operator chart for 1.3.0 release

test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go, test/operator-eks-addon/baseline/chart_render_default.yaml, test/operator-eks-addon/baseline_test.go, test/operator-eks-addon/testmain_test.go
Add baseline test (without assertion) and refresh other baselines, make other tests pass on this branch.
- fixes #
=> Generate baseline file for wrapper chart; update others for this branch

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/system-probe-activity-dump-values.yaml, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds the needed security profiles/auto suppression parameters and enable auto suppression by default
- fixes #
=> [CWS] add auto suppression parameters

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Upgrade the private location to version 1.45.0.
=> [Synthetics] Update PL version to 1.45.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
=> Fix typo in notes

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogslos_v1beta1.yaml, charts/datadog-crds/update-crds.sh, charts/datadog-crds/values.yaml, crds/datadoghq.com_datadogagentprofiles.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogmonitors.yaml
Updates CRDs for operator 1.5.0
- fixes #
=> Update CRDs for operator 1.5.0

.github/workflows/go-test.yaml, Makefile, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go
=> Add Operator 1.5.0

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, charts/operator-eks-addon/Chart.lock, charts/operator-eks-addon/Chart.yaml, charts/operator-eks-addon/README.md, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go, test/operator-eks-addon/baseline/chart_render_default.yaml
- fixes #
- [] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
=> Update add-on to Operator 1.4.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
- fixes #
- Deploying with `language_detection.enabled: true`:
```
datadog:
apiKeyExistingSecret: datadog-secret
appKeyExistingSecret: datadog-secret
kubelet:
tlsVerify: false
apm:
instrumentation:
enabled: true
```
From cluster agent config:
```
language_detection:
enabled: true
reporting:
buffer_period: 10s
enabled: true
refresh_period: 20m
cluster_agent:
.........
language_detection:
cleanup:
language_ttl: 30m
period: 10m
patcher:
enabled: true
.....
auto_instrumentation:
container_registry: gcr.io/datadoghq
enabled: true
endpoint: /injectlib
inject_auto_detected_libraries: false
```
From cluster agent cluster role (patch permission is added):
```
- apiGroups:
- apps …
```
=> add language detection apm config

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, crds/datadoghq.com_datadogagentprofiles.yaml, crds/datadoghq.com_datadogmonitors.yaml
=> Update CRDs for operator v1.6.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/other_default.yaml, test/datadog/dca_AC_sidecar_test.go
=> Update operator chart for 1.6.0

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
=> [OPA-2008] Upgrade OPW helm chart to use to 2.1.0 image

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
=> Update datadog-crds chart to latest version

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update charts for 1.50.0 release
=> [Synthetics] Private Location: Release 1.50.0

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/examples/config.yaml, charts/private-action-runner/values.yaml
Extremely small PR to fix the formatting of the PAR YAML files:
- Switch from JSON list notation to the more canonical YAML list notation
- whitespace in actionsAllowlist examples that fixes alignment of the list elements when e.g. using Cmd+/ to uncomment the lines in an editor
NA
=> Private action runner helm chart YAML formatting tweaks

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update charts for 1.50.0 release
=> PL: release 1.51.0

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml
=> Bump PAR version to v0.1.1-beta

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update charts for 1.52.0 release
=> [s8s] Release Private Location 1.52

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
=> Bump runner version to v0.1.3-beta

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/other_default.yaml
=> [dca] [rbac] Add RBAC rules allowing PDB collection

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, crds/datadoghq.com_datadogagents.yaml
Update `datadog-crds` chart with CRDs from the Datadog Operator v1.10.0 tag
- fixes #
=> [datadog-crds] Update CRDs from Datadog Operator v1.10.0 tag

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/other_default.yaml
=> Update operator version to 1.10.0

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 2.2.2
=> [observability-pipelines-worker] 2.2.2 release

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Releasing a new version of the PAR
=> [PAR] update PAR image

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Releasing a new version of the PAR
- fixes #
=> [PAR] update PAR image to v0.1.8-beta

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
=> [ACTP] Bump runner version to v0.1.9-beta

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
=> [observability-pipelines-worker] 2.2.3 release

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/examples/values.yaml
Add an example for gitlab credentials
No need to bump the version, the file is only used as an example (actually bumping to please the CI)
=> [PAR] Add gitlab credentials example

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Upgrades the helm chart with the latest PAR version
- fixes #
=> Upgrade PAR version to v0.1.12-beta

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Upgrade PAR with latest version
=> Upgrade PAR version to v0.1.14-beta

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Update the runner version to v1.0.0
=> [PAR] update PAR image to v1.0.0

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadoggenericresources_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogpodautoscalers_v1.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadoggenericresources.yaml, crds/datadoghq.com_datadogpodautoscalers.yaml
Update datadog-crds chart following Datadog Operator 1.13.0 release
- fixes #
=> [datadog-crds] Update CRDs for Operator 1.13.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
Update datadog-operator chart for 1.13.0 release
- fixes #
=> [datadog-operator] Update chart for 1.13.0 release

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Upgrades the PAR to v1.1.1
- fixes #
=> [ACTP] upgrade image to v1.1.1

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/templates/NOTES.txt, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml
=> [PAR] improve readme instructions

.github/workflows/release-crds.yaml, .github/workflows/release-operator.yaml, .github/workflows/release.yaml
=> [tooling] Separate Operator and CRDs release workflow

.github/workflows/go-test-operator.yaml, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
=> [datadog-operator] Update chart for 1.14.0 pre-release version

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md
=> [datadog-operator] fix changelog

charts/cloudprem/CHANGELOG.md, charts/cloudprem/Chart.yaml, charts/cloudprem/README.md, charts/cloudprem/templates/configmap.yaml, charts/cloudprem/templates/control-plane-deployment.yaml, charts/cloudprem/templates/indexer-statefulset.yaml, charts/cloudprem/templates/janitor-deployment.yaml, charts/cloudprem/templates/job-create-indices.yaml, charts/cloudprem/templates/job-create-sources.yaml, charts/cloudprem/templates/metastore-deployment.yaml, charts/cloudprem/templates/searcher-statefulset.yaml, charts/cloudprem/values.yaml
=> Update CloudPrem Helm chart

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, crds/datadoghq.com_datadogagents.yaml
=> Update crds for 1.15.0-rc.2

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
=> Update image tag to 1.16.0-rc.1

charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl
Improve the documentation of the PAR chart
=> [PAR] instructions for roleType

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
=> Update operator chart for v1.16.0 tag

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/service_account.yaml, charts/datadog-operator/values.yaml
=> Add serviceAccount.automountServiceAccountToken option

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Updates PL version to 1.59.2
- fixes #
=> chore: ⬆️ [synthetics-private-location] bump image version to 1.59.2
