charts/datadog/Chart.yaml, charts/datadog/templates/container-agent.yaml, charts/datadog/templates/containers-init-windows.yaml
Replace the use of `subPath` volume mount option by a copy inside an init container.
- fixes #15
=> Fix Windows support

charts/datadog/Chart.yaml, charts/datadog/templates/system-probe-configmap.yaml
The cilium-based library needs these syscalls for perf buffer epoll usage.
=> Add eventfd and eventfd2 to allowed syscalls for system-probe

charts/datadog/Chart.yaml, charts/datadog/templates/container-system-probe.yaml, charts/datadog/templates/daemonset-volumes-linux.yaml
Only try to mount `/lib/modules` and `/usr/src` when needed.
If the kernel sources are not installed on the host, `/lib/modules` and `/usr/src` might not exist on the host.
In that case, attempting to mount those `hostPath` will make the CRI create the directories on the host.
If the root filesystem of the host is read-only, it will fail.
So, let attempt to mount those paths only if the user has explicitly enabled a feature that requires them.
=> Only try to mount /lib/modules and /usr/src when needed

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml
The cluster checks runner currently does not mount the config volume unless other volumeMounts are defined. This breaks custom checks defined in `datadog.checksd` and `datadog.confd` without a workaround:
```yaml
clusterChecksRunner:
enabled: true
volumes:
- name: workaround-volume
emptyDir: {}
volumeMounts:
- name: workaround-volume
mountPath: /workaround-ignore
```
N/A
N/A
=> fix: mount config volume always

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
Currently, we don't use `serviceAccount.name` in Deployment when set. Also, changing `serviceAccount.create` behaviour: it will create sa with name provided by helper `datadog-operator.serviceAccountName` if `serviceAccount.create`
=> Fix name of serviceAccount used in Deployment if serviceAccount.name is set

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-network-policy.yaml, charts/datadog/templates/kube-state-metrics-network-policy.yaml, charts/datadog/values.yaml
* Fix the Cluster Agent's network policy (allow ingress from node Agents)
* Add kube-state-metrics network policy
=> Add network policy for KSM

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Update degault `datadog/agent` image tag to `7.23.0`
* Update default `datadog/cluster-agent` image tag to `1.9.0`
N/A
=> Update default images tags

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock
Revert to Helm2 hash in `requirements.yaml` to retain compatibility with Helm 2
- fixes #56
Helm 3 understand Helm 2 hashes but the opposite is not true.
=> Revert to Helm2 hash in `requirements.yaml` to retain compatibility with Helm 2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/container-agent.yaml, charts/datadog/templates/container-trace-agent.yaml, charts/datadog/values.yaml
- Remove port configuration from the default values for liveness and readiness probes.
- Show error notices about port discrepancies in case the user provides their own overrides for the probe settings.
Covers the node, cluster and APM agent settings.
=> [datadog] Show error notices about port discrepancies

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/container-system-probe.yaml
To add common environment variables to the system-probe container. Stuff like tags, and other configuration
- fixes #
Network module without any tags
=> Add common env to system-probe container

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/container-agent.yaml, charts/datadog/templates/container-trace-agent.yaml, charts/datadog/values.yaml
Follow up to previous [PR](https://github.com/DataDog/helm-charts/pull/64).
* Refactor liveness and readiness probes with helpers to allow user overrides with other types of probes or disabling
probes entirely.
* Introduce `clusterChecksRunner.healthPort` default setting.
* Use health port defaults instead of hardcoded values.
- fixes #
=> [datadog] Refactor liveness and readiness probes

charts/synthetics-private-location/.helmignore, charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/README.md.gotmpl, charts/synthetics-private-location/templates/_helpers.tpl, charts/synthetics-private-location/templates/configmap.yaml, charts/synthetics-private-location/templates/deployment.yaml, charts/synthetics-private-location/templates/service_account.yaml, charts/synthetics-private-location/values.yaml
It adds a chart for Datadog Synthetics Private Locations
=> [synthetics] add Private Location helm chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
* Support adding labels to the Agent pods and daemonset via `agents.additionalLabels`.
* Support adding labels to the Cluster Agent pods and deployment via `clusterAgent.additionalLabels`.
* Support adding labels to the Cluster Checks Runner pods and deployment via `clusterChecksRunner.additionalLabels`.
- fixes #43 
=> [charts/datadog] Support additional labels

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/container-process-agent.yaml, charts/datadog/templates/container-security-agent.yaml, charts/datadog/templates/container-system-probe.yaml, charts/datadog/templates/container-trace-agent.yaml, charts/datadog/values.yaml
Propagate agents volume mounts to all agent containers
- fixes AKS certificate issue with the process-agent as the crt volume is not mounted
=> Propagate agents volume mounts to all agent containers

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/cluster-agent-values.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/containers-common-env.yaml, charts/datadog/values.yaml
After merging https://github.com/DataDog/datadog-agent/pull/6400 we decided to increase the enforced limits of 40 characters to 80.
This PR addresses this by enforcing an overall limit of 80 characters because with HELM we cannot make sure that `hostname+cluster-name` < 255. With the limit of 80 we can catch most of the cases.
Additionally, we can remove the enforcement of parts being maximum 40 chars: `<part>.<part>`
- test with the given cluster-name from `cluster-agent-values.yaml`
```
helm template ./charts/datadog --debug -f ./charts/datadog/ci/cluster-agent-values.yaml  > /dev/null
```
- change the cluster-name in `cluster-agent-values.yaml` to be higher than 81 chars
```
helm template ./charts/datadog --debug -f ./charts/datadog/ci/cluster-agent-values.yaml  > /dev/null
```
will …
=> Enforcing clustername maximum helm limit

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/container-process-agent.yaml, charts/datadog/templates/containers-init-linux.yaml, charts/datadog/templates/daemonset-volumes-linux.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
To preserve backwards compatibility, there is some special behavior when systemProbe.enabled=true.
Please see the following truth table for what behaviors should be
available when different values are set:
```
systemProbe.enabled     runtimeSecurity.enabled        networkConfig.enabled  agent features
no                      no                             no                     nothing enabled
no                      no                             yes                    system probe enabled, network config enabled
no                      yes                            no                     system probe enabled, network config disabled
no                      yes                            yes                    system probe enabled, network config enabled
yes                     no …
```
=> Allow the system-probe to be run without network performance monitoring being enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Fix `should-enable-system-probe` helper function to support helm2 builded with a buggy golang version ([issue](https://github.com/golang/go/issues/30948))
in the [template function](https://github.com/DataDog/helm-charts/blob/67b9149a9dfa69ada69c5c98d16d2df3799d4c27/charts/datadog/templates/_helpers.tpl#L194) an extra blank character was present, which trigger the golang lexer bug. 
- fixes #84
=> Fix should-enable-system-probe helper function to support helm2

.github/ct.yaml, .github/workflows/ci.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
https://kubernetes-charts.storage.googleapis.com is moving to https://charts.helm.sh/stable and on Nov 13, 2020, the chart downloads will be redirected to the read-only archive GitHub Pages of helm charts (Please see: https://helm.sh/blog/charts-repo-deprecation/). This redirection can possibly cause some disruption. Given that the upstream resolution at https://github.com/kubernetes/kube-state-metrics/issues/1153 might not happen before Nov 13, moving to https://charts.helm.sh/stable might be a safer option in the interim
- fixes https://github.com/DataDog/helm-charts/issues/75
=> move kube-state-metrics sub-chart from google registry to charts.helm.sh

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/container-process-agent.yaml
https://github.com/DataDog/helm-charts/pull/71 introduced a change that added the `networkMonitoring.enabled` flag. That included a regression that required systemProbe.enabled to be set to make sure the system-probe socket mounts were enabled in the process-agent container.    
=> Fix bug in process-agent mounts

charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-scc.yaml, charts/datadog/templates/daemonset.yaml
The enabling securityAgent.compliance but not useHostPID, it created an inconsistency where it would be enabled in the daemonset but not enabled in the SCC for OpenShift. The result was failed deployment in OpenShift.
Tested with OpenShift 4 on Azure (ARO).
=> Makes handling of useHostPID consistent

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md
Update `datadog-crds` `chart.yaml` `apiVersion` to `v1` to maintains `helm 2` compatibility.
I discovered the issue when I wanted to use it in the `datadog` chart.
=> Update datadog-crds chart.yaml apiVersion to v1

.github/CODEOWNERS, charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
* Update default docker image from dockerhub to gcr.io
* Update `CODEOWNERS` file to assign automatically to the `synthetics` team,  PRs releated to `synthetics-private-location` 
N/A
=> [synthetics-private-location] Use gcr.io instead of Dockerhub

.github/ct.yaml, .github/workflows/ci.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml, charts/datadog/values.yaml
Add the `datadog-crds` chart as dependency of the `datadog` chart, to ease the `DatadogMetrics` CRD installation.
Now, when someone set  `clusterAgent.metricsProvider.useDatadogMetrics=true`, the CRD `DatadogMetrics` is installed.
- fixes #
=> Add 'datadog-crds' chart as 'datadog' dependency

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/values.yaml
We need to have pod annotations on cluster checks runner pods to allow meshing the service with Linkerd service mesh
- fixes #
=> fix(datadog): support cluster checks runner pod annotations

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/disable-apparmor.yaml, charts/datadog/ci/kubeval.yaml, charts/datadog/ci/no_hardened_seccomp-values.yaml, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/container-process-agent.yaml, charts/datadog/values.yaml
* systemProbe.enabled is now implicitly true if oomKill or
tcpQueueLength are enabled
* fixes a bug where DD_SYSTEM_PROBE_ENABLED environment variable was not
explicitly set to "false" when neither the systemProbe.enabled nor
networkMonitoring.enabled flags are flipped on. In those cases, the
process-agent should explicitly disable the system-probe so the
connections check does not get enabled.
=> Deprecate systemProbe.enabled and avoid incorrectly enabling NPM  

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/container-agent.yaml, charts/datadog/templates/container-process-agent.yaml, charts/datadog/templates/container-security-agent.yaml, charts/datadog/templates/container-trace-agent.yaml, charts/datadog/templates/containers-common-env.yaml
Fix `process-agent`, `trace-agent` communication with DCA for tagging purpose.
When the `cluster-agent` is enabled, the agents should communicated with the
`cluster-agent` to retrieved tags like `kube_service` instead of communicating
directly with the Kubernetes API-Server.
N/A
=> Fix process-agent, trace-agent communication with DCA for tagging purpose.

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/container-agent.yaml, charts/datadog/values.yaml
* Add a new field `datadog.dogstatsd.tags` to configure `DD_DOGSTATSD_TAGS`.
- fixes #111
=> Add datadog.dogstatsd.tags field

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/container-agent.yaml
Following https://github.com/DataDog/helm-charts/pull/101 the proper agent volumeMounts need to be set if the oom kill or tcp queue length checks are enabled.
=> [datadog-agent] fix agent container volumeMounts

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/container-system-probe.yaml, charts/datadog/values.yaml
Similar to other agents, this allows the system-probe to run with
privileged=true.
=> [datadog] allow setting privileged securityContext for system-probe

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, examples/datadog/agent_basic_values.yaml, examples/datadog/agent_on_openshift_values.yaml, examples/datadog/agent_on_rancher_values.yaml, examples/datadog/agent_with_cluster_agent_values.yaml, examples/datadog/agent_with_containerd_values.yaml
Updates the default agent image to 7.24.1
=> [datadog-agent] update agent to 7.24.1

.github/kubeval.sh, .github/workflows/ci.yaml, .gitignore, CONTRIBUTING.md, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
Improve Helm CI
Mount `/tmp` as an empty dir in all Agent containers
=> Improve CI and add /tmp as an empty dir to prepare for VOLUME removal in Dockerfile

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml
Mount `/etc/passwd` as readonly in process agent
=> [datadog-agent] Mount /etc/passwd as readonly in process agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-network-policy.yaml, charts/datadog/templates/cluster-agent-psp.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
- 53/UDP - Cluster Agent clusters were not able to resolve hostnames 
- 6443/TCP - When Orchestrator is enabled, Cluster Agent would fail to start with message "Error: unable to read authentication token file: open /etc/datadog-agent/auth_token: no such file or directory"
- The chart does not create PSPs for Cluster Agents.
Deploying a Cluster Agent with Network Policies fails.
- fixes #
- [ x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ x] Chart Version bumped
- [ x] `CHANGELOG.md` has beed updated
- [ x] Variables are documented in the `README.md`
=> Address Cluster Agent deployment issues on secure clusters

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/kubeval.yaml, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/values.yaml
Add `ports` options to all Agent containers
https://github.com/DataDog/helm-charts/issues/123
=> Add `ports` options to all Agent containers

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/kubeval.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/values.yaml, examples/datadog/agent_basic_values.yaml, examples/datadog/agent_on_aks_values.yaml, examples/datadog/agent_on_openshift_values.yaml, examples/datadog/agent_on_rancher_values.yaml, examples/datadog/agent_with_cluster_agent_values.yaml, examples/datadog/agent_with_containerd_values.yaml
Add a new field `datadog.kubelet.host` to override `DD_KUBERNETES_KUBELET_HOST` when set
Add a new field `datadog.kubelet.tlsVerify` to toggle `DD_KUBELET_TLS_VERIFY`
=> [datadog-agent] add datadog.kubelet params

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
This PR enables the orchestrator explorer by default.
The important point of that PR is that it shouldn't introduce major incompatibilities for users, upgrading the helm chart shouldn't make the agent fail. As many variables comes into play, let's list the various scenarios.
Pre-requisites:
- Up to agent 7.24.x, the pod check on the process-agent requires that the `DD_ORCHESTRATOR_CLUSTER_ID` env variable is set. This is taken care of by our helm chart here: https://github.com/DataDog/helm-charts/blob/master/charts/datadog/templates/_container-process-agent.yaml#L38-L44
- With the next agent release (7.25.x), the pod check is now able to query the cluster agent to get the cluster_id. As long as the cluster agent is recent enough (future release 1.11), agent 7.25.x is able to live without …
=> Enable the orchestrator explorer by default

Makefile, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml
If `datadog.kubelet.tlsVerify` is set to false, `DD_KUBELET_TLS_VERIFY` is not set, leading to ignoring the value.
=> Fix datadog.kubelet.tlsVerify when set to false

charts/datadog-crds/update-crds.sh
Update the `update-crds.sh` script.
* `brew` now installs `yq` 4 which isn’t compatible with `yq` 3;
* Fix `shellcheck` warnings.
=> Update the `update-crds.sh` script for `yq` 4

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/values.yaml
Fixes several small issues introduced in 2.7-2.8.
Revert default installation of `DatadogMetric` CRD as it can conflict in several ways and there's no straightforward way to manage it better with Helm.
- fixes #
=> Fix multiple bugs introduced in Charts 2.7/2.8 (kubelet, datadogMetrics, clusterChecks)

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/rbac.yaml
Grant access to the `Lease` objects.
This extra permission is needed by DataDog/integrations-core#8535.
=> Grant access to the Lease objects

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/rbac.yaml
Adds `namespaces` in RBAC for DCA and node agent when DCA is not enabled. This is used for the `kubernetes_namespace_labels_as_tags` feature.
=> [datadog] Add namespaces in RBAC

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/agent-services.yaml, charts/datadog/values.yaml
Add support for Service Topology to target the Datadog Agent via a kubernetes service instead of host ports. This will allow sending traces and custom metrics without using host ports. Note: Service Topology is a new Kubernetes feature, it's still in alpha and disabled by default.
=> [datadog] Support Service Topology for apm and dsd

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
Currently it is not possible to disable the network monitoring (while leaving system-probe enabled) by setting `datadog.networkMonitoring.enabled` to `false`. This PR fixes that.
=> Fix `networkMonitoring.enabled` behavior when set to `false`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
These are config options that have existed for many agent releases under the
system_probe_config namespace.
The config option is intentionally under systemProbe and not
networkConfig to be consisent with other options under
system_probe_config that preceded the network_config block.
=> Add conntrack opts for systemProbe

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Make `datadog.leaderElection` works properly. This boolean variable is used in the following way in the template.
```
{{ default "true" .Values.datadog.leaderElection | quote}}
```
If `datadog.leaderElection` is set to `false` (boolean) , the left side will be evaluated as false, so the default value of `"true"` will be set, and `"false"` (string) will not be set.
In addition, the default value of `datadog.leaderElection` is written in values.yaml, so no need to describe it here.
- fixes #170 
=> Fix a bug related to datadog.leaderElection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-psp.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
- Support [running Datadog Agent](https://www.datadoghq.com/blog/gke-autopilot-monitoring/) on [GKE Autopilot](https://cloud.google.com/blog/products/containers-kubernetes/introducing-gke-autopilot) 🚀 
- Introduce a new section in the chart configuration values for easy setup of cloud provider options.
=> [datadog] ✨ New! ✨ Support running Datadog Agent on GKE Autopilot ✨

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Add missing NET_RAW capability to the system-probe container.
This capability is now requiered with CRIO due to a patch remediation
for the CVE-2020-14386.
- fixes #
=> [datadog] Add missing NET_RAW Cap for CVE-2020-14386 mitigation

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Allow cluster-agent to override metrics provider endpoint through setting `DD_EXTERNAL_METRICS_PROVIDER_ENDPOINT`, added to the cluster-agent in https://github.com/DataDog/datadog-agent/pull/6952.
=> Allow cluster-agent to override metrics provider endpoint

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Configure/enable prometheus AD. Requires Datadog Agent 7/6.26+ and Datadog Cluster Agent 1.11+.
=> [datadog] Support prometheus autodiscovery

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml
Adds main agent config to system-probe container. This will allow flares to be sent from the system-probe container.
=> Add main agent config to system-probe container

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
* Support configuring the secret backend command arguments (requires Datadog Operator v0.5.0+)
Related to https://github.com/DataDog/datadog-operator/pull/196
=> [datadog-operator] Add SB args 

.github/workflows/release.yaml
An attempt to fix this after bumping helm releaser version
```
Run helm/chart-releaser-action@v1.2.0
Looking up latest tag...
Discovering changed charts since 'datadog-2.9.11'...
Installing chart-releaser...
Adding cr directory to PATH...
Packaging chart 'charts/datadog-operator'...
Error: no repository definition for https://helm.datadoghq.com
```
=> Fix releaser

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/pod_disruption_budget.yaml
Currently with the default replica as 1 and the default deployment of the pod disruption budget requiring 1, means that when performing a node drain / upgrade will timeout:
> Drain did not complete pods [datadog-operator-55dc4888bf-94x5j] within 10m0s on vm *****. Check Pod Disruption Budgets
This simply disables deployment of the `PodDisruptionBudget` until the `replicaCount` is set to something greater than 1. Otherwise by default, users that use this operator won't be able to upgrade without manual intervention. 
=> Only deploy PodDisruptionBudget when replicaCount > 1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml
Remove the cluster-id configmap mount for process-agent. This is not needed starting with agent 7.25 and dca 1.11 since we use a cluster agent api endpoint for this now.
- fixes #
WIP
=> remove the datadog-cluster-id configmap mount from process-agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-init-linux.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
Use an EmptyDir volume shared between all the agents for logs so that `agent flare` can gather the logs of all of them.
I tested `agent flare` on a Windows pod and it happened to already contain the log files for all the agents.
So, nothing to be done on Windows.
=> Use an EmptyDir volume shared between all the agents for logs so that `agent flare` can gather the logs of all of them.

.github/ct.yaml, .github/workflows/ci.yaml, .github/workflows/release.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_helpers.tpl
Bump the version of the KSM chart.
When we install the datadog chart, Helm produces the following warnings:
```
W0315 15:51:01.542249   64621 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0315 15:51:01.594559   64621 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0315 15:51:01.647086   64621 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0315 15:51:02.684250   64621 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, …
```
=> Bump KSM chart version to use rbac.authorization.k8s.io/v1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-scc.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/cluster-agent-scc.yaml, charts/datadog/values.yaml, examples/datadog/agent_on_openshift_values.yaml
When using OpenShift + hostNetwork + generated SCC, some fields are not properly set, preventing the Agent/Cluster Agent to deploy normally.
Added SCC in to support Cluster Agent with hostNetwork (though, it's not recommended to run the ClusterAgent with hostNetwork).
=> SCC generation was not handling all options properly

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
See https://github.com/DataDog/datadog-agent/pull/7674 for reasoning.
=> Increase default value of datadog.systemProbe.maxTrackedConnections

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Without this, one cannot use "Metric collection with Prometheus annotations" feature.
=> Fix bug regarding using "Metric collection with Prometheus annotations"

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/values.yaml
#165 introduced the possibility for the node agents of an Helm release to join an “external” DCA (i.e. managed by another Helm release).
By doing so, the node agents were also taking part of the cluster check dispatch.
If the DCA is “external”, we should rather let the cluster checks be handled by the agents (CLC) deployed with the DCA.
=> When joining an existing DCA, do not let node agents take cluster checks

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/values.yaml
Add the possibility to specify a `priorityClassName` for the CLC pods like it was already possible for the node agents and the DCA ones.
- fixes #203
=> Add the possibility to specify a priorityClassName for the CLC

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
Fix system-probe version check when using networkMonitoring.enabled
=> [networks] Fix system-probe version check

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
Fix the DCA RBAC.
Since the migration of the DCA to the `go-client` 1.18, the DCA needs some additional permissions to register an external metrics provider.
With the current version of the Helm chart and the `master` version of the cluster agent, the external metrics provider feature is broken and the DCA complains about the following errors:
```
2021-04-02 13:05:10 UTC | CLUSTER | ERROR | (/go/pkg/mod/k8s.io/apimachinery@v0.18.6/pkg/util/runtime/runtime.go:114 in logError) | pkg/mod/k8s.io/client-go@v0.18.6/tools/cache/reflector.go:125: Failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:default:datadog-agent-cluster-agent" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```
``` …
```
=> Fix DCA RBAC for the external metrics provider

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Currently there is no helm values for containers securityContext for cluster-agent. This PR adds the values.
There is already values for podSecurityContext, but there isn't one for containers securityContext.
=> Allow setting containers securityContext for cluster-agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
* Bump Agent version to `7.27.0`.
* Support configuring advanced openmetrics check parameters via `datadog.prometheusScrape.additionalConfigs`.
Agent version bump requires a minor chart version bump
=> Support additional prometheus config + bump agent version

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl, charts/datadog/values.yaml
Update the documentation with the new path of the `kube-state-metrics` chart.
The previous location is deprecated and was not used anymore since https://github.com/DataDog/helm-charts/pull/194/files#diff-589714dd7d270f1837bc49b48c888d176ed262de781316a9aaf5e7fcd0b4ad03R6
=> Update the documentation with the new path of the `kube-state-metrics` chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/cluster-agent-confd-configmap.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
- Bump the DCA version
- Support configuring the ksm core check in the cluster agent
=> [datadog] DCA 1.12 + Support KSM core basic config

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
Apply this change https://github.com/DataDog/datadog-agent/pull/7754
DCA 1.12 must be released before merging this PR
=> [DCA] Use Role instead of ClusterRole for secrets RBAC

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml
Fix Kubelet connection on GKE-autopilot environment: force `http` endpoint to retrieves pods information.
Thanks to this fix, all the auto discovery and tagging features work on GKE autopilot
- fixes #182
=> [datadog] Fix kubelet connection on GKE Autopilot env

charts/datadog/README.md
Adding the flag (`--recreate-pods`) to the helm install command is not necessary anymore, and it has been deprecated in Helm 3. This line should be removed because customers are attempting to run this flag with helm 3, or are looking for workarounds to achieve the same result.
- fixes #
=> Remove note about --recreate-pods

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/gke-autopilot-values.yaml, charts/datadog/templates/_containers-common-env.yaml
* Fix `YAML parse error on datadog/templates/daemonset.yaml` when gke.autopilot is enabled.
- fixes #255
=> [datadog] fix install when gke.autopilot:true

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, crds/datadoghq.com_datadogmetrics.yaml
Fix type in `DatadogMetrics` CRD definition:
*  `reversed` -> `reserved`
- fixes #
=> [datadog-crds] Fix typo in datadogmetrics

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Bump default agent version to `7.28.0`.
=> Bump agent version to `7.28.0`

charts/datadog/CHANGELOG.md, charts/datadog/README.md, charts/datadog/ci/agent-with-dynamic-annotations.yaml, charts/datadog/ci/cluster-agent-and-worker-with-dedicated-rbac-values.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/rbac.yaml, charts/datadog/values.yaml
Adds Annotations to the Cluster Agent and Agent Service Accounts. Required for using IAM Roles for Service Accounts in EKS.
Update the Agent Pod Annotations to accept variables defined in a values.yaml.
- fixes #263 
=> Add Service Account Annotations and Template Agent Pod Annotations

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
This PR updates the version of the private location image used in helm charts.
- fixes #
=> Update private location image version

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Bump datadog agent version to `7.28.1`.
* `tls` check had a bug in `7.28.0`: https://github.com/DataDog/integrations-core/pull/9433
=> Bump datadog agent version to `7.28.1`

examples/datadog/agent_with_cluster_agent_values.yaml
Remove unneeded and outdated image configuration for cluster checks runner in an example file
=> [examples] rm unneeded image config

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml
Set `GODEBUG=x509ignoreCN=0` to revert Agent SSL certificates validation to behaviour to Golang <= 1.14. Notably it fixes issues with Kubelet certificates on AKS with Agent >= 7.28.
- fixes #
=> Revert Agent SSL certificates validation to golang 1.14 behaviour

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
Datadog Agent `>= 7.29.0` ships a feature using the `/var/log/containers` symlinks to validate the container ID / pod matching.
- ~[ ] Variables are documented in the `README.md`~
=> Mount `/var/log/containers` for better logs file scanning with short-lived containers.

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml
* Use the pod name as cluster check runner ID to allow deploying multiple cluster check runners on the same node. (Requires agent 7.27.0+)
=> [datadog] Use pod name as cluster check runner ID

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/values.yaml
* Document Autodiscovery management parameters: `datadog.containerExclude`, `datadog.containerInclude`, `datadog.containerExcludeMetrics`, `datadog.containerIncludeMetrics`, `datadog.containerExcludeLogs` and `datadog.containerIncludeLogs`.
* Introduce `datadog.excludePauseContainer` to control autodiscovery of pause containers.
* Introduce a deprecation noticed for the undocumented and long deprecated `datadog.acInclude` and `datadog.acExclude`.
=> [datadog] Document and update Autodiscovery management

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/cluster-agent-with-dynamic-annotations.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml
Adds template expansion to Annotations and Service Accounts for the ClusterAgent.
This allows variables defined in a values.yaml to be evaluated in the ServiceAccount and PodAnnotations sections of the Cluster Agent config. 
Useful for avoiding hard-coding parameters for different clusters/environments.
=> Enable template expansion for Cluster Agent Annotations and Service Account

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
* Add a configuration field `collectOperatorMetrics ` to disable/enable collecting operator metrics
=> [datadog-operator] Add `collectOperatorMetrics ` config

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update `datadog` chart to use the latest `agent` and `cluster-agent` releases:
* Update `agent` image tag to `7.29.0`.
* Update `cluster-agent` image tag to `1.13.0`.
=> [datadog] update agent and cluster-agent image tags

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Update `cluster-agent` image tag to `1.13.1`.
- fixes #
=> [datadog] update DCA image to 1.13.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/values.yaml
Expose the Unix Domain Sockect for Dogstatsd in an emptyDir volume by default. It will allow
the "JMX-Fetch" process to always use the UDS socket to send metrics to the `core-agent`.
=> [datadog] Expose UDS for Dogstatsd in an emptyDir volume by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
=> Honor `doNotCheckTag` in Env AD detection, preventing install failures with custom images using non semver tags

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Add "DD_TAGS" in cluster-agent container envvars when needed.
The envvar "DD_TAGS" generated from `datadog.tags` was not added
to the `cluster-agent` container envvars.
- fixes #304 
- fixes #305
=> [datadog] Fix missing DD_TAGS envvar in cluster-agent deployment

charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Fixes the description for the corresponding Agent, Cluster Agent, and Cluster Checks Runner `rbac.serviceAccountName` configuration options. To more accurately reflect that this is used to reference a preexisting `ServiceAccount` rather than giving the option to customize the generated name for the `ServiceAccount`.
CONS-4012
=> Fix descriptions for Agent, DCA, and Check Runner rbac.serviceAccountName

.github/ct.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
* Move to `https://prometheus-community.github.io/helm-charts` helm chart registry for the `kube-state-metrics` dependency in the `datadog` chart.
- fixes #307
=> [datadog] move to the new kube-state-metrics chart registry

.github/workflows/ci.yaml, .github/workflows/release.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md
the helm chart registries are defined in several files. In previous #309 PR, I forgot to update the `kube-state-metrics` registry in the release workflow configuration. 
=> [datadog] Fix release process after kube-state-metrics registry update

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-trace-agent.yaml
* Fix `dsdsocket` volumeMount for the `trace-agent` on windows deployment.
=> [datadog] Fix volumeMount for the `trace-agent` on windows

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Fixes issue where disabling cluster agent wasn't sufficient to disable orchestrator explorer. Prior to the fix, it was noticed that `DD_ORCHESTRATOR_EXPLORER_ENABLED` was set to `true` even if `DD_CLUSTER_AGENT_ENABLED` was `false`. This is because the statement `include "existingClusterAgent-configured" .` in the `if` condition was always returning `true`.
=> [datadog] fix `should-enable-k8s-resource-monitoring` definition

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-trace-agent.yaml
This PR fixes the trace agent container by removing the reference to socket read only mounts on Windows.
Pipes cannot be mounted as read only on windows and this PR introduced a read only mounts by mistake: https://github.com/DataDog/helm-charts/pull/313 for the runtimesocket mount.
Maybe I overlooked a logic introduced by https://github.com/DataDog/helm-charts/pull/300 for the readonly mounts, but I think this should not be there anyway.
=> Remove ref to readonly for socket mounts in trace agent container for Windows

charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl
Updates link to new kube-state-metrics chart location. Instructions on adding the KSM chart were updated, but not the link in the readme.
EDIT: It seems odd to bump the version for a readme change like this, but happy to do so to get CI green
=> Update link to kube-state-metrics chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/values.yaml
Bump datadog-agent image version to latest patch release
https://hub.docker.com/layers/datadog/agent/7.29.1/images/sha256-c06f1d356b73387208dccfc73d799b6c19e63f5e5d13cda5c8d47caa5c89a8a9?context=explore
Keeps the agent up to date for those that install the Chart with default values
- fixes #
- [-] Variables are documented in the `README.md`
=> The queen is dead/agent version bump

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/NOTES.txt, charts/synthetics-private-location/templates/deployment.yaml, charts/synthetics-private-location/templates/secret.yaml, charts/synthetics-private-location/values.yaml
Store configuration in a secret instead of a configMap.
The configuration contains credentials. Therefore it's better to store it in a secret.
This PR changes the following:
- store configFile value in secret instead of configMap
- keep supporting configConfigMap value for backwards compatibility
- add configSecret value
=> [synthetics-private-location] Use secret in stead of configMap

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md
Sets `apiVersion` to `v1` in the datadog-crds chart. This is to be compatible with helm 2.
=> [chart/datadog-crds] Set apiVersion to v1 (for helm 2 compatibility)

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
Updates the datadog chart `datadog-crds` dependency to v0.3.2
=> [chart/datadog] Update datadog-crds dependency to v0.3.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
Big thanks to @ludaires who started this in https://github.com/DataDog/helm-charts/pull/265 👏 
* Print a configuration notice to clarify the containers filtering behavior when a misconfiguration is detected.
- fixes https://github.com/DataDog/helm-charts/issues/331
=> [datadog] Clarify container include/exclude with warning

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/README.md.gotmpl, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetreplicasets_v1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetreplicasets_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsets_v1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsets_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetsettings_v1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetsettings_v1beta1.yaml, charts/datadog-crds/update-crds.sh, crds/datadoghq.com_datadogmetrics.yaml, crds/datadoghq.com_extendeddaemonsetreplicasets.yaml, crds/datadoghq.com_extendeddaemonsets.yaml, crds/datadoghq.com_extendeddaemonsetsettings.yaml
We want to add the charts from the EDS repo in this one. To do that, we'll need to be able to download the CRDs from that repo in the "datadog-crds" chart.
This PR also runs the updated script to add the CRDs from the EDS repo v0.6.0 (latest tag).
=> [datadog-crds] Adapt script to be able to download CRDs from the EDS repo

charts/extended-daemon-set/.helmignore, charts/extended-daemon-set/CHANGELOG.md, charts/extended-daemon-set/Chart.yaml, charts/extended-daemon-set/README.md, charts/extended-daemon-set/README.md.gotmpl, charts/extended-daemon-set/requirements.lock, charts/extended-daemon-set/requirements.yaml, charts/extended-daemon-set/templates/_helpers.tpl, charts/extended-daemon-set/templates/clusterrole.yaml, charts/extended-daemon-set/templates/clusterrole_binding.yaml, charts/extended-daemon-set/templates/deployment.yaml, charts/extended-daemon-set/templates/role.yaml, charts/extended-daemon-set/templates/role_binding.yaml, charts/extended-daemon-set/templates/serviceaccount.yaml, charts/extended-daemon-set/values.yaml
Adds the Extended DaemonSet (EDS) chart as it is in the 0.6.0 tag of its repo.
=> Add Extended DaemonSet (EDS) chart

.github/ct.yaml, .github/kubeval.sh, .github/workflows/ci.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Update default Agent image tag to `7.30.0`
* Update default Cluster-Agent image tag to `1.14.0`
- fixes #
=> [datadog] bump agent and cluster-agent version

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update synthetics private location chart tag to 1.13.0
=> [synthetics-private-location] update version to latest PL image

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
Add `{agents,clusterChecksRunner}.image.tagSuffix` to request JMX or servercore images without having to override the `{agents,clusterChecksRunner}.image.tag` setting and having to explicit the agent version.
- fixes #350
=> Add `{agents,clusterChecksRunner}.image.tagSuffix` to request JMX agent image

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/kube-state-metrics-cilium-network-policy.yaml, charts/datadog/templates/kube-state-metrics-network-policy.yaml
Skip KSM network policy creation when KSM creation is disabled.
- fixes #336
=> Skip KSM network policy creation when KSM creation is disabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl
* Disable by default UDS sockets support for dogstastd and apm on GKE autopilot.
- fixes #182
=> [datadog] always disable UDS socket on GKE autopilot

.github/helm-docs.sh, .github/workflows/ci.yaml, .github/workflows/release.yaml
- Update actions/checkout to v2
- Update chart-releaser-action to 1.2.1
- Update helm-docs to 1.5.0
- fixes #
I ran helm-docs@1.5 locally and it didn't create any diff, and didn't notice any notable changes in their changelog
=> Update GH action versions and helm-docs

.github/workflows/ci.yaml, .github/workflows/release.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Fix the Dogstatsd UDS hostVolume configuration when `useSocketVolume:true`. 
The PR #357 has introduced a bug that reverse the logic about create an `hostVolume` or an `EmptyDir`.
The wanted behaviour is:
* If `useSocketVolume:true` => use an `hostVolume`.
* If `useSocketVolume:false` => use an `emptyDir`.
- fixes #
=> [datadog] Fix Dogstatsd UDS hostVolume configuration

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetreplicasets_v1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetreplicasets_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsets_v1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsets_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetsettings_v1.yaml, charts/datadog-crds/templates/datadoghq.com_extendeddaemonsetsettings_v1beta1.yaml, charts/datadog-crds/update-crds.sh, crds/datadoghq.com_extendeddaemonsetreplicasets.yaml, crds/datadoghq.com_extendeddaemonsets.yaml, crds/datadoghq.com_extendeddaemonsetsettings.yaml
Updates CRDs for EDS v0.7.0 in the `datadog-crds` chart.
EDS v0.7.0 also offers valid `v1` CRDs. That's why this PR adapts the script that downloads CRDs to fetch those too.
=> [datadog-crds] Update CRDs for EDS v0.7.0

charts/extended-daemon-set/CHANGELOG.md, charts/extended-daemon-set/Chart.yaml, charts/extended-daemon-set/README.md, charts/extended-daemon-set/requirements.lock, charts/extended-daemon-set/requirements.yaml, charts/extended-daemon-set/templates/role.yaml, charts/extended-daemon-set/values.yaml
Updates the EDS chart to support v0.7.0.
=> [EDS] Update to 0.7.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
This PR changes the condition for including the system probe socket & config mount in the `agent` container to use the existing `should-enable-system-probe` helper that is defined in `charts/datadog/templates/_helpers.tpl`. This fixes the case where before, certain system probe modules (such as network monitoring) being enabled wouldn't cause the socket/config to get mounted in the agent container (because they weren't included in the condition).
Moreover, this PR is part of a fix (along with https://github.com/DataDog/datadog-agent/pull/9110) to `datadog-agent status` and `datadog-agent flare` to have them correctly report the status of the system probe when it is running. Without the system probe socket & config being mounted, it won't report the status of the system probe when running …
=> Use existing helper to determine whether to mount system-probe socket & config

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default Datadog Agent image to 7.31.0.
* Default Datadog Cluster Agent image to 1.15.0.
- fixes #
=> [datadog] update default image tags

charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/README.md.gotmpl
Fix the instructions to run the script used to update the CRDs. The script no longer accepts a second parameter after merging https://github.com/DataDog/helm-charts/pull/382/
=> [datadog-crds] Fix instructions to run the update-crds script

charts/extended-daemon-set/CHANGELOG.md, charts/extended-daemon-set/Chart.yaml, charts/extended-daemon-set/README.md, charts/extended-daemon-set/README.md.gotmpl, charts/extended-daemon-set/requirements.lock, charts/extended-daemon-set/requirements.yaml, charts/extended-daemon-set/templates/crds/datadoghq.com_extendeddaemonsetreplicasets_v1.yaml, charts/extended-daemon-set/templates/crds/datadoghq.com_extendeddaemonsetreplicasets_v1beta1.yaml, charts/extended-daemon-set/templates/crds/datadoghq.com_extendeddaemonsets_v1.yaml, charts/extended-daemon-set/templates/crds/datadoghq.com_extendeddaemonsets_v1beta1.yaml, charts/extended-daemon-set/templates/crds/datadoghq.com_extendeddaemonsetsettings_v1.yaml, charts/extended-daemon-set/templates/crds/datadoghq.com_extendeddaemonsetsettings_v1beta1.yaml, charts/extended-daemon-set/update-crds.sh, charts/extended-daemon-set/values.yaml
* Add ExtendedDaemonset CRDs directly inside this chart.
- fixes #
=> [extended-daemon-set] Add CRDs inside the chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
Bind mount the host /etc/os-release file for proper host distribution detection
=> Bind mount host /etc/os-release in system probe container

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-cilium-network-policy.yaml
Update the `CiliumNetworkPolicy` of the agent to allow outbound connections to the ECS container agent on `localhost`.
- fixes #387
=> [datadog] Update CNP to grant access to ECS agent on localhost

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Missing tags from Cluster Agent checks/metrics
- fixes #319
=> [datadog] `DD_TAGS` are always added when present

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml
Add RBAC to the operator to allow the creation of the cluster-agent rbac
when the admission controller is enabled
```
- apiGroups:
- datadoghq.com
resources:
- extendeddaemonsetreplicasets
verbs:
- get
- list
- watch
```
- fixes https://github.com/DataDog/datadog-operator/issues/382 
=> Add missing RBAC when the DCA admission controller is enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml, charts/synthetics-private-location/templates/deployment.yaml
Each container will be able to specify environment variables from a secret or configmap exclusively, therefore not requiring every container to share environment. When you apply the helm config, the dictionaries of `container.` and `datadog.envFrom` will be merged.
- fixes #
I am happy to update the changelog, but I wasnt sure on the versioning, for when this gets approved as to avoid conflicts with other PRs.
=> :sparkles: Allow for envFrom per container instead of exclusively global

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Adds a default required pod anti-affinity for the cluster agent.
When there are several DCA, one is elected the leader and is in charge of doing all the work about dispatching cluster checks.
The non-leader ones are in standby and are waiting for the leader to crash to take the lead.
If the standby instances can run on the same node as the leader, this defeats the purpose.
`datadog-operator` counter-part: DataDog/datadog-operator#381.
=> [datadog] Add a default required anti-affinity for the cluster agent

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
* Add `watchNamespace` option to limit on which namespace the operator can watch resources.
=> [datadog-operator] watch all namespaces by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Makes the runtime socket configurable when running on Windows instead of defaulting to `\\.\pipe\docker_engine`.
=> [datadog] Make Windows runtime socket configurable

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default Datadog Agent image to `7.31.1`.
* Default Datadog Cluster Agent image to `1.15.1`.
=> [datadog] Update Agent to 7.31.1 and DCA to 1.15.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/values.yaml
Adds the option to the process agent for stripping all process arguments.
The option is described [here](https://docs.datadoghq.com/infrastructure/process/?tab=linuxwindows#process-arguments-scrubbing)
The env var is processed by the agent [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/process/config/config.go#L424) 
Was not reported as far as I can tell
Not sure if it make sense for me to bum the version and update the changelog at this point yet.
=> Add option to strip process arguments to the process agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
- Removes prometheus AD annotations for the Cluster Agent
- Avoids duplicated checks (`datadog_cluster_agent` will be triggered via file AD automatically starting agent 7.31)
=> [datadog] Use the datadog_cluster_agent check instead of prometheus

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
When a node has a large number of processes, the system probe container fails. A fix was applied to the agent in https://github.com/DataDog/datadog-agent/issues/8181. This PR will allow you to configure the value, with a default of 10s (default of agent).
=> :wrench: Add configurable init timeout conntrack_init_timeout

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-psp.yaml, charts/datadog/values.yaml
Add an `agents.podSecurity.defaultApparmor` setting to allow customising the default AppArmor profile used by all containers but `system-probe`.
For `system-probe`, there was already the `datadog.systemProbe.apparmor` setting.
Agents other than `system-probe` don’t need any AppArmor privileges so that the `runtime/default` default AppArmor profile should be enough in most cases.
On some setups, however, AppArmor is generating a lot of harmless messages. See DataDog/datadog-agent#6915 for more details.
In order to fix those messages, we can use a custom AppArmor profile as described [here](https://github.com/DataDog/datadog-agent/issues/6915#issuecomment-748077547).
This change adds a parameter in the `values.yaml` of the chart to allow specifying this custom profile.
- fixes #389
[Place …
=> Add an `agents.podSecurity.defaultApparmor` setting

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-services.yaml, charts/datadog/values.yaml
1. Add an option to set the service name use to communicate with the node agent.
2. Add an option to force the activation of internalTrafficPolicy to support Kubernetes version on which the feature is still alpha.
```yaml
agents:
localService:
overrideName: ""
forceLocalServiceEnabled: false
```
- fixes #429
=> Add `agents.localService` parameters

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-cloudinit-volumemounts.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/values.yaml
In EKS backed by EC2, IMDS service may be disabled and hostname
detection will fail. This change allows us to mount the EC2 host's
filesystem and get the hostname through the cloud-init provided file
at `/var/lib/cloud/data/instance-id` through DD_HOSTNAME_FILE.
Fixes #419 
=> [datadog] Add option to use EKS EC2 hostname from host filesystem

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/cluster-agent-values.yaml, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
**What this PR does / why we need it:**
feat/fix: defined expvarPort, set containerPort for agentmetrics
* Add `datadog.expvarPort` parameter to customize the default 
expvar default port to not conflict with the default clusteragent 
metrics port.
* Defined cluster-agent containerPort `agentmetrics` to expose the 
default port, which is set to 5000 and already defined in the 
`NetworkPolicy` for the cluster-agent.
**Special notes for your reviewer:**
See also 
https://github.com/DataDog/datadog-agent/blob/4f63274038167c7487aa44e0126d42cd6b27fba0/pkg/config/config.go#L659-L660
https://github.com/DataDog/datadog-agent/blob/4f63274038167c7487aa44e0126d42cd6b27fba0/pkg/config/config.go#L576-L585
Closes: #264
**Checklist**
=> feat/fix: defined expvarPort, set containerPort for agentmetrics

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default Datadog Agent image to `7.32.0`.
* Default Datadog Cluster Agent image to `1.16.0`.
- fixes #
=> Update default agent and cluster agent versions

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Fix a typo on `agents.localService.forceLocalServiceEnabled`
=> Fix typo in variable name `agents.localService.forceLocalServiceEnabled`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
- fixes #441 
This adds the ability to set custom annotations in the cluster-agent and also the daemonset for the DD agent. Things like reloader need apps to have annotations to they can monitor a secret. If the secret changes then it can do a rolling restart. 
=> Add annotations to cluster-agent and agents

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update default agent image to 7.32.1
=> [datadog] update agent image to 7.32.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
Add support for USM (Universal Service Monitoring) which is currently under private beta.
The feature is behind a new configuration param: `datadog.serviceMonitoring.enabled`.
Setting it to true has 2 effects:
* Enabling `service_monitoring_config.enabled` inside system-probe's ConfigMap
* Mounting the host root volume under `/host/root`
=> [networks] Add support for USM

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-confd-configmap.yaml, charts/datadog/values.yaml
Expose the `labels_as_tags` setting of the KSM core check introduced by DataDog/datadog-agent#9214 in the Helm chart.
=> [datadog] Expose the `labels_as_tags` parameter of the KSM core check

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-cilium-network-policy.yaml
Adds missing FQDN rules to the agent Cilium network policy.
Resolves `Unable to validate API Key` and `You are currently sending logs to Datadog through TCP...` messages in agent status. 
- fixes #456
I didn't find that the `unable to validate API key` message was breaking anything in the agent, but came across it while investigating Cilium network drops caused #456 so thought I would include the fix for that too.
=> Add missing toFQDNs for agent-http-intake to CilumNetworkPolicy

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_daemonset-volumes-windows.yaml, charts/datadog/templates/_helpers.tpl
Right now you can't mount the custom files in windows pods and a specific config with the security/compliance that makes the pods crash.
Used this custom values file, for a chart named `datadog-windows-test`:
```
➜  datadog git:(charlyf/fix-security-agent-config-conflict) ✗ cat values-custom.yaml
#targetSystem: windows
#existingClusterAgent:
datadog:
collectEvents: true
leaderElection: true
logs:
enabled: true
apm:
enabled: true
processAgent:
enabled: true
clusterChecks:
enabled: true
networkMonitoring:
enabled: true
orchestratorExplorer:
enabled: true
securityAgent:
compliance:
enabled: true
runtime:
enabled: true
kubeStateMetricsEnabled: false
kubeStateMetricsCore:
enabled: true
useClusterCheckRunners: true
confd:
mongo.yaml: |-
ad_identifiers:
- redis
- bitnami/redis
init_config: …
```
=> Fix unsupported config in windows envs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/agent-clusterchecks-rbac.yaml, charts/datadog/templates/cluster-agent-confd-configmap.yaml, charts/datadog/templates/kube-state-metrics-core-rbac.yaml
Fix bugs that prevented running the ksm core check as a cluster check.
- fixes https://github.com/DataDog/helm-charts/issues/460
=> fix: running ksm core as cluster check

.github/kubeval.sh, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default Agent image to `7.32.2`.
- fixes #
=> [datadog] default Agent image to 7.32.2

.github/kubeval.sh, .github/workflows/ci.yaml, charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/extended-daemon-set/CHANGELOG.md, charts/extended-daemon-set/Chart.yaml, charts/extended-daemon-set/README.md, charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md
Fix the following error:
```
WARN - datadog/templates/agent-services.yaml contains an invalid Service (default.RELEASE-NAME-datadog) - internalTrafficPolicy: Additional property internalTrafficPolicy is not allowed
```
=> Pass the proper Kubernetes version to `helm template`

.github/PULL_REQUEST_TEMPLATE.md, charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update the `synthetics-private-location` chart with latest 1.17.0 release.
=> [Synthetics] Update Private Location Chart with release 1.17.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Defaulting to the most recent version of the Datadog Agent.
=> Bumping default version of the Datadog Agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
The CAP_CHOWN capability is needed by system-probe to change the owner of the socket exposed between system-probe and the process agent. (see https://github.com/DataDog/datadog-agent/pull/9434 for more context)
- fixes #474
=> [system-probe] add SYS_CHOWN to the system-probe container

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-priorityclass.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
In Autopilot environments, the default NG is too small to accommodate applications and the agent in certain conditions. This ensures the agent is prioritized and let's Autopilot do the scale up as necessary.
https://github.com/DataDog/helm-charts/issues/409
=> Adding priorityClass for the DD daemonset in Autopilot environments

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
The `SYS_CHOWN` was added in #483 but the correct capability name was `CHOWN`.
- fixes #484
=> [datadog] Fix CAP_CHOWN configuration for system-probe

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Update `agents.podSecurity.capabilities` to contain all `agents.containers.systemProbe.securityContext.capabilities`.
Fix issue reported [here](https://github.com/DataDog/helm-charts/pull/486#issuecomment-997816504)  after that #486 was merged.
- fixes #484, #486 
=> [agent] add CHOWN in PodSecurityPolicy capabilities

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/rbac.yaml, charts/datadog/values.yaml
* Add a new configuration section `datadog.secretBackend`.
* Configuring `datadog.secretBackend.command="/readsecret_multiple_providers.sh"` will add the secret permissions required by the `/readsecret_multiple_providers.sh` helper.
- fixes https://github.com/DataDog/helm-charts/issues/479
=> feat: add secretBackend values

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default Datadog Agent image to `7.32.4`.
=> feat(datadog): default agent image to 7.32.4

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/pod_disruption_budget.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-pdb.yaml, charts/datadog/templates/cluster-agent-pdb.yaml
Update PodDisruptionBudget api version from `policy/v1beta1 `to `policy/v1`, to get rid of the warning message, the v1beta1 is deprecated in v1.21+, unavailable in v1.25+;
- fixes #436
=> Update PodDisruptionBudget api version to get rid of warning message

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/cluster-agent-values.yaml, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml
fix(datadog): environments variables quoted correctly
Fix environment variables to be quoted with a loop and `quote` instead of
`toYaml`.
**Checklist**
=> fix(datadog): environments variables quoted correctly

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/pod_disruption_budget.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-pdb.yaml, charts/datadog/templates/cluster-agent-pdb.yaml
* Fix `PodDisruptionBudget` api version definition when using `helm template`.
* Define an helper that return the proper PodDisruptionBudget api version depending of the
api version availability and the kubernetes api-server version.
when running `helm template` the function `.Capabilities.APIVersions.Has "policy/v1/"` always return true event if it was not
define for a specific kubernetes version (for example v1.19).
=> fix(datadog): PodDisruptionBudget api version with helm template cmd

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-scc.yaml
* Remove unset field in the Cluster-Agent `SecurityContextConstraints` definition. The API-Server validation on openshift 3.x doesn't allow `null` value.
- fixes #499
=> fix(datadog): fix DCA SCC creation on openshift 3

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-scc.yaml, charts/datadog/values.yaml
Update config examples for the mysql integration to match the current values accepted by the integration
Updates the examples of the mysql integration to correspond to the current values. For example replace the server parameter with the current host that is in the integration example. Also removed the "" around the server and password. This will hopefully help avoid customers using these in their setups and having issues.
=> Update example mysql confs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_daemonset-volumes-linux.yaml
Do not declare the volumes for `/etc/*-release` if there is no `system-probe`.
Only the `system-probe` container mounts them.
=> Do not declare the volumes for `/etc/*-release` if there is no `system-probe`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Update cluster-agent's podAntiAffinity from `requiredDuringSchedulingIgnoredDuringExecution` to `preferredDuringSchedulingIgnoredDuringExecution` so that a new cluster-agent pod can be scheduled during a `helm upgrade` in a one node cluster
- fixes #
=> Update cluster-agent's podAntiAffinity from required to preferred

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
This PR addresses the following warning log line from the system probe:
```
datadog-zsqjc system-probe 2022-01-12 21:44:20 UTC | SYS-PROBE | WARN | (pkg/util/log/log.go:630 in func1) | Unknown key in config file: runtime_security_config.debug
```
=> System Probe: Remove unknown config key "runtime_security_config.debug"

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-psp.yaml, charts/datadog/values.yaml
This allows us to use unsafe sysctls as described here: https://docs.datadoghq.com/developers/dogstatsd/high_throughput/\#over-uds-unix-domain-socket
=> Add agents.podSecurity.allowedUnsafeSysctls parameter to datadog chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default Datadog Agent image to `7.33.0`.
* Default Datadog Cluster-Agent image to `1.17.0`.
- fixes #
=> [datadog] Default Agent to 7.33.0, DCA to 1.17.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/values.yaml
Expose [multi-line log detection option](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile#automatic-multi-line-aggregation) in the `values.yaml` of the `datadog` Helm chart.
- fixes #530
=> Add a parameter to setup automatic multi-line log detection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
* Add a new note to recommand to the Cluster Agent in HA mode when the `admission-controller` or the `metrics provider` are enabled.
- fixes #438
=> [datadog] Add note about Cluster-Agent HA recommendation

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml
* Sync operator RBACs from `datadog-operator` repo to add missing `verticalpodautoscalers` RBACs.
* It adds also the RBAC for `ciliumnetworkpolicies` resources. 
When testing the lastest operator binary with `kubernetes_state_core` check enable, the following error is returned by
the API-server to the operator:
```
{"level":"ERROR","ts":"2022-02-09T09:18:31Z","logger":"controller-runtime.manager.controller.datadogagent","msg":"Reconciler error","reconciler group":"datadoghq.com","reconciler kind":"DatadogAgent","name":"datadog","namespace":"default","error":"clusterroles.rbac.authorization.k8s.io \"default-datadog-ksm-core-dca\" is forbidden: user \"system:serviceaccount:default:my-datadog-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:default\" …
```
=> fix(datadog-operator): fix Operator RBACs (for VPA)

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
* Add ingress RBAC rules for the Cluster Agent to collect ingress resources in the Orchestrator Explorer. (Feature available starting Cluster Agent v1.19)
- fixes #
=> feat: add rbacs for ingress resources collection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helm_check_config.yaml, charts/datadog/templates/helm-check-rbac.yaml
Fixes scheduling of Helm check. It's no longer scheduled on a daemonset agent.
=> [datadog] Fix Helm check scheduling

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-cilium-network-policy.yaml, charts/datadog/templates/cluster-agent-cilium-network-policy.yaml
Updates CiliumNetworkPolicy to allow sending Agent Flares. 
Resolves post error when attempting to send flare from an agent running on a cluster that uses Cilium network policies. 
- fixes #555
=> Allow sending Agent Flares in CiliumNetworkPolicy

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
=> Bumping default version of the Datadog Agent to 7.33.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Bumps datadog agent verison to 7.34 and cluster agent version to 1.18.
=> [datadog] Bump agent version to 7.34

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update `synthetics-private-location` to latest `1.20.0` release.
=> [Synthetics] Update `synthetics-private-location` chart to v1.20.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
Use `0.4.7` version of `datadog-crds` chart with fix of `Capabilities.APIVersions` to install CRD into Kubernetes version >=1.22.
=> DATADOG-CHART: Use last version of datadog-crds dependency

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.21.0.
None
=> [synthetics-private-location] bump image version to 1.21.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helm_check_config.yaml, charts/datadog/values.yaml
Adds a new option in the datadog chart to enable event collection in the Helm check.
Needs to be merged after https://github.com/DataDog/datadog-agent/pull/11317
=> [charts/datadog] Add option to collect events in Helm check

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Enforce use of `root` user for the node agent.
This is currently useless and it won’t change anything.
The goal is to be ready for when the agent docker image will have a non-`root` user by default.
The corresponding `datadog-operator` PR is DataDog/datadog-operator#456.
=> Enforce use of `root` user for the node agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl
Fixes the docs for enabling NPM to use the newer `datadog.networkMonitoring.enabled` value.
=> Update README with updated NPM instructions

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_daemonset-volumes-windows.yaml, charts/datadog/values.yaml
=> Add `datadog.kubelet.podLogsPath` to customize hostPath mounted in to get Kubernetes PODs logs.

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update the agent to the latest released version: 7.35.0
=> Bump default agent version to 7.35.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
Add `setitimer` syscall to seccomp profile for `system-probe` to fix Go CPU profiling.
=> Fix Go CPU profiling for system-probe

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update `synthetics-private-location` to latest 1.22.0 release.
=> [Synthetics] Upgrade `synthetics-private-location` chart to v1.22.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
Fixes the ability for system-probe to detect process liveness by allowing the `kill(<pid>, 0)` syscall in the seccomp profile.
=> Allow kill with signal value 0 to detect processes

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_kubernetes_state_core_config.yaml, charts/datadog/templates/kube-state-metrics-core-rbac.yaml, charts/datadog/values.yaml
Add configuration `datadog.kubeStateMetricsCore.collectVpaMetrics` to add the `verticalpodautoscalers` to the list of collectors in the `kubernetes_state_core.yaml.default`  to enable collection. Updated the RBAC to only provision the `ClusterRole` portion for this when enabled. 
VPAs are not enabled by default in most Kubernetes Clusters, and the `verticalpodautoscalers` KSM collector will throw errors when it is active and VPAs are not enabled. So this option is set to `false` by default.
- fixes https://github.com/DataDog/helm-charts/issues/603
Can validate that when enabled the `/etc/datadog-agent/conf.d/kubernetes_state_core.yaml.default` file gets this collector added and the `ClusterRole: datadog-ksm-core` has that corresponding permission.
For full validation can deploy a VPA like …
=> Add option to enable verticalpodautoscalers collection for KSM Core

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/gke-autopilot-values.yaml, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_daemonset-volumes-windows.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/agent-scc.yaml, charts/datadog/templates/checksd-configmap.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/confd-configmap.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/datadog-yaml-configmap.yaml, charts/datadog/templates/helm-check-rbac.yaml, charts/datadog/templates/install_info-configmap.yaml, charts/datadog/templates/rbac.yaml
From this version, on GKE Autopilot, only one "datadog" helm chart release is allow by Kubernetes namespace due to the following new constraints:
* On GKE autopilot, make the "Agent" Daemonset serviceaccountName immutable.
* On GKE autopilot, make the "Install Info" ConfigMap name immutable.
* Improve `Notes.txt` to better document GKE Autopilot limitation, fail the
installation when an unsupported option has been used in the configuration.
=> feat(datadog): hardcode serviceAccount&ConfigMap name on GKE Autopilot

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.23.0.
None
=> [synthetics-private-location] bump image version to 1.23.0

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, charts/datadog-crds/update-crds.sh
The updated `v1beta1` CRDs from https://github.com/DataDog/helm-charts/pull/626 cause issues on clusters using v1.14.x or lower since CRD pruning was not introduced until v1.15.0. Error from the failed build job attempting to install the `datadog-operator` chart on v1.14.10: https://github.com/DataDog/helm-charts/runs/6472542441?check_suite_focus=true
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec`
=> [datadog-crds] Remove `preserveUnknownFields` from v1beta1 crds

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/deployment.yaml, charts/synthetics-private-location/values.yaml
The liveness probe mechanism used by the Synthetics Private Location chart is deprecated. We want to use the HTTP liveness probe instead.
Also, we are adding the HTTP readiness probe, with the possibility to enable/disable both probes using a new value: `enableStatusProbes`.
=> [synthetics] Update liveness and readiness probes in PL chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Fix inaccurate documentation example for `datadog.kubeStateMetricsCore.labelsAsTags`.
- fixes https://github.com/DataDog/helm-charts/issues/632
=> fix: wrong example for ksm core labelsAsTags

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/rbac.yaml, charts/datadog/values.yaml
When we set `datadog.secretBackend.command` to `/readsecret_multiple_providers.sh`, it will add a cluster wide permission to read any secret. This is an anti-pattern that does not follow the principle of least privilege.
This PR will add a new value `datadog.secretBackend.enableGlobalPermissions` with the default set to `true` (non-breaking behaviour), when it is set to `false` it will prevent this cluster wide permission being created.
In its place is a new value `datadog.secretBackend.roles` which have the following structure:
```yaml
datadog:
secretBackend:
enableGlobalPermissions: false
roles:
- namespace: some-namespace
secrets:
- secret-1
- secret-2
- namespace: another-namespace
secrets:
- another-secret-1
```
The chart will then create a `Role` and then a `RoleBinding` for each …
=> [charts/datadog] Allow granular read secret roles

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-services.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
* Introduce `clusterAgent.admissionController.configMode` (requires Cluster Agent `1.20+`). It allows choosing the kind of configuration to be injected ("hostip", "service", or "socket").
- fixes #
Related to https://github.com/DataDog/datadog-agent/pull/11373
=> feat: add admissionController.configMode

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
This allows setting of the necessary variables to allow the operator to use a proxy for outbound connections.
=> Add proxy to operator deploy

.gitignore, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/templates/NOTES.txt, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Updates default values for admission controller failure policy.
- fixes #
This is related to https://github.com/DataDog/datadog-agent/issues/11426
and depends on https://github.com/DataDog/datadog-agent/pull/11432
=> update default values for failure policy

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds an option to enable the File Integrity Monitoring for CWS. FIM enabled is a subset of the "general" enabled option which means that in most cases we want to check for one or the other.
- fixes #
=> CWS: add option to enable FIM

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
* Avoid the error `<eq .Values.clusterAgent.admissionController.configMode "service">: error calling eq: incompatible types for comparison` that can happen in older helm versions.
- fixes https://github.com/DataDog/helm-charts/issues/649
=> fix: error calling eq: incompatible types for comparison for configMode

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.24.0.
=> [synthetics] Bump PL image version to 1.24.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/cluster-agent-admission-controller.yaml, charts/datadog/values.yaml
* The Admission Controller is now enabled by default. (the mutation stays opt-in via mutateUnlabelled or pod label `admission.datadoghq.com/enabled="true"`)
- fixes #
=> feat: enable the admission controller by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_kubernetes_state_core_config.yaml, charts/datadog/templates/kube-state-metrics-core-rbac.yaml
* Update RBACs and the default check configuration to collect ingress metrics in Kube State Metrics Core.
Note: Ingress metrics collection requires Cluster Agent 1.21+.
Related to https://github.com/DataDog/datadog-agent/pull/12344
- fixes #
=> feat(ksm core): prepare rbacs and config for ingress metrics

.github/helm-docs.sh
The existing script doesn't function properly for Apple M1 Macs.
Use `uname -m` to get the arch, rather than hard-coding to x86_64.
This also requires updating to a later version of helm-docs, so update from 1.5.0 to 1.10.0
Use double quotes around the entire string with interpolated variables, vs. individual variables themselves.
**Note** This does generate some changes to the generated docs. I did not update the docs in this PR, though I can if preferred.
Most of the changes are things like this
```
| providers.gke.autopilot | bool | `false` | Enables Datadog Agent deployment on GKE Autopilot |
-| registry | string | `"gcr.io/datadoghq"` | Registry to use for all Agent images (default gcr.io) |
+| registry | string | `"gcr.io/datadoghq"` | Registry to use for all Agent images (default …
```
=> chore: update helm-docs version and support M1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-cilium-network-policy.yaml, charts/datadog/templates/cluster-agent-network-policy.yaml
Allow cross cluster-agent communication in DCA `NetworkPolicy` and `CiliumNetworkPolicy`.
This is needed to allow “follower” cluster agents to forward queries to the “leader” one.
This new behaviour was introduced in cluster-agent `1.21` by DataDog/datadog-agent#11864.
=> Allow cross cluster-agent communication in DCA `NetworkPolicy` and `CiliumNetworkPolicy`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml
Fixes an `include` in the agent-clusterchecks-deployment template of the datadog chart.
=> [datadog] Fix include in agent-clusterchecks-deployment tmpl

.github/CODEOWNERS
Removes `container-integrations` from the code owners of `synthetics-private-location`.
=> Remove `container-integrations` from the code owners of `synthetics-private-location`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update
* Default Datadog Agent image to `7.37.1`
* Default Datadog Cluster Agent image to `1.21.0`
=> Bump default agent to `7.37.1` and default cluster agent to `1.21.0`

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.25.0.
=> [synthetics] Bump PL image version to 1.25.0

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, charts/datadog-crds/update-crds.sh, crds/datadoghq.com_datadogagents.yaml
The `.Capabilities.APIVersions` does not expose `CustomResourceDefinition` in GKE so the process of publishing the operator is not working.
Make sure we publish the operator to the Google Marketplace.
=> Updating condition to deploy v1 or v1beta1 of CRD to work with Google marketplace

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_helpers.tpl
Starting from agent 7.36, we should use `--cfgpath` instead of `--config` (Ref: https://github.com/DataDog/datadog-agent/pull/11328).
Also, we were using `-config` instead of `--config`. `-config` was deprecated in 7.31. (Ref: https://github.com/DataDog/datadog-agent/pull/8964)
=> [datadog] Fix usage of deprecated command flags in the process-agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
Usefull when we have a policies manager as Kyverno.
Signed-off-by: Flaagada <mary.thibault2@gmail.com>
When we used a policies manager as Kyverno, it's usefull to be able to add a common labels on all resources created by the chart in order to respect the policy.
=> Add: support common labels for all resources

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, charts/datadog-crds/update-crds.sh
- fixes https://github.com/DataDog/helm-charts/issues/689
=> Fix semver comparison to use v1beta1 in 1.21

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_helpers.tpl
Using the regexMatch with works with helm2 instead of the mustRegexMatch.
doc: https://helm.sh/docs/chart_template_guide/function_list/#regexmatch-mustregexmatch
Making sure this still works:
```
➜  datadog git:(charly/fix-helm2-breaking-option) ✗ helm3 template --set datadog.otlp.receiver.protocols.grpc.enabled=true  --set datadog.otlp.receiver.protocols.grpc.endpoint="0.0.0.0:a"  .
Error: execution error at (datadog/templates/daemonset.yaml:109:12): port must be set explicitly on OTLP endpoints
Use --debug flag to render out invalid YAML
➜  datadog git:(charly/fix-helm2-breaking-option) ✗ helm2 template --set datadog.otlp.receiver.protocols.grpc.enabled=true  --set datadog.otlp.receiver.protocols.grpc.endpoint="0.0.0.0:a"  .
Error: render error in "datadog/templates/daemonset.yaml": …
```
=> Use backward compatible method to support helm2

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update `synthetics-private-location` Chart with new release `1.26.0`.
=> [Synthetics] Release Chart `0.14.4` with latest Private Location version

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Fix GKE Autopilot installation. The `process-agent` command must
use the `-config` argument to be compliant with the Datadog Agent's
GKE Autopilot security profile.
- fixes #549
=> fix(datadog): gke-autopilot process-agent compatibility

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/NOTES.txt, charts/synthetics-private-location/templates/deployment.yaml, charts/synthetics-private-location/templates/secret.yaml, charts/synthetics-private-location/values.yaml
This allows providing a custom configuration for the config volume mount via `extraVolumes` if neither `configFile`, `configConfigMap` or `configSecret` are supplied. This is useful if for example you are using the [CSI secrets driver](https://secrets-store-csi-driver.sigs.k8s.io/getting-started/usage.html).
Example usage:
```yaml
extraVolumes:
- name: worker-config
csi:
driver: secrets-store.csi.k8s.io
readOnly: true
volumeAttributes:
secretProviderClass: my-secret-provider
extraVolumeMounts:
- name: worker-config
mountPath: /etc/datadog
readOnly: true
```
=> [synthetics-private-location] allow custom configuration of the worker-config volume

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml
Adds the value of `datadog.clusterName` to the cluster check runner pods. Fixes an issue where KSMCore check being run by CCR pods are not reporting properly because they have a separate cluster name than the node agent/cluster agent
- fixes #
=> Add datatdog.clusterName on clusterCheckRunner pods

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
Adds `/etc/dnf/vars` and `/etc/yum/vars` to the default package management directories mounted to `/host/etc` for kernel header downloading. 
This is necessary for kernel header downloading to be able to resolve variables in `yum` and `dnf` repo files.
Users can prevent these folders from being mounted unnecessarily by setting `systemProbe.mountPackageManagementDirs` to only the directories required for their system.
- fixes #
=> Mount yum & dnf vars to /host/etc

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Defaults Datadog Agent image to `7.38.0`.
* Defaults Datadog Cluster Agent image to `1.22.0`.
=> [datadog] Update agent to 7.38.0 and DCA to 1.22.0

.github/kubeval.sh, .github/workflows/ci.yaml
Despite the note about checking for available schemas, many of the schemas being tested about do not exist at
https://kubernetesjsonschema.dev/, which is no longer updated; this could result in a false sense of confidence (because of `--ignore-missing-schemas`, I believe this will fail soft)
Update to later 1.18.x and 1.22.x variants in the matrix, add 1.24.x, and switch to the schemas at https://github.com/yannh/kubernetes-json-schema (used by `kubeconform`).
While this may seem a little strange, I haven't found a more updated / stable source to use thus far.
=> ci: update schema location for chart validation

.github/workflows/ci.yaml, charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, charts/datadog-crds/update-crds.sh, crds/datadoghq.com_datadogagents.yaml
By comparing the minor version with the semverCompare the function would fail in certain cases (e.g. 1.22+).
This should fix it.
We can't rely on `.Capabilities.KubeVersion.Version` because it's not supported with helm2, so I went with `GitVersion`.
```
testGitVersion: '{{ semverCompare ">1.21-0" .Capabilities.KubeVersion.GitVersion }}'
gitversion: '{{ .Capabilities.KubeVersion.GitVersion }}'
```
yields:
```
testGitVersion: "true"
gitversion: v1.23.8-gke.400
```
with helm2 and helm3.
Which should cover the `+` case in the versionning:
```
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8-gke.400", GitCommit:"efbcd8d250c89b4290356c0fc27843d583c80a35", GitTreeState:"clean", BuildDate:"2022-06-24T09:25:13Z", GoVersion:"go1.17.10b7", Compiler:"gc", …
```
=> Fixing corner case for semver

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default Datadog Agent image to `7.38.1`.
- fixes #
=> Default to agent 7.38.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/system-probe-configmap.yaml
set traced_cgroups_count default value to 0 which reduces the performance impact
- fixes #
=> set traced_cgroups_count default value to 0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md
It looks like the fix for the following wasn't added to the operator helm chart:
* https://github.com/DataDog/datadog-operator/issues/565
* https://github.com/DataDog/helm-charts/issues/689
This changes the `datadog-crds` dependency version and the version of the chart itself.
The noted fixes are not reflected in the datadog-operator chart yet because its version hasn't been updated.
* https://github.com/DataDog/datadog-operator/issues/565
* https://github.com/DataDog/helm-charts/issues/689
=> Update Chart.yaml to fix Semver in Operator

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-host-release-volumemounts.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/values.yaml
Change the osReleasePath parameter to datadog.osReleasePath to mount proper files into every container.
- fixes #
=> Mount host release files for proper host OS detection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
Solves an `Operation not permitted` error which can occur during kernel header downloading (libdnf may make a call to `chmod`: [source](https://github.com/rpm-software-management/libdnf/blob/b4c72e83c277e5a6b529606a75fb28d26379825f/libdnf/hy-iutil.cpp#L412)) 
- fixes #
=> Add chmod to allowed actions in seccomp profile

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-host-release-volumemounts.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml
Fix Windows nodes deployment: do not mount `container-host-release-volumemounts`
if the `targetSystem` is "Windows".
changes:
* move the `include container-host-release-volumemounts` to the `if linux` section.
* rename `container-host-release-volumemounts` to `linux-container-host-release-volumemounts` to be sure that people understand it can only be use on a linux system
- fixes #729
this PR doesn't fix the issue reported in this comment: https://github.com/DataDog/helm-charts/pull/717#issuecomment-1228231227. A second PR will come later
=> [datadog] Fix windows nodes deployment

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/values.yaml
* Fix: avoid volumeMount duplication in `system-probe`
container if `datadog.osReleasePath` value correspond
to one of the default os-release-paths mounted
automatically.
* Feat: add the possibility to disable the default
os-release path mount linked to `system-probe`
container with the option: `datadog.systemProbe.enableDefaultOsReleasePaths:false`
- fixes https://github.com/DataDog/helm-charts/pull/717#issuecomment-1228231227
=> [datadog] avoid volumemount conflict in system probe

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Release Synthetics Private Location 0.15.1 chart with update `1.27.0` image.
=> [Synthetics] Release 0.15.1 chart with PL v1.27.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/values.yaml
Adds the `datadog.systemProbe.enableDefaultKernelHeadersPaths` option that allows to choose whether to mount the default kernel headers paths. It defaults to true.
The reason is that in some environments like container OS, some of those paths do not exist. So, in order to make the OOMKill and the TCP queue length checks work, we need to disable the new option.
=> [datadog] Add `datadog.systemProbe.enableDefaultKernelHeadersPaths`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
New versions of runc may call the faccessat2 syscall. If this syscall is not allowed the system-probe container will fail to start with the following error:
"start container process: exec /opt/datadog-agent/embedded/bin/system-probe: operation not permitted: unknown"
Additional context:
https://github.com/opencontainers/runc/commit/d83a861d950b42b53406424468f8644551fa8980
https://github.com/bottlerocket-os/bottlerocket/issues/2394
=> Add faccessat2 syscall to system-probe-configmap

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-host-release-volumemounts.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
This is blocking a few customers - I believe it might be tied to https://github.com/DataDog/helm-charts/issues/549
We can revisit the logic around mounting the os-release file soon.
=> Fix os-release mount in GKE autopilot

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
* Default Agent image to `7.39.0`.
* Default Cluster-Agent image to `7.39.0`. Cluster-Agent versioning is now aligned with the Agent.
=> [agent] Update Agent&DCA version to 7.39.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Sets `enableKernelHeaderDownload` to `true` by default. We had set it to `false` by default due to memory issues related to kernel header downloading; those issues have now been fixed, and we want kernel header downloading to occur by default when runtime compilation is enabled.
- fixes #
=> Set default value for enableKernelHeaderDownload to true

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helm_check_config.yaml, charts/datadog/values.yaml
Adds the `datadog.helmCheck.values` option to collect helm values and use them as tags.
This is a new agent feature added in https://github.com/DataDog/datadog-agent/pull/13451
This should be merged after the first 7.40 release candidate.
=> [datadog] Add `datadog.helmCheck.valuesAsTags` option

examples/datadog/agent_on_aks_values.yaml
Adding `tlsVerify` set to false due to incompatibility with AKS certs and Agent's Golang version as of 7.35+. Lines up with https://docs.datadoghq.com/containers/kubernetes/distributions/?tab=helm#AKS
* Fixes issue with AKS certs starting from Agent `7.35+`
* Lines up with our AKS doc : https://docs.datadoghq.com/containers/kubernetes/distributions/?tab=helm#AKS
=> Sets `datadog.kubelet.tlsVerify` to false by default in AKS

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default "Agent" and "Cluster-Agent" image tag to `7.39.1`.
This change is need to have by default the Agent and Cluster-Agent image with the latest bug and security fixes.
N/A
=> [datadog] Update Agent tag to 7.39.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/daemonset.yaml
Uses the preferred `securityContext.seccompProfile` instead of the annotations for kubernetes v1.19+
=> Use seccompProfile under securityContext in k8s 1.19+ for system-probe

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/daemonset.yaml
Ensures we always pass a version to the `generate-security-context` helper
Fixes #771
=> Fix usages of generate-security-context

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Release Synthetics Private Location 0.15.2 chart with update 1.28.0 image.
=> [Synthetics] Release 0.15.2 chart with PL v1.28.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Fix the new way of specifying the `system-probe` seccomp profile on Kube 1.19+ introduced in #768.
Fix the `system-probe` container remaining in `CreateContainerError` state forever because of the following error:
```
Warning  Failed     11m                 kubelet            Error: failed to create containerd container: cannot load seccomp profile "/var/lib/kubelet/seccomp/localhost/system-probe": open /var/lib/kubelet/seccomp/localhost/system-probe: no such file or directory
```
This is because the profile was copied in `/var/lib/kubelet/seccomp/system-probe`, without the `/localhost/` subdirectory.
=> Fix the configuration of the default seccomp profile for system-probe

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Defaults Agent and DCA images to 7.39.2.
=> [datadog] Update agent and DCA to 7.39.2

charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/_helpers.tpl
Usefull when we have a policies manager as Kyverno.
Signed-off-by: Flaagada <mary.thibault2@gmail.com>
When we used a policies manager as Kyverno, it's usefull to be able to add a common labels in all resources created by the chart in order to respect the policy. In this [PR](https://github.com/DataDog/helm-charts/pull/785), it missing commonLabels on ressources (RS + Pods) from deployment.
=> Add: support common labels for resources from Kuberntes deployment

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md
Default to use the latest Datadog Operator image, 0.8.2
=> [datadog-operator] bump latest image version to 0.8.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/agent-services.yaml, charts/datadog/values.yaml
In certain environments users can't enable the use of the Host Ports for the Agent container's OTLP Ingest feature. The Host Port syntax is the original and default strategy for sending data to the Agent as this allows application pods to send data from a given pod to the Host IP, which routes to the Host Port, which routes to the Agent pod on the **same node**. Which we want for tagging purposes.
However, with Kubernetes 1.22+ we can use the Agent `Service` to route traffic to the Agent pod on the same node with `internalTrafficPolicy: Local`. 
This PR adds the ability to allow you to keep the gRPC or HTTP endpoints enabled, but without the host port. For compatibility the host port is on by default. This uses the similar syntax as dogstatsd, `...grpc.useHostPort` and …
=> Add option to toggle Host Ports of OTLP Ingest, add use of Agent Service

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Release Synthetics Private Location 0.15.6 chart with update 1.29.0 image.
=> [synthetics] update private location to version 1.29.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default "Agent" and "Cluster-Agent" image tag to `7.40.0`.
=> [datadog] Update agent and DCA to 7.40.0

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/values.yaml
PR in the CRDs before PR in the operator to support using DDA in v2alpha1 directly.
- fixes #
=> Adding option to store v2alpha1 version of the DatadogAgent

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
- Following up on https://github.com/DataDog/helm-charts/pull/798
- Add reference to updated CRD that allows storing/serving v2alpha1
- Add ability to deactivate Conversion Webhook and add safeguard not to use for versions of the Operator that don't support it.
- fixes #
=> Update datadog operator chart v2alpha1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Defaults Agent and DCA images to 7.40.1.
=> [datadog] Update agent and DCA to 7.40.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl, charts/datadog/templates/agent-psp.yaml, charts/datadog/templates/agent-scc.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
useHostPID is being moved under the datadog namespace from under the datadog.dogstatsd namespace.
This change is happening since the host pid namespace is no longer used just for origin detection in dogstatsd. The Trace Agent also now relies on being in the host's pid namespace for origin detection to work under cgroup v2.
This commit deprecates the old datadog.dogstatsd.useHostPID value and adds a new one named datadog.useHostPID. This variable is then used in the templates everywhere where dogstatsd.useHostPID is.
=> charts/datadog: move datadog.dogstatsd.useHostPID under datadog.

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md
Follow up of  https://github.com/DataDog/helm-charts/pull/805
Bumping dependency to the DatadogAgent crd in the Datadog Operator chart.
=> Updating dependency on CRD Chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml
Removes `mountPropagation` from individual files in `/etc` that are mounted for kernel header downloading. `mountPropagation` is not needed and may be causing problems.
- fixes #
=> Remove mountPropagation from release files in /etc

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-psp.yaml, charts/datadog/templates/agent-scc.yaml, charts/datadog/templates/daemonset.yaml
Add fixes relative to changes made in:
3.2.2 - Add new mounts to the `trace-agent` by default
- https://github.com/DataDog/helm-charts/pull/803
3.3.0 - Move to `datadog.hostPID` and enable by default
- https://github.com/DataDog/helm-charts/pull/790
As these were preventing the Agent from being deployed on GKE Autopilot. 
- fixes #
=> Fixes for GKE Autopilot mountPoints and hostPid settings

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/values.yaml
Certain combinations of `clusterChecksRunner.enabled` and `kubeStateMetricsCore.useClusterCheckRunners` settings may lead to poor utilization of Cluster Checks Runner and overloading of DCA or Node Agents. Change adds documentation to the helm chart and and a warning about config leading to such issues.
* Addresses CONTECO-286
=> [datadog] Comment clarifying relationship between clusterChecksRunner and useClusterCheckRunners configurations and corresponding Helm warning note.

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml
We had not updated the CRD following up on the update to store v2alpha1 https://github.com/DataDog/helm-charts/pull/798
- fixes https://github.com/DataDog/datadog-operator/issues/649
=> Fix the DatadogAgent CRD for clusters < 1.21

.github/workflows/ci.yaml
downgrading to ubuntu-20.04 allow us to keep supporting k8s 1.18.x in the CI. 
The issue is that in 22.04 cgroupv2 is enabled by default.
Fix the CI when PR are validated on kubernetes 1.18.x.
you can check this CI action https://github.com/DataDog/helm-charts/actions/runs/3585666025 to see that it worked with a fake `datadog` chart update.
=> Downgrade Ubuntu to 20.04 to keep k8s 1.18 support in the CI

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
Add `datadog.systemProbe.btfPath` for mounting user-provided BTF files for Compile Once Run Everywhere (CO-RE) (see [#13962](https://github.com/DataDog/datadog-agent/pull/13962) and [#14096](https://github.com/DataDog/datadog-agent/pull/14096) for more context).
=> Add configuration value for mounting custom BTFs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
Removes `enableKernelHeaderDownload` and `enableRuntimeCompiler` from the helm chart values. These settings should instead be configured via the `DD_ENABLE_KERNEL_HEADER_DOWNLOAD` and `DD_ENABLE_RUNTIME_COMPILER` environment variables.
Runtime compilation and kernel header downloading are being slowly released to customers. At the current stage of this release, we want these features to be turned off by default for all customers except USM customers. This is achieved by having the system-probe turn on runtime compilation & kernel header downloading when customers have USM enabled, but **only if they haven't explicitly configured these features themselves** (that is, only if these configuration values are not set - see [here](https://github.com/DataDog/datadog-agent/blob/6a3d555a334cfd2dacd …
=> Remove runtime compilation helm config options

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
apiKey value is getting defaulted to <DATADOG_API_TOKEN> as its value.
apiKey value is coming in as <DATADOG_API_KEY>, because it is not commented and helm thinks its an actual value. Check my issue https://github.com/DataDog/helm-charts/issues/827
- fixes # https://github.com/DataDog/helm-charts/issues/827
the value should be commented. Seems to be typo.
=> Comment Value for apiKey

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogmonitors.yaml
Using the Datadog Operator 0.8.4 (and 1.0.0-rc.4) supports `newGroupDelay`  (`newHostDelay` is deprecated), this updates the CRDs to reflect this.
TODO: Update the dependency in the Datadog Operator chart on the minimum image installed.
- fixes #
=> Updating DatadogAgent and DatadogMonitor CRDs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/agent-psp.yaml, charts/datadog/templates/cluster-agent-psp.yaml
* Fix API Key check in NOTES.txt following change of default value for `datadog.apiKey`.
* Fix failure if PSP activated in Kubernetes 1.25 (PSP have been removed).
Fixes #832 
=> Fix API Key check following change of default value (+ fix CI)

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Update default agent version to `7.41.0` in the `datadog` chart.
* Update default cluster-agent version to `7.41.0` in the `datadog` chart.
- fixes #
=> feat(datadog): update default agent version to 7.41.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_kubernetes_state_core_config.yaml, charts/datadog/values.yaml
Add `datadog.kubeStateMetricsCore.annotationsAsTags` that expose the `annotations_as_tags`
parameter of the KSM core check.
This parameter exists only in agent 7.42.0 and above and cluster-agent 7.42.0 and above.
- fixes #
=> feat(datadog): add ksm-core annotationsAsTags option

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
This PR fixes the nesting in the `env` section so that `providers.aks.enabled` works as initially intended with PR #842
Fixes #851
=> fix: update nesting for `provider.aks.enabled`

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
This PR updates the Synthetics Private Location helm-chart to use the latest version of the PL.
- fixes #
This PR will be merge after the docker tag for the PL 1.31.0 will be pushed
=> [synthetics] update private location to version 1.31.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml
Fix missing Cluster Agent configuration in `security-agent` if CSPM is not actived
Fixes #720 
=> Fix missing Cluster Agent configuration in `security-agent` if CSPM is not actived

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml
* Fix missing volumeMount in `security-agent` container when `datadog.kubelet.hostCAPath` is provided.
Because the `workload-metadata-store` component is used in the `security-agent` container, this container requires to use mount the host CA certificat to communicate with the kubelet.
=> fix(datadog): fix security-agent config with hostCAPath option

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` image tags to `7.41.1`.
- fixes #
=> feat(datadog): default agent version to 7.41.1

charts/datadog-operator/templates/clusterrole.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
This adds missing RBAC rules for the collection of Vertical Pod Autoscalers
- fixes #
=> Add RBAC rules for Vertical Pod Autoscalers

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/daemonset.yaml
This aims to fix auth_token not available from system-probe which avoid using remote-config and the remote-tagger.
- fixes #
=> add auth_token support

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/cluster-agent-values.yaml, charts/datadog/templates/_components-common-env.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/_kubernetes_apiserver_config.yaml, charts/datadog/templates/cluster-agent-confd-configmap.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
*  Create `components-common-env` to define shared environment variable between "agent" and "cluster-agent" containers, and refactor `containers-common-env`.
* Add `datadog.kubernetesEvents.*` options to configure new Kubernetes unbundling events feature.
(This parameter exists only in agent 7.42.0 and above and cluster-agent 7.42.0 and above.)
* Add `datadog.clusterTagger.*` options to configure the Kubernetes cluster-tagger feature.
(This parameter exists only in agent 7.42.0 and above and cluster-agent 7.42.0 and above.)
- fixes #
=> feat(datadog): add k8s unbundle events feature support

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update the Private Location chart to 0.15.7 with new release 1.31.1.
=> [Synthetics] Private Location Chart: Bump to 0.15.7 with release 1.31.1

.github/CODEOWNERS
Replace @DataDog/containter-integration and @DataDog/container-ecosystems by @DataDog/container-helm-chart-maintainers in CODEOWNERS file to simplify code-reviews.
- fixes #
=> introduce container-helm-chart-maintainers in codeowners

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/secret-with-dynamic-annotations-values.yaml, charts/datadog/templates/secret-api-key.yaml, charts/datadog/templates/secret-application-key.yaml, charts/datadog/templates/secret-cluster-agent-token.yaml, charts/datadog/values.yaml
This PR adds support for annotations on kubernetes Secrets deployed by the datadog helm chart
- fixes #882 
N/A
=> feat(datadog):  Secret annotations support

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR enables the process-discovery check in the process agent by default when using helm. Initally this setting was turned off by default because the minimum helm version was less than the version that the setting was introduced in. Now that the minimum version is 7.34, we can safely enable this setting by default.
- fixes #
Original PR: https://github.com/DataDog/datadog-agent/pull/9082
=> [process-agent][helm-chart] Enable process discovery check by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` image tags to `7.42.0`.
=> [datadog] Update agent and DCA to 7.42.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Add missing capability `DAC_READ_SEARCH` in the psp agent. It prevented the creation of agent pods when PSPs are activated in the cluster.
- fixes #881
=> [datadog] Fix missing agent PSP capability (#881)

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update the Private Location chart to 0.15.8 with new release 1.32.0.
=> [Synthetics] Private Location Chart: Bump to 0.15.8 with release 1.32.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/_helpers.tpl
Fix default `hostPid` value set to true on Windows.
Fix auth token path value on Windows.
- fixes #
=> Fix auth token path and default hostPid=true on Windows

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Fixes https://github.com/DataDog/helm-charts/issues/858
=> [datadog] Fix docs for `agents.containers.{traceAgent,securityAgent}.env`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` image tags to `7.42.1`.
=> [datadog] Update agent and DCA to 7.42.1

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update the Private Location chart to 0.15.10 with new release 1.33.0.
=> [synthetics] Bump to 0.15.10 with PL release 1.33.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-scc.yaml
the `users` field was duplicated in the cluster-agent scc.
- fixes #907
=> fix(datadog): fix cluster-agent scc

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default `Agent` and `Cluster-Agent` image tags to `7.42.2`.
=> [datadog] Update agent and DCA to 7.42.2

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/ci/dupe-ports-values.yaml, charts/observability-pipelines-worker/ci/serviceHeadless-disabled.yaml, charts/observability-pipelines-worker/ci/templated-config-values.yaml, charts/observability-pipelines-worker/templates/_pod.tpl, charts/observability-pipelines-worker/values.yaml
~~The original PR intending to GA the chart and application missed the `image.tag` value, this wasn't a _huge_ deal as the `1.0.0` was a retag of the old `0.1.0` so by happy accident nothing was broken for users.
I've updated the release documentation to include this change as well, but also considering removing the number of places this needs to be updated to avoid future mistakes.~~
Repurposing for the upcoming release, given the we're moving past the `1.0` quickly. I also removed the extra places that needed version bumps to streamline releases.
- closes [OPB-806](https://datadoghq.atlassian.net/browse/OPB-608)
~~The image was incorrectly published as `v1.0.0`, this PR can't merge until the correct image has been released.~~
Awaiting the upcoming `1.1.1` release for OPW.
=> [observability pipelines worker] 1.1.1 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` image tags to `7.43.0`.
=> [datadog] Update agent and DCA to 7.43.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/agent-clusterchecks-rbac.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/rbac.yaml, charts/datadog/values.yaml
Add `automountServiceAccountToken` to the agent, cluster-agent and clustercheck runner chart templates. By default, the option is set to True. This new option allows users to configure whether the created RBAC ServiceAccount token should be mounted.
- fixes #
=> Add automountServiceAccountToken option

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
- Expose apm onboarding + RC config in values.yaml
- Add required patch permissions in the cluster agent
- fixes #
The goal is to allow beta testers to use the helm chart
=> apm onboarding beta: support remote instrumentation

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Make the root filesystem of the `cluster-agent` read-only by default.
It is still possible to override this setting to restore the previous behavior.
Some volumes that need to be writable for the `cluster-agent` to work properly are defined in the `Dockerfile` rather than in the kubernetes manifests. See https://github.com/DataDog/datadog-agent/blob/055d626c2415fa37ffb9968b6208eef52a3a8338/Dockerfiles/cluster-agent/Dockerfile#L91-L92
We cannot safely do the same by default for the node agent because there can be arbitrary (custom) python checks that might need write access.
=> Set `readOnlyRootFilesystem: true` on the cluster-agent container

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Enable remote configuration if `clusterAgent.admissionController.remoteInstrumentation` is enabled.
Less friction, better UX
- fixes #
=> Enable remote config if `remoteInstrumentation` is enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
* Add new EmptyDir in Cluster-Agent deployment to allow creation of log file in `/var/log/datadog` even when the container is using read-only root filesystem (since v3.14.0 helm chart)
* Add missing entry in the CHANGELOG for 3.16.0 datadog chart version.
- fixes #937
the change in 3.14.0 was tested on Kubernetes with containerd, and it was working, thanks to the fact that the `/var/log/datadog` folder is listed as a VOLUME  in the Dockerfile. So it seems that containerd set this folder a read/write even if the container is configured with root-only filesystem in the Pod spec.
Openshift (and so maybe CRIO) seems to not have the same behaviour. 
=> fix(datadog): allow DCA to write logs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Mount an `emptyDir` volume at `/opt/datadog-agent/run` in the cluster-agent container to allow it to write files there even when running with a read-only root filesystem.
```
2023-03-08 14:16:58 UTC | CLUSTER | ERROR | (comp/core/log/logger.go:84 in Errorf) | Failed to start remote-configuration: unable to create remote-config service: failed to create rc db dir: (/opt/datadog-agent/run/remote-config.db): mkdir /opt/datadog-agent/run: read-only file system
```
=> [datadog] Make `/opt/datadog-agent/run` writable by the cluster agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-cilium-network-policy.yaml, charts/datadog/templates/kube-state-metrics-cilium-network-policy.yaml
This PR focus to update cilium egress rules to Kubernetes API server.
#927 
=> Update Cilium Egress rule to kube-apiserver

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update datadog `agent` and `cluster-agent` default version to `7.43.1`.
See https://github.com/DataDog/datadog-agent/releases/tag/7.43.1
=> [datadog] Update agent and DCA to 7.43.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-cri-volumemounts.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-init-linux.yaml, charts/datadog/templates/_containers-init-windows.yaml, charts/datadog/templates/_system-probe-init.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml
Add `readOnly` option to all mounted volumes to improve security of the datadog-agent installation. Makes sure volumes are `readOnly: true` where possible and exceptions are noted with a reason. 
- fixes #
=> Update volumeMounts with `readOnly` fields

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-init-linux.yaml, charts/datadog/templates/cluster-agent-deployment.yaml
Explicitly mount `emptyDir` volumes in `/etc/datadog-agent` and `/tmp` in the `cluster-agent` container to allow it to write to those locations even with a read-only root filesystem (see #934).
This is a follow-up of #938 and #940.
- fixes #937
The issue this PR is fixing seems to be specific to OpenShift / `cri-o`.
On other Kubernetes distributions with `containerd`, there were already writable volumes mounted at those locations thanks to a `VOLUME` statement in the `cluster-agent` `Dockerfile`: https://github.com/DataDog/datadog-agent/blob/14b9337b0ad7ccb583249e5d13e63932e5b51113/Dockerfiles/cluster-agent/Dockerfile#L91-L92 .
=> [datadog] make `/etc/datadog-agent` and `/tmp` writable by the cluster-agent.

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-init-windows.yaml
Make the `emptyDir` `config` volume [read-write in the `init-volume` init container on Windows](https://github.com/DataDog/helm-charts/pull/932/files#diff-cd8b7548c45e0257b7d9852440a7e1683c31795f1c9603f32cb83d8553f5a4c9R13) like [it already is on Linux](https://github.com/DataDog/helm-charts/pull/932/files#diff-2d5d99450009939b13edaea8bc6c04ed07dbdcb45f59247bc27b3fc63e6593f5R11).
- fixes https://github.com/DataDog/helm-charts/pull/932#issuecomment-1466252978
=> [datadog] Fix R/W volume mounts in init containers on Windows

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR enables CWS network detections by default, matching the default value of the agent config.
The config is used in https://github.com/DataDog/helm-charts/blob/e72d103839332be084ca4e2af577162018cb7e2b/charts/datadog/templates/system-probe-configmap.yaml#L55 pointing to the agent config defined in https://github.com/DataDog/datadog-agent/blob/94e6571a6a950c07828e6cf28ff2138a166ba0ec/pkg/config/system_probe.go#L271
- fixes #
=> [SEC-7719][CWS] enable cws network by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-init-linux.yaml
This PR reverts the `args` change introduced in https://github.com/DataDog/helm-charts/pull/943/files#diff-2d5d99450009939b13edaea8bc6c04ed07dbdcb45f59247bc27b3fc63e6593f5R24-R27. This change is breaking deployments in GKE Autopilot and I think it's because the GKE Warden expects the exact command arg as written in the `allowlistedworkload` exemption. See https://github.com/DataDog/helm-charts/issues/947. 
https://github.com/DataDog/helm-charts/issues/947
=> Fix linux init container command args

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-cri-volumemounts.yaml
Remove the `readOnly: true` option on the CRI named-pipe volume mounts on Windows because it causes the following error:
```
Error: Error response from daemon: invalid volume specification: '\\.\pipe\docker_engine:\\.\pipe\docker_engine:ro': invalid mount config for type "npipe": field ReadOnly must not be specified
```
This was a regression introduced by https://github.com/DataDog/helm-charts/pull/932/files#diff-7adecba9235479e1b29b031bdb0c4cd8c07c69c8f7252e0df99c00562c257b81
- fixes #955
=> [datadog] Fix R/W volume mounts for CRI on Windows

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_containers-init-linux.yaml
Fixes to allow Datadog Agent deployment in GKE Autopilot on the rapid release channel:
* Only mount dogstatsd socketpath in non-autopilot environments
* Fix init container script to match the expected script in the GKE Autopilot AllowlistedWorkload resource
- fixes #
=> Fix dogstatsd socketpath mount and container script for gke autopilot rapid release channel

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds a parameter to enable the remote configuration service of the agent.
- fixes #
=> add a parameter to enable remote configuration

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml
Add missing `nodeLabelsAsTags` and `namespaceLabelsAsTags` to v2alpha1 spec. 
- fixes #
=> Add nodeLabelsAsTags and namespaceLabelsAsTags to v2alpha1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/dca-helm-values-rbac.yaml, charts/datadog/values.yaml
* Injects some env variables in the DCA to determine : 
* The Helm release name
* The generated Daemonset name of the node Agent
* The generated Deployment name of the cluster Agent
* Adds new parameter `clusterAgent.rbac.flareAdditionalPermissions` parameter to enable user Helm values retrieval in DCA flare (`true` by default)
https://datadoghq.atlassian.net/browse/CONT-3734 / https://github.com/DataDog/datadog-agent/pull/16229
* These env vars are used to retrieve the necessary resources from the API server to add to the DCA flare user configuration, as well as manifests of the node Agent/cluster Agent.
* The additional RBACs are necessary to retrieve Helm user values from cluster Agent namespace if the Helm check and admission controllers are not enabled.
=> [DCA][Flare] Additional environment variables and RBAC to permit user manifests retrieval

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Move `kube-state-metrics` default image registry from k8s.gcr.io to registry.k8s.io.
- fixes #967
According to the [announcement](https://kubernetes.io/blog/2023/03/10/image-registry-redirect/) k8s.gcr.io will be redirected to registry.k8s.io and then later sunset.
I tested that the image tag exist in this registry too.
=> feat(datadog): use registry.k8s.io for ksm image

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This feature will be enabled by default in agent version 7.44. But can already be enabled with older agent version. This feature is only active is CWS itself is enabled, and will be no-op if not.
- fixes #
=> CWS: enable security profiles collection by default

charts/datadog/CHANGELOG.md
The changelog entry of https://github.com/DataDog/helm-charts/pull/974 was not clear enough. This PR fixes this using https://github.com/DataDog/helm-charts/pull/974#discussion_r1152831351 feedback.
This PR specifically does not bump the version.
- fixes #
=> [CWS] improve clarity of changelog entry for 3.25.0 release

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/NOTES.txt, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
PR adds two new configurations to Operator chart to control `maximumGoroutines` used in Operator health checks and `datadogAgentEnabled` to control whether Operator runs `DatadogAgent` reconciler (e.g. in case users only needs `DatadogMonitor`).
- fixes # https://github.com/DataDog/datadog-operator/issues/666, https://github.com/DataDog/datadog-operator/issues/721
=> Operator configuration for maximumGoroutines and datadogAgentEnabled parameters

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/values.yaml
- Change the default of the stored version in the CRDs chart.
Once merged I will update the dependency in the datadog-operator chart.
=> Update the CRD default storedVersion

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md
Chart.yaml are necessary even for doc changes, while we work on a way to circumvent this, this PR releases the datadog chart to unblock the other ones.
=> Unblock release process

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/templates/NOTES.txt, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml
As part of the General Availability of the Datadog Operator, we are making a major chart update that includes:
- Update the default image to 1.0
- Update the dependency on the `datadog-crd` chart
- Set the default stored version as `v2alpha`
- Add a safeguard in case users try to run the old operator with the new chart or the new operator with `v1alpha1` as the stored version.
- Remove the mention of the RC/beta.
- Need to wait for https://github.com/DataDog/helm-charts/pull/982 to be merged to update the dependency.
=> Datadog Operator GA chart update

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update the Private Location chart to 0.15.11 with new release 1.34.0.
=> [synthetics] Bump to 0.15.11 with PL release 1.34.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_containers-common-env.yaml
The `DD_REMOTE_CONFIGURATION_ENABLED` setting needs to be set not only on the core agent but also on all the other processes.
Without this most features will remain disabled:
- `trace-agent` proxy to forward tracers Remote Config requests, making it impossible to use ASM/DI/etc... with RC.
- `APM_SAMPLING` / `CWS_*`
=> (rcm) fix partial enablement of RC

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml
RC should be enabled even if the cluster agent is disabled.
https://github.com/DataDog/helm-charts/pull/994 added the env var in `{{- define "containers-cluster-agent-env" -}}` instead of `{{- define "containers-common-env" -}}`.
- fixes #
=> (rcm) enable RC even if the cluster agent is disabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/kube-state-metrics-core-rbac.yaml
https://github.com/DataDog/datadog-agent/pull/16141 adds support to crd metrics.
same as https://github.com/DataDog/helm-charts/pull/989 but verified
=> feat: add customresourcedefinitions list and watch permissions to kube-state-metrics-rbac.yaml

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to 0.5.12 for the new PL 1.34.1 release.
=> [synthetics] Bump private location chart with release 1.34.1

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml
This PR updates the webhook certificate name in datadog-operator's deployment.yaml to match how the certificate name is generated (i.e. using `.Release.Name` since #1006)
Apologies for missing this on the previous version.
- follow up from #1006 
=> Update reference to webhook certificate secret name in deployment.yaml for datadog-operator

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` to `7.43.2` version.
=> feat(datadog): default to 7.43.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-fips-proxy.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
For customers using GOVCLOUD, the FIPS compliant side car proxy is necessary to forward data to the backend.
This PR introduces the logic to add the side car to the Agent, the Cluster Agent and the Cluster Level Check Workers.
The side car opens 13 ports by default (only to the local pod network namespace, not on the node) for each feature, per [this config](https://github.com/DataDog/datadog-agent/blob/7.44.x/pkg/config/config.go#L1564-L1577).
Environment variables are added to the Agent containers (trace, process, security...), DCA and CLCW for the forwarders to use the side car.
TODO: 
=> Adding support for the FIPS sidecar container.

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml
Add `memfd_create` to system-probe seccomp policy.
Needed for runtime compilation sealed memfd feature from https://github.com/DataDog/datadog-agent/pull/15726
=> Add `memfd_create` to seccomp for system-probe

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to 0.5.13 for the new PL 1.35.0 release.
- fixes #
=> [synthetics] Bump private location chart with release 1.35.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` to `7.44.1` version.
N/A
=> [datadog] default agent to 7.44.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
Follow-up to https://github.com/DataDog/helm-charts/pull/1050
The change was still not fixing the problem. It appears to be because of issues restricting creation of leases to specific resource names (see [kubernetes documentation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources))
We are already using a similar pattern for the configmap permission, I assume for the same reason
I validated this locally via minikube
=> [helm][dca][rbac] Fix create permission for leases in DCA

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml
This PR adds `list` and `watch` permissions of crd resources to the datadog-operator.
KSM core check now watches `customresourcedefinitions`.
- fixes #
=> [Operator][RBAC] Add CRD `list` and `watch` permissions to datadog-operator

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_kubernetes_state_core_config.yaml, charts/datadog/templates/cluster-agent-rbac.yaml
This PR adds RBAC permissions to the ksm core rbac and configures the check to monitor `apiservices` since metrics are currently available for this resource.
=> [RBAC][KSM] Update config to monitor `apiservices`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This change bumps the default version of the fips-proxy image used to fix issues with DNS handling in restricted environments.
=> [datadog] Update `fips.image.tag` to 0.5.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Pass its pod name to the cluster agent.
It’s used by DataDog/datadog-agent#17305 to improve the leader election when the cluster-agent runs with `hostNetwork: true`.
=> Pass its pod name to the cluster-agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
Currently pointdir is mounted on C:/var/log but we look for registry.json by [default](https://github.com/DataDog/datadog-agent/blob/85eac7ff934d3f0b5525d960e2f03684cfa68d6d/pkg/config/config_windows.go#L19) at `c:/programdata/datadog/run`. This location is currently mapped to an ephemeral volume, `config`.
Because of it, when an agent container is restarted for whatever reason, most commonly configuration updates, it loses the pointers for the logs.  It results in customers ingesting multiple times the same log entries.
=> Updated pointerdir mountPath for Win deploy

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to 0.5.14 for the new PL 1.36.0 release.
=> [synthetics] Bump private location chart with release 1.36.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` to `7.45.0` version.
=> feat(datadog): default agent/dca to 7.45.0

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Releases OPW chart pointing to OPW v1.2.1
- OPW v1.2.1 contains a bug fix for loading configurations via remote configuration (private beta atm)
- Doc update (kudos to @taka2noda)
=> [OPB-892] Release OPW 1.2.1 chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-scc.yaml, charts/datadog/templates/cluster-agent-scc.yaml
Upgrading an OpenShift cluster to 4.11+ after the datadog agent has been deployed fails because the datadog SCC has a higher priority than the OpenShift `restricted-v2` one.
=> Set the OpenShift SCC priority to null

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
The setting `dogstatsd.tagCardinality` is ignored if `dogstatsd.originDetection` is false. I don't see a reason for such dependency.
=> Sets tagCardinality independently

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
This PR updates the script used by the cluster agent initContainer to update the permissions of the files in /etc/datadog-agent before copying them to /opt/datadog-agent.
As a consequence of [this change](https://github.com/DataDog/datadog-agent/pull/16347) introduced to the cluster agent image, the init container would fail if `securityContext` was set to anything non-root with the following error:
```
cp: cannot stat '/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default': Permission denied
cp: cannot stat '/etc/datadog-agent/conf.d/orchestrator.d/conf.yaml.default': Permission denied
```
This is fixed by changing the permissions of this directory from 644 to 744.
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets …
=> [datadog] Fix cluster agent pod failing to start when securityContext is set

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/cluster-agent-deployment.yaml
As we plan to enable Remote Configuration by default in the future, we need to make sure that RC being disabled in the chart actually disables RC in the agent. This is what this PR does by enforcing the presence of the RC enablement env var.
N/A
=> upgrade(datadog): Always set the Remote Configuration environment variable

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go
Fix the datadog-operator deployment template to correctly set the user-configured `datadogCRDs.migration.datadogAgents.conversionWebhook.enabled` parameter. 
Previously, the `-webhookEnabled` container arg was not being set on the datadog-operator deployment.yaml when `datadogCRDs.migration.datadogAgents.conversionWebhook.enabled` was set to `true`. It was only set when the config was set to `false`. This bug was obscured by the `datadog-operator` binary which has the default behavior of `webhookEnabled: true`. 
When the default behavior in the datadog-operator is updated to `webhookEnabled: false` in a future version, users using the conversion webhook must upgrade their datadog-operator helm chart to the latest version in order to avoid any interruption in the conversion webhook. …
=> Fix conversionWebhook.enabled parameter to set user-configured value

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to 0.5.15 for the new PL 1.37.0 release.
None
=> [synthetics]: Updates PL version to 1.37.0 and Chart version to 0.15.15

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Release agent 7.46.0.
- [] Variables are documented in the `README.md`
=> release 7.46.0 final build

charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
Updates `datadog-crds` dependency to v1.0.1
=> [datadog] Update datadog-crds dependency to v1.0.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
Removes DataStreamsMonitoring option
- fixes #
=> Remove DataStreamsMonitoring support

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Fix datadog operator cluster role permission that was added in https://github.com/DataDog/helm-charts/pull/1054
=> [operator] fix clusterrole

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR update the fips-proxy tag to use the latest release which reduces the number of health check because the traffic overhead was high
- fixes #
=> Update FIPS Proxy version to 0.5.4

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Releases the 1.3.1 chart pointing to the `1.3.1` image
* Closes OPB-979
- Drafted pending official release
=> OPB-979: Release OPW 1.3.1 chart

.github/workflows/go-test.yaml
Only run the github workflow `Go Test` when a pull request modified the `datadog-operator` chart.
- fixes #
=> Run Github workflow Go test only for the datadog-operator chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_daemonset-volumes-windows.yaml
The chart does not render the daemonset correctly for windows datadog agents due to missing the `logdatadog` volume 
- fixes #1133 
=> include volume in daemonset-volumes-windows definition

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml
What this PR does / why we need it:
Trivial spelling corrections 
Checklist
=> Correct spelling (Agetn --> Agent)

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
This PR ensures the core agent is aware that CSPM is enabled, fixing the wrong values reported by the inventories.
=> ensure the core agent is aware that CSPM is enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-cilium-network-policy.yaml, charts/datadog/templates/agent-clusterchecks-cilium-network-policy.yaml
Adds the additional intakes for profiling, network, dbm, and remote config into the `CiliumNetworkPolicy` for the node Agent. Adds missing relative ones for Cluster Check Runner. Relative to the missing ones here:
- https://docs.datadoghq.com/agent/guide/network/?tab=agentv6v7
Excluding RUM and Synthetics since the Agent won't hit those. Excluding APM related ones on Cluster Check Runner. 
Can test with config like the following, with no `site` or the respective `site` to use. 
```yaml
datadog:
apiKey: <API_KEY>
site: datadoghq.com
logLevel: debug
networkPolicy:
create: true
flavor: cilium  
```
Can curl the endpoints within the Agent container to validate connectivity depending on the site like. Any response from server is good, will timeout if egress is invalid.
```
curl …
```
=> Add additional cilium intakes for profiling, network, dbm, remote config to node Agent and CCR

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go
Update `datadog-operator` chart for v1.1.0 release
- fixes #
=> Update operator chart for 1.1.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-host-release-volumemounts.yaml
Removes `mountPropagation` for `/etc/os-release` files which were in a separate template from the fixes in #810 
- fixes #
=> Remove mountPropagation for /etc/os-release files

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/agent-clusterchecks-deployment.yaml
Fixes DaemonSets getting stuck in Autopilot when the same env var is defined multiple times.
Currently, `DD_PROVIDER_KIND` is defined twice. This is a spec violation but the validation currently is not enforced during creation. But this prevents the pod GC from removing pods because it seems at that time a different validation is used.
See https://github.com/kubernetes/kubernetes/issues/118261
- fixes #1142
`provider-env` is currently included in both `containers-cluster-agent-env` and `containers-common-env`. Containers that use `containers-common-env` also use `containers-cluster-agent-env` most of the time. `containers-cluster-agent-env` is only used without `containers-common-env` in `charts/datadog/templates/agent-clusterchecks-deployment.yaml`
[Place an '[x]' (no spaces) in all …
=> avoid creating the DD_PROVIDER_KIND env var two times

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
This pr fixes `mutatingwebhookconfigurations` RBAC to avoid restricting create to a specific resource name.
- fixes #
=> Fix `mutatingwebhookconfigurations` RBAC to avoid restricting `create` to a specific resource name

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-services.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-network-policy.yaml, charts/datadog/values.yaml
This PR opens port 8000/TCP for `cluster-agent` container to communicate with the Admission Controller.
- fixes #848
NetworkPolicy ingress rule has already been implemented in #152
=> feat: open container port 8000 for admission controller

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helm_check_config.yaml
Branch from contributor PR https://github.com/DataDog/helm-charts/pull/954, PR fixes issue reported in #953, both by [pc-brizkowsky](https://github.com/pc-brizkowsky). 
Branch is rebased on main and updates changelog and chart version.
#953 
=> fix(helmchecks): 🐛 This fixes an issue with an empty line

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/rbac.yaml
A rule was added to allow the agent to curl `/metrics/slis`, exposing the SLI metrics provided by Kubernetes as a part of the changes made in https://github.com/DataDog/integrations-core/pull/15731
Does the corresponding change need to be made in the operator as well?
=> Add rule to allow agent role to curl `/metrics/slis`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/rbac.yaml
Our Helm Chart has the helper function for `agents.serviceAccountName` to set the Service Account Name to the `datadog.fullname` OR if in GKE AutoPilot force this to `datadog-agent`. This is used in our normal `ClusterRoleBinding` for the Agent. However, the extra `RoleBinding` when granting permissions to specific secrets uses the old `datadog.fullname` value. This can cause that mismatch in GKE Autopilot where the RoleBinding is referencing the "wrong" service account name, so the Agent won't have the right permissions to fetch those secrets.
Helper 
https://github.com/DataDog/helm-charts/blob/datadog-3.35.1/charts/datadog/templates/_helpers.tpl#L505-L516
ClusterRoleBinding with correct reference
https://github.com/DataDog/helm-charts/blob/datadog-3.35.1/charts/datadog/templates/rbac.yam …
=> Fix serviceAccountName for Secrets RoleBinding in GKE Autopilot

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
A rule was added to the operator cluster role to curl `/metrics/slis`, exposing the SLI metrics provided by Kubernetes as a part of the changes made in https://github.com/DataDog/integrations-core/pull/15731. A similar change was applied to the agent role in https://github.com/DataDog/helm-charts/pull/1155.
=> [operator] Add rule to allow operator cluster role to curl `/metrics/slis`

repository.datadog.yml
when using the mergequeue, we need to restrict who can actually merge using the commands.
=> added repository config mirroring the repo access settings

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds an option to enable CWS security profiles (runtime anomaly detection)
- fixes #
=> add option to enable CWS security profiles (runtime anomaly detection)

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR updates the fips-proxy tag to use the latest release which uses new versions of HAProxy (2.4.24) and zlib (1.3).
- fixes #
=> Update FIPS Proxy version to 0.5.5

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to 0.15.17 for the new PL 1.39.0 release.
=> [synthetics] Bump to 0.15.17 with Private Location 1.39.0

examples/datadog/agent_on_aks_values.yaml
What the title says. This is a change in example file - no chart/values/doc change.
`datadog.kubelet.tlsVerify: false` was necessary due to an issue in AKS distribution which was resolved late last year https://github.com/Azure/AKS/issues/2770. 
Documentation was updated to reflect the change here https://github.com/DataDog/documentation/pull/17436 so not updating it now. 
For testing provisioned AKS cluster, and did helm install with the example values override.
Related issue https://github.com/DataDog/helm-charts/issues/972
https://github.com/Azure/AKS/issues/2770
https://github.com/Azure/AgentBaker/pull/2352
- fixes #
[Place an '[x]' (no spaces) in all applicable …
=> Remove datadog.kubelet.tlsVerify override in Agent on AKS example

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/values.yaml
Request through support to not mount `/etc/passwd` when only container collection is enabled in the process agent. 
diff chart template for `datadog.processAgent.processCollection` set to `false` and `true`
```
1010a1011,1012
>           - name: DD_PROCESS_AGENT_ENABLED
>             value: "true"
1050a1053,1055
>           - name: passwd
>             mountPath: /etc/passwd
>             readOnly: true
1204c1209
```
- fixes #
=> Mount `/etc/passwd` in process agent only if process collection is enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml
Disables Remote Config in the cluster checks runner as it is not supported there
- 
=> fix(clusterchecksrunner): Disable Remote Config in cluster checks runner

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/security-agent-compliance-values.yaml, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/values.yaml
This change renames the `datadog.securityAgent.compliance.xccdf.enabled` parameter to `datadog.securityAgent.compliance.host_benchmarks.enabled`.
The `xccdf` parameter has been renamed to `host_benchmarks` since Agent 7.47.
=> Rename xccdf parameter to host_benchmarks

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
This temporarily reverts https://github.com/DataDog/helm-charts/pull/1157 .
Why we need this is a long story. There is a crash loop in the cluster agent that a customer on GovCloud reported. I am fixing that crash loop in https://github.com/DataDog/datadog-agent/pull/19596 for the 7.49 build of the agent. I am backporting the fix in https://github.com/DataDog/datadog-agent/pull/19657 to the 7.48 build of the agent. However, right now we are still 1-2 weeks away from releasing 7.48, and we need a workaround to make the cluster agent not crash until then.
The crash only happens when the following conditions are true:
- `admission_controller.auto_instrumentation.patcher.enabled` is true - otherwise we will [never call StartControllers](https://github.com/DataDog/datadog-agent/blob/c0487d93f9b …
=> Revert enabling remote configuration by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
* Default `Agent` and `Cluster-Agent` to `7.47.1` version.
=> [datadog] Update agents to 7.47.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
PR to keep Remote Config enabled on the host agent after #1177, as some customers may already have upgraded. The cluster agent only uses Remote Instrumentation so it's fine to let it have RC disabled by default.
N/A
`remoteInstrumentation.enabled` is still set to `false` by default with this PR
=> fix(remoteConfig): Enable Remote Config by default again on the host agent only

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/rbac.yaml
Skip references to `PodSecurityPolicy` objects on recent Kubernetes clusters where their support has been dropped.
* CONS-5802
=> Skip references to `PodSecurityPolicy` on recent Kubernetes clusters

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR update the fips-proxy tag to use the latest release which now use OpenSSL 3.0 instead of OpenSSL 1.0.2
=> Update FIPS Proxy version to 0.6.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
* This PR introduces the parameter `operatorMetricsEnabled` (`true` by default) to enable/disable the operator metrics forwarder component by modifying the flags passed to the container : https://github.com/DataDog/datadog-operator/blob/35f34ae25e3c8ce43c1d548595f14ec8c5e4e0b4/main.go#L147
* https://datadoghq.atlassian.net/browse/CECO-1 
=> [CECO-1] Add parameter to enable/disable operator metrics forwarder

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
We're in the process of moving the orchestrator pod check from the process agent to corechecks. This means we need `orchestrator_explorer.enabled` to default to true in the agent in order to run the check
- fixes #
=> [Orchestrator] Enable orch_explorer by default on agent

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogmetrics.yaml, crds/datadoghq.com_datadogmonitors.yaml
Update CRDs from Operator 1.2.0 tag.
- fixes #
=> Update CRDs from Operator v1.2.0 tag

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml
Fix a small typo in the Datadog operator chart
~_I see https://github.com/DataDog/helm-charts/pull/1195 which will bump the chart version to 1.2.0, I will wait for that one to then bump here the version to 1.2.1 and also update the CHANGELOG.md, as required parts of the checklist_~ 
Checklist items done (unsure if the make update-test-baselines is needed). Let me know if anything else is missing
=> docs: fix typo in Datadog Operator Chart

.github/CODEOWNERS
This is now owned by the @DataDog/observability-pipelines-worker team.
=> chore: Update CODEOWNERS for observability-pipelines-worker chart

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
- Official release for OPW version 1.5.1
=> [observability-pipelines-worker] 1.5.1 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_kubernetes_state_core_config.yaml, charts/datadog/templates/kube-state-metrics-core-rbac.yaml, charts/datadog/values.yaml
The metric `kubernetes_state.configmaps.count` was added in a few releases ago. This change adds a new `datadog.kubeStateMetricsCore.collectConfigMaps` config field to enable collection of config maps resource by default, and allow users to disable it if they'd like. 
The operator currently has `configmaps` collection enabled by default.
=> Add `kubeStateMetricsCore.collectConfigMaps` 

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/_orchestrator_explorer_config.yaml, charts/datadog/templates/cluster-agent-confd-configmap.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
1. Add new field `orchestratorExplorer.customResourcesCollection` to collect custom resources
2. Update RBACs according to `orchestratorExplorer.customResourcesCollection`
3. Mount a default config if custom config is not provided
- fixes #
=> Support custom resources and custom resource definitions collection in orchestrator explorer

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default Agent and Cluster-Agent to 7.48.0 version.
=> Default Agent and Cluster-Agent to 7.48.0 version

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-init-linux.yaml, charts/datadog/templates/_containers-init-windows.yaml, charts/datadog/values.yaml
This adds support for volume mounts inside the initContainers. For my use case, this allows custom shell scripts to be placed in `/etc/cont-init.d` to run when the container starts up.
While there isn't an issue _specifically_ for this, there are a number of issues that would be solved with this change:
- #286 requests support for additional initContainers. This is an option, but with a larger blast radius to consider.
- #294 was submitted over 2 years ago to fix the issue above, but was never discussed or merged.
- #1107 added direct support for community integrations, but it was closed due to operational risk. This change uses an existing mechanism built into the image rather than change the startup command.
- #1149 requests community integration installation support. The datadog-agent …
=> add support for initContainer volume mounts

README.md, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/rbac.yaml
Most resources related to the deprecated `PodSecurityPolicies` have already been gated with `if` statements, however there are a few misses specifically related to RBAC. In GKE we are getting deprecation warnings for `io.k8s.policy.v1beta1.podsecuritypolicies.list` which seem to come from the Datadog Cluster Agent (user agent: `datadog-cluster-agent/v0.0.0 (linux/amd64) kubernetes/$Format`).
This PR simply gates the related RBAC using existing flags and checks used to enabled / disable the other `PodSecurityPolicy` resources.
- fixes # n/a
=> Only include RBAC for PodSecurityPolicies when enabled

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to 0.5.18 for the new PL 1.40.0 release.
=> [synthetics] Bump to 0.15.18 with PL 1.40.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default Agent and Cluster-Agent to 7.48.1 version.
=> default agent and cluster agent images to version 7.48.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-apiservice.yaml, charts/datadog/templates/hpa-external-metrics-rbac.yaml, charts/datadog/values.yaml
External metrics server is started by the datadog agent when `clusterAgent.metricsProvider.enabled` is set to `true`. It is also registered by the helm chart in the kube api server as an APIService and an rbac is created to support it. 
This PR allows the user to enable creating an external metrics server while still disabling registering the external metrics server as an APIService. 
It does so by adding the option `clusterAgent.metricsProvider.registerAPIService` to allow user to disable registering external-metrics server as an `APIService`
This allows the user to use other external-metrics providers (such as KEDA) in the cluster, but also use the datadog cluster-agent as a metrics proxy to datadog. 
- `clusterAgent.metricsProvider.registerAPIService` is defaulted to `true` in …
=> Added option to disable external metrics registration as an APIService

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/values.yaml
Enable “container lifecycle events” collection by default.
=> [CONTINT-3345] Enable container lifecycle events collection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
Add:
- datadog.features.containerMonitoring.containerImageCollection.enabled to enable collection of container image metadata
- datadog.features.sbom.containerImage.enabled to enable SBOM collection for container images
- datadog.features.sbom.host.enabled to enable SBOM collection for host filesystem
Right now, we rely on environment variables which is not optimal as it makes checks on required
features complicated : for instance, SBOM collection relies on container runtime support to be enabled.
- fixes #
=> Allow enabling SBOM collection for host and container images

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Bump FIPS Proxy to fix bump openssl to latest version (3.0.12)
- fixes #
=> Update FIPS Proxy version to 0.6.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Set the default agent and cluster agent version to `7.49.0`.
- fixes #
=> Set default agent and cluster agent version to `7.49.0`

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.41.0.
None
=> [SYNTH-11523] bump PL image version to 1.41.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Remove a buggy
```
chmod -R 744 /etc/datadog-agent
```
in the init container of the cluster agent:
* it recursively sets the execution bit for the user, even on non-executable, non-directory files.
* it doesn’t set the directory search bit for group and others on directories.
This `chmod` was introduced by #1096 to workaround an issue introduced by DataDog/datadog-agent#16347 and DataDog/datadog-agent#18069.
Let’s rather fix the issue at its root cause: inside the docker image thanks to DataDog/datadog-agent#19673.
- fixes CONS-5810
=> Remove buggy chmod directive

.github/workflows/go-test.yaml
Run Operator tests on `go-test.yaml` ci changes and skip integration tests on PRs from forks. 
- fixes #
=> Skip Operator integ tests on PRs from forks

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
As a part of the changes made in https://github.com/DataDog/datadog-agent/pull/19788 to support filtering of metrics emitted by service/endpoint checks, the values for `DD_CONTAINER_INCLUDE` and `DD_CONTAINER_EXCLUDE` had to be separated between the agent and the cluster agent. 
=> Separate `DD_CONTAINER_INCLUDE/EXCLUDE` for agent/cluster agent

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/pod_disruption_budget.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Fix an issue where when trying to helm install using `--set replicaCount=x`, a typecast issue occurred and the install failed.
```
helm install datadog-operator datadog/datadog-operator --set installCRDs=true --set replicaCount=2
Error: INSTALLATION FAILED: template: datadog-operator/templates/pod_disruption_budget.yaml:1:7: executing "datadog-operator/templates/pod_disruption_budget.yaml" at <gt .Values.replicaCount 1.0>: error calling gt: incompatible types for comparison
```
=> fix(datadog-operator): fix PodDisruptionBudget creation issue when setting replicaCount via --set

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
SecretProviderClass can be used to pull a secret from a cloud provider (ie. AWS Secrets Manager) and create the associated Kubernetes Secret. For this to work, we need to mount the SecretProviderClass in the container. Secret will be pulled when the container start.
This PR add configuration for `volumes` and `volumeMounts` so that we can pass a SecretProviderClass to the container.
=> feat: datadog-operator add volumes and volumeMounts

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
=> Add GCR EU and Asia registries. Auto adapt value based on selected site.

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/deployment.yaml, charts/synthetics-private-location/values.yaml
Adds support for `dnsPolicy` configuration in the synthetics private location helm chart.
- fixes [#1121](https://github.com/DataDog/helm-charts/issues/1121)
=> [synthetics-private-location] Support dnsPolicy configuration

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Set default agent and cluster agent version to `7.49.1`.
- fixes #
=> Set default agent and cluster agent version to `7.49.1`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl, charts/datadog/ci/apm-single-step-instrumentation-admission-controller-values.yaml, charts/datadog/templates/NOTES.txt, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Starting from release 7.49.x, cluster agent supports Single Step Instrumentation. This change allows configuring Single Step Instrumentation during agent installation with Helm.
This PR is the copy of reviewed and approved https://github.com/DataDog/helm-charts/pull/1211, where I didn't have all commits signed preventing merge.
=> [APM Onboarding] Enable Single Step Instrumentation

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR updates the FIPS Proxy to the latest version
- fixes #
=> Update FIPS Proxy version to 1.0.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
* Uses boolean comparison as `datadog.apm.instrumentation.enabled` is a boolean instead of relying on `eq` type conversion : this prevents the Agent installation when `datadog.apm.instrumentation.disabled_namespaces` is set
* https://github.com/DataDog/helm-charts/issues/1249
=> [APM instrumentation] Use boolean comparison directly in NOTES template

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml
Remove the old `GODEBUG = x509ignoreCN=0` hack introduced #272 by that is not needed anymore.
=> Get rid of the old GODEBUG=x509ignoreCN=0 hack

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
NOTES template has a bug of using snake case formatted Single Step Instrumentation configuration instead of camel case.
With this fix, configuration like
```
apm:
enabled: false
socketEnabled: true
instrumentation:
enabled: true
disabledNamespaces:
- default
enabledNamespaces:
- datadog
- rc-tests
libVersions: []
```
will result in the error
```
➜  helm-charts git:(liliya.belaus/fix-ssi-notes) helm install dd2 ./charts/datadog --dry-run --debug -n datadog -f ~/values-test-cluster.yaml
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /Users/liliya.belaus/dd/helm-charts/charts/datadog
coalesce.go:220: warning: cannot overwrite table with non table for datadog.datadog.apm.instrumentation.libVersions (map[])
coalesce.go:220: warning: cannot overwrite …
```
=> [APM Onboarding] Fix NOTES for APM Instrumentation

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogslos_v1.yaml, charts/datadog-crds/update-crds.sh, charts/datadog-crds/values.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogslos.yaml
Update CRDs for Operator 1.3.0 release. 
- fixes #
=> CRD update from 1.3.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
SLO controller has been released in datadog-operator 1.3.0 and we need a flag to enable it.
=> Parameter to enable SLO controller: rebase and sign

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
This fixes a bug a customer has been facing when enabling host SBOM (`datadog.sbom.host.enabled`)
When the feature is enabled, the agent needs to have access to the package manager databases of the host.
- fixes #
=> Mount host package manager database when host SBOM is enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR update the fips-proxy tag to use the latest release
- fixes #
=> Update FIPS Proxy version to 1.0.1

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Upgrade to the latest synthetics private location version 1.42.0
- fixes #
=> [Synthetics] Bump private location version to 1.42.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default Agent and Cluster-Agent to 7.50.1 version.
=> [datadog] Update agents to 7.50.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default Agent and Cluster-Agent to 7.50.2 version.
=> [datadog] Update agents to 7.50.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl
Follow-up to https://github.com/DataDog/helm-charts/pull/1258. New Datadog `allowlistedv2workloads` has been published which support the new registries. 
- fixes #1257
=> Support new registries for GKE Autopilot

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
New private location 1.43.0 has been released. This PR updates the definition to that version.
=> [Synthetics] Upgrade Private location to 1.43.0

CONTRIBUTING.md
The policy on the base branch of this repository requires all commits to be signed and verified by Github:
This PR adds a mention for contributors to sign their commits so that their contributions can be accepted.
=> Mention that public contribution commits need to be signed

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/deployment.yaml, charts/synthetics-private-location/values.yaml
This PR allows user to specify [PriorityClass](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#priorityclass) they want to use for Private Location PODs. 
My use case is to guarantee that Private Location pods have higher priority than application pods during scheduling and can't be evicted by app pods in case of resource pressure on the k8s node.
- fixes #
=> [Synthetics] Allow specifying PriorityClass for pods

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
This PR clarifies the usage of `configSecret` in the `synthetics-private-location` chart.
It is only used if you want to manage the secret holding the configuration outside of the Helm chart, and it needs to have a given format (key name needs to be `synthetics-check-runner.json`).
=> [synthetics] Add comments to clarify the usage of configSecret for public PL chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default Agent and Cluster-Agent to 7.50.3 version.
=> [datadog] Update agents to 7.50.3

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
This PR adds additional bind mounts of system files for proper OS detection when generating SBOM for the host. 
- fixes #
=> Fix host OS detection for SBOMs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/agent-sbom-snapshotter.yaml, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
This PR set up container image scanning using the containerd snapshotter.
To do so, it bind mounts the containerd folder and adds the required
capability to mount container images. This is intended to be used when
facing the `discard_uncompress_layers` issue with containerd.
- fixes #
=> Add option to use containerd snapshotter to generate SBOMs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/kpi-telemetry-configmap.yaml
Generates DD_INSTRUMENTATION_INSTALL_TIME and DD_INSTRUMENTATION_INSTALL_ID on installation of Cluster Agent. These env variables are used to power [APM time-to-value KPI](https://docs.google.com/document/d/14vsrCbnAKnXmJAkacX9I6jKPGKmxsq0PKUb3dfiZpWE/edit#heading=h.8d3o7vtyu1y1)
https://datadoghq.atlassian.net/browse/AIT-8952
=> [AIT-8952] Generate DD_INSTRUMENTATION_INSTALL_TIME and DD_INSTRUMENTATION_INSTALL_ID

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/kpi-telemetry-configmap.yaml
BUG FIX
Use `{{ template "datadog.fullname" . }}` instead of `{{ .Release.Name }}` to parametrize the Configmap name
https://github.com/DataDog/helm-charts/issues/1293
=> [Bug fix] Use datadog.fullname to parametrize KPI configmap

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/cluster-agent-deployment.yaml
Previous bug fix PR changed the configmap name, but not its usage. Updating used configmaps in Cluster and Trace agents.
- fixes #
=> [Bug fix] Use correct KPI configmap in Cluster and Trace Agents

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 1.8.0
- Resolves OPA-957
=> [observability-pipelines-worker] 1.8.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_containers-common-env.yaml, charts/datadog/values.yaml
Chart is missing support for OTLP logs.
Added `otlp.logs.enabled` option to datadog agent to set `DD_OTLP_CONFIG_LOGS_ENABLED`.
- fixes #1298
=> added `otlp.logs.enabled` option to datadog agent to set `DD_OTLP_CONFIG_LOGS_ENABLED`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Bump FIPS Proxy version to the latest one
=> Update FIPS Proxy version to 1.1.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/daemonset.yaml
Exclude the agent pod from library injection (receiving new environment variables) when the admission controller is enabled. The agent doesn't send traces and it can be configured to send dogstatsd metrics so it is unnecessary to perform library injection on the agent pod. 
This change will also prevent daemonset/agent pod creation problems in GKE Autopilot, which does not allow privileged pod to be mutated. 
- fixes #
=> Exclude agent pod from admission controller library injection

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
New private location 1.44.0 has been released. This PR updates the definition to that version.
=> [Synthetics] Upgrade Private location to 1.44.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Bump FIPS Proxy version to the latest one
- fixes #
=> Update FIPS Proxy version to 1.1.1

.github/kind_config.yaml
the goal is to ease the CI migration from `kubeval` to `kubeconform` introduced by the PR #1199
- fixes #
=> add(tooling): Add disktype label on kind nodes

.github/kind_config.yaml, .github/workflows/ci.yaml
In previous PR #1316 I added `node` labels in the kind cluster config. But this config was not used in the CI test...
This PR add the config path to the `helm/kind-action` configuration. Also this PR fix the yaml linter.
- fixes #
=> fix(tooling): add config file path in helm/kind-action

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1beta1.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogmonitors.yaml
Update datadog-crds following release of Datadog Operator 1.4.0
=> update datadog-crds for operator 1.4.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go, test/integ/operator_integ_test.go
Update latest image reference for Datadog Operator to 1.4.0
=> update latest image in datadog-operator chart to 1.4.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/agent-clusterchecks-deployment.yaml
We're deploying the chart using ArgoCD and ApplicationSets with a cluster generator. To avoid having to bake Datadog-specific logic into our wider ArgoCD Application generator, we need support for rendering `clusterName` as a template variable in order to generate an appropriate value from generic values.
=> feat: support templated clusterName

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Default Agent and Cluster-Agent to 7.51.0 version.
=> [datadog] Update agents to 7.51.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds the missing config toggle for CWS auto suppression, and turns it on by default.
- fixes #
=> [SEC-12368] allow configuring CWS security profile based auto suppression feature and enable it by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/daemonset.yaml
Exclude the agent, cluster agent and clusterchecks pods from any kind of mutation performed by the Admission Controller. With this change Admission Controllers will not inject configs, tags or tracing libraries into DD resources.
Agent pod for latest helm-chart:
```
apiVersion: v1
kind: Pod
metadata:
annotations:
checksum/autoconf-config: 74234e98afe7498fb5daf1f36ac2d78acc339464f950703b8c019892f982b90b
checksum/checksd-config: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
checksum/clusteragent_token: 03184415b2e1becb4249a9453d54f35f031f89ed107c895018bf4ec611d9265e
checksum/confd-config: 44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
checksum/install_info: 53a0b6d31a0130a55703ac799b2ab18fdaed9e338e6d27bf12695bb42b598cb4
creationTimestamp: …
```
=> Disable mutations on Datadog resources pods

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Add option to enable introspection following the release of Operator 1.4.0
=> [datadog-operator] add flag for introspection

.gitlab-ci.yml
the current `e2e` gitlab-ci job is manual. 
to avoid running it during the merge-queue process a new rules is needed to check the CI_COMMIT_BRANCH
- fixes #
=> Avoid running e2e state during mergequeue run

.gitlab-ci.yml
* Run e2e tests during mergequeue only for `datadog` chart 
* Don't run e2e tests for any other charts change on `main`: for now e2e tests is only testing the `datadog` chart.
* Keep the possibility to run e2e test manually on other branch.
- fixes #
=> Run e2e tests during mergequeue for `datadog` chart

charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Following PR https://github.com/DataDog/helm-charts/pull/1332 , update chart version and associated files
=> [datadog-operator] bump chart to 1.5.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
set default version to 7.52.0 
- fixes #
=> feat(datadog): set default version to 7.52.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml
Disable by default language detection reporting with Agent 7.52.0.
- fixes #
=> Disable language detection reporting by default

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
=> Update PL version to 1.46.0

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/deployment.yaml
0.15.29 breaks the indentation of `envFrom` in the `synthetics-private-location` deployment template. This adjusts the templating to use the same `{{-` and `nindent` that other variables use.
Tested locally by uncommenting the example `envFrom` in `values.yaml`:
Before this change:
`$ cd charts/synthetics-private-location`
`$ helm template .`
```
Error: YAML parse error on synthetics-private-location/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: did not find expected key
Use --debug flag to render out invalid YAML
```
After this change:
Valid yaml.
Tested with:
```
$ helm version
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
```
*(optional, in `fixes #<issue number>(, fixes …
=> Fix envFrom indentation in synthetics-private-location

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/deployment.yaml, charts/synthetics-private-location/values.yaml
Add `podLabels` value to allow setting labels that only appear on the pods managed by the deployment.
Need pod label for monitoring that value changes regularly with version upgrades. Cannot use `commonLabels` because they are used as match labels which are immutable.
- fixes #1357 
=> Add `podLabels` value to allow setting labels that only appear on the pods managed by the deployment.

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/other_default.yaml, test/datadog/dca_AC_sidecar_test.go
Set default `Agent` and `Cluster-Agent` version to `7.52.1`.
- fixes #
=> [datadog] Update agents to 7.52.1

charts/datadog/CHANGELOG.md
Adding back changelog message accidentally removed in pull #1328
- fixes #
=> Fix CHANGELOG for 3.59.5

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update chart for release 1.47.0 of the Synthetics Private Location.
=> [Synthetics] Private Location 1.47.0

.github/workflows/release.yaml
If a chart was updated but the version was not bumped (example documentation, changelog), the [release job will fail for all charts](https://github.com/DataDog/helm-charts/actions/runs/8702337157/job/23964331154) with:
```
Error: error creating GitHub release datadog-3.59.6: POST https://api.github.com/repos/DataDog/helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
This PR adds the `CR_SKIP_EXISTING` flag to the release to ignore this issue.
- fixes datadog/synthetics-private-location 0.16.1 release: https://github.com/DataDog/helm-charts/pull/1372#issuecomment-2062057411
- ~~Chart Version bumped~~
- ~~Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)~~
- ~~`CHANGELOG.md` has been updated~~
- …
=> [release] Add `CR_SKIP_EXISTING` flag to release job

charts/synthetics-private-location/README.md, charts/synthetics-private-location/README.md.gotmpl
Small PR to trigger the [release pipeline](https://github.com/DataDog/helm-charts/blob/main/.github/workflows/release.yaml) to properly publish the latest Private Location version after the fix: https://github.com/DataDog/helm-charts/pull/1378
> [!CAUTION]
> We skip updating the charts as the previous release failed and we want to retry it https://github.com/DataDog/helm-charts/pull/1372
- ~~Chart Version bumped~~
- ~~Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)~~
- ~~`CHANGELOG.md` has been updated~~
-  ~~Variables are documented in the `README.md`~~
- ~~For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)~~
=> [doc] Update Private Location documentation link

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Opened from fork https://github.com/DataDog/helm-charts/pull/1337: 
> Add support for ASM in activation cluster-wide via admission webhook. (cf. https://github.com/DataDog/datadog-agent/pull/23618)
> Sister PR of https://github.com/DataDog/datadog-operator/pull/1151
=> [ASM] support enabling ASM features cluster-wide

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Fixes dap permissions not being added to clusterrole when DAP is enabled in chart
- fixes #
=> [datadog-operator] Fix clusterrole for dap

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Bump FIPS Proxy version to the latest one
- fixes #
=> Update FIPS Proxy version to 1.1.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Enables the kubelet core check by default. We have tested the kubelet core check internally and would like to push it out to a broader audience so we can make any fixes necessary before we can enable the kubelet core check everywhere and eventually deprecate the Python check.
- fixes #
=> Set kubelet core check option to be enabled by default

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/values.yaml
Add a new Global setting for the Origin Detection Unified setting of the Agent. This setting is a global one as it control Origin Detection behaviour for multiple Operator features (APM and DogStatsD).
Using the following chart:
```
➜  helm cat enabled.yaml
registry: public.ecr.aws/datadog
datadog:
clusterName: wassim-minikube
apiKeyExistingSecret: datadog-secret
appKeyExistingSecret: datadog-secret
originDetectionUnified:
enabled: true
kubelet:
tlsVerify: false
coreCheck: true
agents:
image:
tag: 7.54.0-rc.3-jmx
env:
- name: DD_TELEMETRY_ENABLED
value: true
```
You should see:
```
➜  helm k exec -it datadog-agent-56tr4 -- agent config | grep unified
Defaulted container "agent" out of: agent, trace-agent, process-agent, init-volume (init), init-config (init)
origin_detection_unified: true …
```
=> feat(origin-detection): add unified setting

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds a new config option to control the track CWS events are sent to:
- `false` -> to `log` as is currently the case
- `true` -> to `secruntime` which is the new track specific for CWS events that we are in the process of migrating to
It's currently disabled by default, it will be switched to `true` in another PR (very soon).
- fixes #
=> [CWS] add new config option to control the CWS events track

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
https://github.com/DataDog/helm-charts/pull/1394 created the toggle to start sending CWS events directly to the new explorer/track. This PR turns it on by default now that we believe all the backend and frontend pieces are ready for this.
- fixes #
=> [CWS] default option to switch CWS events to the new track to true

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
[OPA-1733](https://datadoghq.atlassian.net/browse/OPA-1733)
Makes the 2.0.1 release of OPW available to Helm  
- fixes #
[OPA-1733]: https://datadoghq.atlassian.net/browse/OPA-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [observability-pipelines-worker] 2.0.1 release 

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml
This PR fixes https://github.com/DataDog/helm-charts/pull/1394 by making sure the security agent is aware of the config flag.
=> [CWS] make sure the security agent is aware of `datadog.securityAgent.runtime.useSecruntimeTrack`.

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Update chart for release 1.48.0 of the Synthetics Private Location.
=> [Synthetics] Private Location 1.48.0

.github/CODEOWNERS
Add @DataDog/processes as a code owner for the process agent template `_container-process-agent.yaml`
This ensures the Processes team is aware of PRs that affect the process agent.
Note: This PR also reorders the files alphabetically and fixes the system-probe filenames.
=> Add CODEOWNER for process agent template

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml
This PR removes enabling live process collection by default when language detection is enabled.
Fixes the issue of enabling live process detection by default for APM SSI users.
- [A fix](https://github.com/DataDog/datadog-agent/pull/26116) was implemented in the agent to allow language detection to work in case live process collection is not enabled.
- The initial PR that activated live process collection by default when language detection is enabled can be found [here](https://github.com/DataDog/helm-charts/pull/1338).
=> do not enable live process collection by default when language detection is enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
Update RBACs for collection of Kubernetes LimitRange and StorageClass resources.
=> Update RBACs for storageclass and limitrange collection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Set default `agent` and `cluster-agent` version to `7.54.0`.
- [] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)
=> Set default (cluster-)agent version to `7.54.0`

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Makes the latest OPW 2.0.2 release ([DockerHub](https://hub.docker.com/layers/datadog/observability-pipelines-worker/2.0.2/images/sha256-0c66a695805cf0f732cc8fe5c3ebaee6c45b1a1b634227658fe6739cccd0a8d1?context=explore) & [Github](https://github.com/DataDog/observability-pipelines-worker/releases/tag/2.0.2) ref) available to Helm users 
- fixes #
=> [observability-pipelines-worker] release 2.0.2

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Adds `DD_TOOL_VERSION=helm` to operator helm chart
=> [CECO-1228][operator] Add tool version to operator helm chart

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1beta1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1beta1.yaml, crds/datadoghq.com_datadogagentprofiles.yaml, crds/datadoghq.com_datadogagents.yaml
Update CRDs following release of Datadog Operator 1.7.0
- ~[ ] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)~
=> [datadog-crds] update CRDs following datadog operator 1.7.0 release

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_with_certManager.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog-operator/operator_deployment_test.go, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/other_default.yaml, test/datadog/dca_AC_sidecar_test.go
Update Datadog Operator chart following the 1.7.0 release
=> [datadog-operator] update chart for 1.7.0

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml
Modifies the tool version set in the operator helm chart. While the value should not need to be changed by the end user, we need to be able to modify it in our chart wrappers.
=> Modify tool version in operator chart

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml, charts/datadog/values.yaml
[CONTP-257](https://datadoghq.atlassian.net/browse/CONTP-257)
Expose namespaceAnnotationsAsTags option
We recently added support for “kubernetes namespace annotations as tags” option: https://github.com/DataDog/datadog-agent/pull/25585 
However, it’s not exposed in the public helm chart.
We already have a setting for “kubernetes namespace labels as tags” (`datadog.namespaceLabelsAsTags`) so we should also have one for the annotations to avoid having to configure this using ENVs.
- [x ] Chart Version bumped
- [ x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x ] `CHANGELOG.md` has been updated
- [x ] Variables are documented in the `README.md`
[CONTP-257]: …
=> [CONTP-257] add namespaceAnnotationsAsTags to helm chart

.github/workflows/go-test.yaml
Run Operator integ test on Kubernetes 1.30
- fixes #
- [] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)
=> Add Kubernetes 1.30 to Operator integ test

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
The added `startupProbe` in the Helm Chart 3.67.0 appears to conflict with the expected pattern for the Agent in GKE AutoPilot, causing it to get blocked by the GKE Warden. This just adds a simple "if NOT gke.autopilot -> add startup probe". 
Does not make the changes to the Cluster Agent or Cluster Check Runner, as those were not impacted. 
- fixes #1436 
=> Remove startup probe for Agent in GKE AutoPilot due to restrictions

charts/extended-daemon-set/CHANGELOG.md, charts/extended-daemon-set/Chart.yaml, charts/extended-daemon-set/README.md, charts/extended-daemon-set/templates/role.yaml
Fixing this:
```
{"level":"ERROR","ts":"2024-07-03T11:52:48Z","logger":"klog","msg":"error retrieving resource lock datadog-agent-operator/extendeddaemonset-lock: leases.coordination.k8s.io \"extendeddaemonset-lock\" is forbidden: User \"system:serviceaccount:datadog-agent-operator:extendeddaemonset\" cannot get resource \"leases\" in API group \"coordination.k8s.io\" in the namespace \"datadog-agent-operator\"\n"}
```
- fixes #
=> [EDS] Add rbac for the leader election lease

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to `0.16.4` for the new PL `1.49.0` release.
=> [synthetics] Bump to 0.16.4 with PL 1.49.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/values.yaml
This PR:
- makes sure this host benchmark config is propagated to the agent, this was not the case when it was disabled
- turns the config on by default, matching the default value from the agent
- fixes #
=> make sure that disabling CSPM host benchmarks is propagated to the agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_system-probe-init.yaml
This PR allows to overwrite the seccomp-setup initContainer's security context.
It can be a requirement to configure a securityContext.
- fixes #
=> Configure security context for the seccomp-setup initContainer

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/_processes-common-env.yaml, charts/datadog/values.yaml
This PR adds initial support for running Processes-related checks in the core agent instead of the process-agent. This is documented as an experimental feature. 
N/A
There is a possible misconfiguration: If `processAgent.enabled=true` and the process checks are moved to core agent without other running checks on the core agent, the process agent container enters crash loop. We advise in the documentation to set `processAgent.enabled=false` in that case.
=> [PROCS-3709] Add support to run process checks in core agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Set default agent and cluster-agent version to 7.55.1.
=> Set default (cluster-)agent version to 7.55.1

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/_helpers.tpl, charts/synthetics-private-location/templates/pdb.yaml, charts/synthetics-private-location/values.yaml
It is crucial to have at least one instance of a private location running at any moment of time (not to lose visibility of your endpoints). Currently, there is no way to specify [PodDisruptionBudget ](https://kubernetes.io/docs/tasks/run-application/configure-pdb/)to prevent downtime during maintenance of k8s cluster. This pr introduces it (in the similar way it is done for other Dadadog product, for example https://github.com/DataDog/helm-charts/blob/main/charts/observability-pipelines-worker/templates/pdb.yaml
=> [synthetics]  Add support for PDB for private location deployment

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/baseline/Operator_Deployment_with_certManager.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/other_default.yaml, test/datadog/dca_AC_sidecar_test.go
In our deployment of datadog-operator we want to utilize https://github.com/stakater/Reloader to automatically restart (a.k.a. perform a fresh rollout) the deployment of the operator when secrets (e.g. api-key, app-key) change.
=> support setting annotations on datadog-operator deployment

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
CONTP-342
Currently when [datadog.containerLifecycle.enabled](https://github.com/DataDog/helm-charts/blob/b46720a3384eaabe658a8747a4134a99479cddd4/charts/datadog/README.md?plain=1#L700) is false, the setting is ignored. The fix sets a value based on the Helm chart's configuration (true or false), defaults to true if not specified
=> [CONTP-342] Fix container lifecycle

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 2.1.1 
- completes [OPA-2076](https://datadoghq.atlassian.net/browse/OPA-2076)
- [n/a] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)
[OPA-2076]: https://datadoghq.atlassian.net/browse/OPA-2076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [observability-pipelines-worker] 2.1.1 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/agent-otel-collector-no-config-values.yaml, charts/datadog/ci/agent-otel-collector-ports-values.yaml, charts/datadog/ci/agent-otel-collector-values.yaml, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-otel-agent.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/_otel_agent_config.yaml, charts/datadog/templates/agent-services.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/otel-configmap.yaml, charts/datadog/values.yaml, examples/datadog/agent_otel_collector.yaml, examples/datadog/otel_collector_config.yaml
Adds OTel Agent container  . OTel Agent is a Datadog's OpenTelemetry's collector distro that runs along with Agent. 
The PR add example collector configuration and corresponding agent configuration. 
To test the changes use the below helm command 
```
helm install my ./charts/datadog --set-file datadog.otelCollector.config=examples/datadog/otel_collector_config.yaml -f examples/datadog/agent_otel_collector.yaml  --set datadog.apiKey=${DD_API_KEY}              
```
=> Add helm chart installation for OTel Agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
=> Set default (cluster-)agent version to 7.55.2

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/ci/kubeconform-values.yaml, charts/datadog-crds/templates/datadoghq.com_datadogpodautoscalers_v1.yaml
Remove XValidation rule from DPA CRD as requires K8S >= 1.25
=> Remove XValidation rule from DPA CRD as requires K8S >= 1.25

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/examples/config.yaml, charts/private-action-runner/values.yaml
The Private Action Runner was updated to version v0.0.1-alpha24. This PR bumps the version in the associated Chart.
Also adds a missing field to the `examples/config.yaml` file
None
Will update instructions with`--enroll-and-print-config` after UI updates are in.
=> [APF-14] Bump image version and fix example config

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml
The Private Action Runner was updated to version v0.0.1-alpha25. This PR bumps the version in the associated Chart.
=> Bump image version

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml
This PR bumps the version of the private action runner image to alpha26
This makes the current runner up to date with main and fixes the discrepancy created by the broken runner version alpha25. Resolves the revert that was done in [this PR](https://github.com/DataDog/helm-charts/pull/1478)
=> Bumping runner version to alpha26

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml
This PR bumps the version of the private action runner image to alpha27
N/A
=> Bumping runner version to alpha27

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/values.yaml, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/README.md.gotmpl, charts/datadog-operator/templates/NOTES.txt, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, charts/operator-eks-addon/CHANGELOG.md, charts/operator-eks-addon/Chart.lock, charts/operator-eks-addon/Chart.yaml, charts/operator-eks-addon/README.md, charts/operator-eks-addon/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go, test/operator-eks-addon/baseline/chart_render_default.yaml, test/operator-eks-addon/baseline_test.go
Updates add-on for Operator 1.7.0. Addon version was bumped from 0.1.7->0.1.9 as 0.1.8 failed validation (and can't be mutated).
- fixes #
=> Update addon to Operator 1.7.0

.github/workflows/labeler/labels.yaml, charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/templates/deployment.yaml, charts/private-action-runner/templates/secrets.yaml, charts/private-action-runner/values.yaml, repository.datadog.yml
Simplifies README instructions to reflect the new Kubernetes UI.
Includes updates after [discussion ](https://docs.google.com/document/d/1UnKppoT-b6q2cEmFelCfJcmUvEz7VUHi4wNv0cJaOKY/edit)with agent team:
- Splits image into `repository` and `tag` to be consistent with the other charts.
- Updates labeler config to get our chart PRs properly labeled.
- Adds action-platform to the merge queue config 
- fixes #
- Fixes bug where port is required in the config even if the runner is in Workflows mode
Tested using an EC2 instance following: https://datadoghq.atlassian.net/wiki/spaces/SYN/pages/3587637521/How+to+test+the+PL+chart+from+helm-charts+repo
[Place an '[x]' (no …
=> [APF-14] Update chart instructions to reflect new UI and split image value

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/templates/deployment.yaml, charts/private-action-runner/values.yaml
Since customers have to manually define connection credentials in the Helm chart right now, we do not want to copy the credential files.
We will send the HELM_DEPLOYMENT environment variable to the container so the runner can check if it was deployed by Helm and skip copying credential files
- fixes #
Runner changes PR: https://github.com/DataDog/dd-source/pull/120539
=> [APF-14] Send MANAGED_BY environment variable

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Set default agent/cluster agent version to `7.56.0`
- fixes #
=> Set default agent/cluster agent version to `7.56.0`

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml
This PR bumps the version to `alpha29` based on similar changes in the action runner.
Find the [changes here](https://github.com/DataDog/dd-source/pull/120604).
Just bumping version.
=> [WF-8933] Bumping version to alpha29

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
Update helm chart to allow `kubelet.coreCheckEnabled` to be set to `false`. Currently when set to `false`, the value is ignored. 
Similar fix to https://github.com/DataDog/helm-charts/pull/1460.
- fixes #
=> Update helm chart to allow `kubelet.coreCheckEnabled` to be set to false

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-cilium-network-policy.yaml
This PR adds the admission controller port to the CiliumNetworkPolicy, when `clusterAgent.admissionController.enabled` is set to `true`. This port is already exposed by the kubernetes network policy, so this PR brings the cilium version in line with the other
- fixes #
=> Add admission controller port to cilium network policy for the cluster agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR updates the fips-proxy tag to use the [latest release 1.1.4](https://github.com/DataDog/fips-proxy/releases/tag/1.1.4) in the helm chart
- fixes #
=> [ASCII-2204] Update fips-proxy image tag to 1.1.4 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/_processes-common-env.yaml, test/datadog/process_agent_test.go, test/datadog/values/process-run-in-core-envvars.yaml
This PR updates the chart logic for using the `processAgent.runInCoreAgent` features. The changes aim to:
* Make the logic for enabling the process agent container easier to follow.
* Guard the `DD_PROCESS_CONFIG_RUN_IN_CORE_AGENT_ENABLED` from being mistakenly set to `true` in unsupported environments.
* Add a method to ignore any compatibility checks by specifying an env var override. This was mostly done to support testing with custom agent images.
=> [PROCS-4293] Improve support for `processAgent.runInCoreAgent` feature

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Set default agent/cluster agent version `7.56.1` now that it has been released.
- fixes #
=> Set default agent/cluster agent version to `7.56.1`

examples/datadog/agent_on_openshift_values.yaml
Just modifies an example file for the OpenShift Helm configuration. Does not change the actual chart. Moving towards a more standardized version of the configurations. 
- fixes #
Ideally wait to merge until the other ones are approved as well:
- https://github.com/DataDog/documentation/pull/24920
See https://datadoghq.atlassian.net/browse/CONS-6524 for technical details
=> [CONS-6524] Standardize example OpenShift values

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
Adds note of private beta for OTel collector. We are seeing support tickets by customers using OTel collector with regular Agent image. 
=> Add note for OTel collector

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Set default agent/cluster agent version `7.56.2`
- fixes #
=> Set default agent/cluster agent version `7.56.2`

charts/private-action-runner/.helmignore, charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/examples/config.yaml, charts/private-action-runner/templates/_helpers.tpl, charts/private-action-runner/templates/secrets.yaml, charts/private-action-runner/values.yaml
- Add ability to configure connection credentials (Basic Auth, Token Auth, Jenkins, Postgres) in `config.yaml`
- [docs](https://docs.datadoghq.com/service_management/workflows/private_actions/private_action_credentials)
- Users shouldn't pull and untar to add their credentials to `secrets.yaml`
=> [APPS-1924] Add ability to configure connection credentials in config.yaml

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This PR update the fips-proxy tag to bump the openSSL version to 3.0.15
- fixes #
=> Update FIPS Proxy version to 1.1.5

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/values.yaml
There is a new version of the private action runner available
=> Bump private action runner to v0.0.1-alpha31

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml, charts/datadog/values.yaml
[CONTP-375](https://datadoghq.atlassian.net/browse/CONTP-375) Exposing kubernetesResourcesAnnotationsAsTags and kubernetesResourcesLabelsAsTags options in a generic format. We recently added support for these fields in [PR](https://github.com/DataDog/datadog-agent/pull/27369), however, it's not exposed in the public helm chart.
QA'd locally via `helm install datadog-agent -f ~/.../values/linux.yaml ~/Desktop/Datadog/helm-charts/charts/datadog`following steps for [parent issue](https://datadoghq.atlassian.net/browse/CONTP-277)
```
datadog:
logLevel: DEBUG
kubelet:
tlsVerify: false
logs:
enabled: true
containerCollectAll: true
clusterTagger:
collectKubernetesTags: true
podLabelsAsTags:
stale-label: stale-label
podAnnotationsAsTags:
stale-annotation: stale-annotation
namespaceLabelsAsTags: …
```
=> [CONTP-375] Expose k8s resource labels as tags to configure tagger

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml, charts/datadog/values.yaml
* Set default agent/cluster agent version `7.57.2`
=> [datadog/datadog] Update Agent/cluster Agent to `7.57.2`

.github/workflows/ci.yaml
Remove paths-ignore which was added in #1538 and had unintended consequences
=> [ci] rm paths-ignore from lint and test charts

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
Adds the necessary RBACs for the Cluster Agent to modify the `ValidatingWebhookConfigurations`.
This is needed to support the new `ValidatingAdmissionWebhook` controller in the Agent's Admission Controller.
QA:
For the Datadog Agent Helm Chart
```
➜ helm install datadog-agent -f ~/Projects/work/datadog-dev/dev-helm.yaml ~/Projects/work/helm-charts/charts/datadog
W0830 15:00:05.497863   38547 warnings.go:70] spec.template.metadata.annotations[container.apparmor.security.beta.kubernetes.io/system-probe]: deprecated since v1.30; use the "appArmorProfile" field instead
W0830 15:00:05.503343   38547 warnings.go:70] spec.template.spec.containers[0].env[44]: hides previous definition of "DD_LANGUAGE_DETECTION_ENABLED", which may be dropped when using apply
NAME: datadog-agent
LAST DEPLOYED: Fri …
```
=> feat(admission controller): add ValidatingWebhookConfigurations RBAC

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Fix typos: trace-agent -> otel-agent
- fixes #
=> Fix a few typos on otel agent in values.yaml

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 2.2.0
- completes OPA-2407
=> [observability-pipelines-worker] 2.2.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_otel_agent_config.yaml
Simplifies OTel Agent OOTB pipelines.
- OTel Agent is in private beta; no actual customers will be affected by the change.
- The initial OTel Agent config had 2 traces pipelines: `traces` to compute APM stats and `traces/otlp` _potentially_ for probabilistic sampling. After internal discussions, we decided that `traces/otlp` pipeline is not required in OOTB config.
**Pipelines before:**
**Pipelines after:**
- N/A Variables are documented in the `README.md`
- N/A For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)
=> Simplify OTel Agent default pipelines

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogdashboards_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/update-crds.sh, charts/datadog-crds/values.yaml, crds/datadoghq.com_datadogagentprofiles.yaml, crds/datadoghq.com_datadogdashboards.yaml, crds/datadoghq.com_datadogmonitors.yaml
* Updates `datadog-crds` chart for operator v1.9.0
* Adds DatadogDashboards CRD
- fixes #
=> Update crds for operator v1.9.0

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Bumping the PAR helm chart version + runner version
PAR PR - https://github.com/DataDog/dd-source/pull/139372
- fixes #
=> Bump PAR chart to 0.14.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
Mount /usr/lib/sysimage/rpm to properly scan Amazon Linux hosts.
- fixes #
=> Mount /usr/lib/sysimage/rpm when using host SBOM feature

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
* Reverts https://github.com/DataDog/helm-charts/pull/1541: the SBOM feature is not compatible with Bottlerocket nodes. When enabling this feature, kubelet tries to create `/usr/lib/sysimage/rpm` on the node if the directory does not exist, but `/usr` is read-only, thus causing the pod to not be scheduled
```shell
Warning  Failed     12m                  kubelet            Error: failed to generate container "9ccab0256589e0b5c0aae5d8f0f32dad3912f67ebf1595883a02b473a32e06b1" spec: failed to apply OCI options: failed to mkdir "/usr/lib/sysimage/rpm": mkdir /usr/lib/sysimage: read-only file system
```
- fixes #
[Place an '[x]' (no spaces) in all applicable fields. Please …
=> Reverts #1541: do not attempt to mount `/usr/lib/sysimage/rpm`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_ac-agent-sidecar-env.yaml, charts/datadog/templates/cluster-agent-deployment.yaml
The value `clusterAgent.admissionController.containerRegistry` was added in https://github.com/DataDog/helm-charts/pull/1376, as a fix for https://github.com/DataDog/helm-charts/issues/1078.
However, in the original implementation that env var was added to `_ac-agent-sidecar-env.yaml` template, which makes it working only if `clusterAgent.admissionController.agentSidecarInjection.enabled` is `true`.
That should not be the case - the option `DD_ADMISSION_CONTROLLER_CONTAINER_REGISTRY` has a wider use case and does not depend on the `agentSidecarInjection` feature, which was rightly noted in that comment: https://github.com/DataDog/helm-charts/issues/1078#issuecomment-2158033251
This PR fixes that behavior described above: `DD_ADMISSION_CONTROLLER_CONTAINER_REGISTRY` will be added to the …
=> fix: Move DD_ADMISSION_CONTROLLER_CONTAINER_REGISTRY outside of sidecar condition

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
https://github.com/DataDog/datadog-agent/pull/26975 sets the Kubernetes event source based on a mapping of controller to integration. This PR adds the helm chart option `datadog.kubernetesEvents.sourceDetectionEnabled` to enable this feature.
=> Added helm chart option to enable event source mapping

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.53.0.
=> [Synthetics Private Location]: Bump Image version to 1.53.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
What this PR does / why we need it:
Currently, error message is
Error: execution error at (datadog/templates/NOTES.txt:341:4): On GKE Autopilot environments, System Probe is not supported. The option 'datadog.securityAgent.runtime.enabled' must be set 'false'
but system probe can be enabled by other options that are not mentioned in error message. This PR adds those options.
=> Fix system probe error message

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/other_default.yaml
Set default agent/cluster agent version `7.58.0`
=> Update agent / cluster-agent to 7.58.0

.github/helm-docs.sh, .github/kubeconform.sh, .github/workflows/ci.yaml, .github/workflows/go-test.yaml
This just updates and standardizes the Kube versions.
- Update Kubernetes versions and standardize across test matrices
- Update helm-docs to v1.14.2
- Update actions/checkout to v4 in two workflows
- Update helm/chart-testing-action to v2.6.1
- Update setup-helm action to 4.x (4.x is just for node version update)
- Update helm/kind-action to v1.10.0
- Update kubeconform to v0.6.7
See #1199. It had been mentioned there or in another place that 1.16 was still supported - wondering if 1.16 or 1.18 still need to be tested against (I can remove them if wanted).
- fixes #
=> ci: update Kube and test workflows

.github/workflows/ci.yaml
* Removes Kubernetes `v1.18.20` from testing matrix as the underlying action fails since https://github.com/DataDog/helm-charts/pull/1486:
```shell
╰─❯ kind create cluster --config .github/kind_config.yaml --name chart-testing --wait 60s --image kindest/node:v1.18.20
Creating cluster "chart-testing" ...
✓ Ensuring node image (kindest/node:v1.18.20) 🖼
✓ Preparing nodes 📦 📦
✓ Writing configuration 📜
✗ Starting control-plane 🕹️
Deleted nodes: ["chart-testing-worker" "chart-testing-control-plane"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged chart-testing-control-plane kubeadm init --config=/kind/kubeadm.conf --skip-token-print --v=6 --skip-phases=preflight" failed with error: exit status 1
```
*(optional, in `fixes #<issue number>(, …
=> [CI] Remove k8s 1.18.20 from testing matrix

.github/workflows/ci.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
`discard_uncompressed_layers` is enabled by default on GKE and EKS, causing all new customers of infrastructure vulnerabilities on these platforms to have a very high number of errors when generating SBOMs for container images.
- fixes #
=> Enable support for uncompressed layers by default

.github/workflows/ci.yaml, .github/workflows/go-test.yaml
Update our CI workflow configuration and add back CI chart testing with kubernetes v1.18.x.
Since #1486 the CI job was failing on the chart testing with kubernetes `v1.18`. To keep our capability to merge PRs, we commented the testing for 1.18 in #1576.
After investigation we understood the issue: #1486 has pumped the kind-action from `v1.5.0` to `v1.10.0` which pumps the kind-action version from `v0.17.0` to `v0.22.0`. However, kind `v0.22.0` is not able anymore to start the node image `v1.18`.
To solve the issue we now express which kind version needs to be used with each kubernetes version. So we can reintroduce the charts testing on kubernetes cluster `v1.18`.
- …
=> fix: re-introduce k8s 1.18 CI testing

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/daemonset.yaml
In #1573 , `datadog.sbom.containerImage.uncompressedLayersSupport` was set to `true` to prevent errors for the SBOM feature on EKS, GKE, AKS where discard_uncompressed_layers is enabled by default. However, this feature requires `CAP_SYS_ADMIN` and mounts some directories that are not necessarily compatible with other distributions such as GKE Autopilot where the Daemonset can't be admitted anymore. This PR gates this default behind `datadog.sbom.containerImage.enabled` (`false` by default) to ensure we only add these modifications if and only if the user wants to use the SBOM container image feature.
* Fixes #1584
=> Use uncompressedlayerssupport only if containerImage is enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/values.yaml
Fixes the warning message during the installation of Agent with Otel Collector. Adds preview message. 
Previously we were getting 
```
coalesce.go:286: warning: cannot overwrite table with non table for datadog.datadog.otelCollector.config (map[])
coalesce.go:286: warning: cannot overwrite table with non table for datadog.datadog.otelCollector.config (map[])
```
=> Fix helm installation warnings

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
This PR adds a `datadog.sbom.containerImage.overlayFSDirectScan` flag to enable direct scanning
of overlayfs layers to generate SBOM for container images when applicable.
This method does not required CAP_SYS_ADMIN capability compared to the snapshotter/mounts based method.
- fixes #
This PR also fixes both mount and direct overlayfs scanning methods for Docker by bind-mounting
/var/lib/docker
=> Add support for overlayfs direct scan for SBOMs

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml
Rather than delete the entire conf.d folder, only delete the configuration for checks enabled by default.
Currently, this list is
```
/etc/datadog-agent/conf.d/cri.d/conf.yaml.default
/etc/datadog-agent/conf.d/network.d/conf.yaml.default
/etc/datadog-agent/conf.d/container_image.d/conf.yaml.default
/etc/datadog-agent/conf.d/io.d/conf.yaml.default
/etc/datadog-agent/conf.d/ntp.d/conf.yaml.default
/etc/datadog-agent/conf.d/containerd.d/conf.yaml.default
/etc/datadog-agent/conf.d/kubelet.d/conf.yaml.default
/etc/datadog-agent/conf.d/sbom.d/conf.yaml.default
/etc/datadog-agent/conf.d/file_handle.d/conf.yaml.default
/etc/datadog-agent/conf.d/cpu.d/conf.yaml.default
/etc/datadog-agent/conf.d/ecs_fargate.d/conf.yaml.default
/etc/datadog-agent/conf.d/orchestrator_ecs.d/conf.yaml.default …
```
=> Delete default configuration files from cluster checks runner

repository.datadog.yml
We are currently blocked from pushing a PR due to a mistake in how the allowed teams in `repository.datadog.yml` are formatted
Fixes the listed teams so they are in the correct format
=> Fix format of teams listed in github_team_restrictions

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 2.2.0
completes OPA-2579
=> [observability-pipelines-worker] 2.2.1 release

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/values.yaml
When using the Operator, we need additional permissions for CRDs. We need to allow the cluster agent to view these custom resources and in order to do that the operator needs permission to see them. This is currently disabled by default
This fixes a current bug in the operator where users are unable to configure the orchestrator explorer to view and index custom resources
=> [Orch] Add additional permissions for operator to view CRDs

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Bump Private Actions Runner version in order to include recent GitLab changes. DD-Source changes https://github.com/DataDog/dd-source/pull/147598
=> Bump runner version to v0.1.4-beta

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml, test/datadog/process_agent_test.go
* Updates the minimum version `datadog.processAgent.runInCoreAgent` to be 7.57 as this is the version where language detection is supported on the core agent.
* Removes the experimental status for `datadog.processAgent.runInCoreAgent`
=> [PROCS-4303] Remove experimental status and update agent version needed for datadog.processAgent.runInCoreAgent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/README.md.gotmpl
* Document how to use `datadog.envDict` option with the `--set` helm's flag.
- fixes #
=> doc(datadog): docuement datadog.envDict usage

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Add support for the new Cluster Agent Admission settings.
Using the following settings:
```
clusterAgent:
enabled: true
admissionController:
enabled: true
validation:
enabled: false
mutation:
enabled: false
```
Make sure that the output of those commands is as follows:
```
➜ kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io -A
No resources found
➜ kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io -A
No resources found
```
Modify the setting with:
```
clusterAgent:
enabled: true
admissionController:
enabled: true
validation:
enabled: true
mutation:
enabled: true
```
Make sure that the output changes to:
```
➜ kubectl get validatingwebhookconfigurations.admissionregistration.k8s.io -A
NAME              WEBHOOKS   AGE
datadog-webhook   0 …
```
=> feat(admission controller): Add new webhook settings

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Bump the private action runner to v0.1.5-beta
=> Upgrade helm chart with new private action runner version

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/agent-apm-use-local-service-values.yaml, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
- Add a new option to disable hostPorts for the trace-agent with `datadog.apm.useLocalService`.
- This is for K8s clusters that restrict hostPorts and hostPaths volumes, therefore can only use the K8s local service to send traces. 
Currently there is no option to disable the trace-agent's host port and disable UDS for APM since at the moment, the trace-agent gets disabled if both of these are disabled when `datadog.portEnabled` and `datadog.socketEnabled` are both set to `false` respectively.
This PR aims to provide a more flexible option to disable both the host port and UDS and still being able to send traces to the local service.
=> Add a new option `datadog.apm.useLocalService` to disable hostPorts for the trace-agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update `fips.image.tag` to `1.1.6` updating PCRE2 version to 10.44 and HAProxy version to 2.4.28
- fixes #
=> Update FIPS Proxy version to 1.1.6

repository.datadog.yml
Since we want to run e2e tests in gitlab during the merge queue, the parameter `gitlab_check_enable` must be true.
Mergequeue should check the gitlab pipeline status before merging
=> fix(mergequeue): check gitlab-ci to merge PR

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/values.yaml, charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/values.yaml
This PR adds the `pods/exec` RBAC to the `datadog-operator` and the `cluster-agent` deployments, when the "CWS Instrumentation" feature is enabled. It also injects the `cluster-agent` service account name as an environment of the `cluster-agent` deployment in the `datadog` chart (so that in both deployment methods the service account name is properly injected - see https://github.com/DataDog/datadog-operator/pull/1146)
This PR is the helm chart counter part of [this](https://github.com/DataDog/datadog-operator/pull/1146) `datadog-operator` PR. It is necessary to allow the "CWS Instrumentation" feature to be enabled in `remote_copy` mode.
This PR fixes [this issue](https://github.com/DataDog/helm-charts/issues/1613).
Follow the steps in [the datadog-operator …
=> [CWS] Configuration options for enabling CWSInstrumentation in the `cluster-agent`

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogdashboards_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmetrics_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogmonitors_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogpodautoscalers_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogslos_v1.yaml, crds/datadoghq.com_datadogagentprofiles.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogdashboards.yaml, crds/datadoghq.com_datadogmetrics.yaml, crds/datadoghq.com_datadogmonitors.yaml, crds/datadoghq.com_datadogpodautoscalers.yaml, crds/datadoghq.com_datadogslos.yaml
Update CRDs from Datadog Operator v1.11.0 tag: most changes are coming from the kubebuilder version bump and in the case of `DatadogAgent` CRD from additional features
- fixes #
=> [datadog-crds] Update CRDs from Datadog Operator v1.11.0 tag

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.53.0.
=> [release]: Synthetics Private Location 1.54.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Remove `deployments.apps` example for resources tag option since it's not implemented yet
=> Remove deployments.apps example for resources tag option

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
Adds support for the new feature for change tracking in k8s called "Kubernetes Admission Events".
Applicable on Agent v.7.62.0+
=> [CONTP-519] Support K8s admin events

charts/datadog/Chart.yaml, charts/datadog/README.md
Properly create the `datadog` `3.84.3` chart version
the chart version was not bumped properly in the `chart.yaml` file, but the `changelog.md` already mention it https://github.com/DataDog/helm-charts/blob/main/charts/datadog/CHANGELOG.md#3843 
and it was part of the PR https://github.com/DataDog/helm-charts/pull/1639
=> fix(datadog): version 3.84.3 was not created properly

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_otel_agent_config.yaml
Add to the default OTELCollector config the `datadog.site` config option.
If a user is setting `datadog.site: us5.datadoghq.com`, they are expecting that the OTELCollector is also configured to send the payload to the same datadog site.
Before this PR it wasn't the case, the default site `datadoghq.com` was still set.
=> fix(datadog): propagate `datadog.site` option to the `otelCollector` config

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
The PR provides easy configuration option to enable or disable service discovery feature of the agent.
The PR introduces the configuration option
```yaml
datadog:
discovery:
enabled: <true/false>
```
The customer can enable or disable the feature using this configuration option.
On purpose I left the default value as empty, to allow the agent to fallback into the default mechanism, as we're in the process to enable the feature by default under some conditions.
- fixes #
Testing 4 options:
Goal: Enable SD directly
How to test:
Install the agent with the following configuration
```yaml
datadog:
discovery:
enabled: true
```
What to expect?
1. Run `k logs -n <namespace> -c …
=> [USMON-1389] service discovery: Add support

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml
Adds the necessary RBACs for the Cluster Agent to delete the `datadog-webhook` Validating and Mutating webhook configurations.
```
➜  kubectl describe clusterroles.rbac.authorization.k8s.io datadog-agent-cluster-agent
Name:         datadog-agent-cluster-agent
[...]
mutatingwebhookconfigurations.admissionregistration.k8s.io    []                 [datadog-webhook]                [get list watch update delete]
validatingwebhookconfigurations.admissionregistration.k8s.io  []                 [datadog-webhook]                [get list watch update delete]
```
=> feat(admission): add delete RBAC for datadog-webhook

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-otel-agent.yaml
The `otel-agent` should be launched with the `--core-config` switch so as to honor other potential configuration directives not present in the OTel configuration (which are Datadog Agent specific). This also includes and affects environment variables, which, as we know, are an important configuration tool in containerized environments. 
- fixes #
Currently the `otel-agent` does not honor environment variables, or other directives that may be specified in the `datadog.yaml` and that can define important configuration elements for the `otel-agent`.
=> [datadog] otel-agent: the otel-agent should be launched with --core-config

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
We need this https://github.com/DataDog/dd-source/pull/165598 for a customer
=> [ACTP] Bump runner version to v0.1.10-beta

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/values.yaml
This commit allows setting the APM instrumentation injector version in the `datadog` helm chart.
* [INPLAT-408](https://datadoghq.atlassian.net/browse/INPLAT-408)
[INPLAT-408]: https://datadoghq.atlassian.net/browse/INPLAT-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(datadog): allow setting injector version

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/operator_deployment_test.go
Adds configuration for CRD-specific watch namespaces added in Operator 1.8.0
https://github.com/DataDog/datadog-operator/pull/1235
- fixes #
=> [datadog-operator] expose CRD-specific watch namespace settings

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml
In the datadog-operator, the host cgroups are mounted in the system-probe container for USM, NPM and (with an ongoing fix https://github.com/DataDog/datadog-operator/pull/1610) Service Discovery, but this is not done in the helm chart.
It is needed get container information for Service Discovery with agent 7.61.
=> Add host cgroup mount to system-probe

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml
Update agent/cluster agent/cluster check runners version to `7.61.0` now that it has been released.
- fixes #
=> [datadog] Update agents to version 7.61.0

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/templates/service_account.yaml, charts/synthetics-private-location/values.yaml
This adds an optional annotations block for the synthetics-private-location service account, to use with AWS IAM roles, for example.
- fixes #
=> [synthetics-private-location] Add service account annotations

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml
=> Add support for SBOMs on CRI-O

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official observability-pipelines-worker 2.3.0 release
Same changes as [PR for 2.2.0 release](https://github.com/DataDog/helm-charts/pull/1549) 
- completes [OPA-2889](https://datadoghq.atlassian.net/browse/OPA-2889)
[OPA-2889]: https://datadoghq.atlassian.net/browse/OPA-2889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [observability-pipelines-worker] 2.3.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/rbac.yaml
This PR adds a clusterrole rule necessary to allow the agent to query the EKS metrics API as described in the official [AWS blog post](https://aws.amazon.com/blogs/containers/amazon-eks-enhances-kubernetes-control-plane-observability/)
I tested this by deploying the updated chart to my EKS cluster and validated that the `datadog-agent` clusterrole contains the new rule
```
❯ helm ls
NAME         	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART         	APP VERSION
datadog-agent	default  	1       	2025-02-03 15:12:57.193742 -0500 EST	deployed	datadog-3.90.1	7
```
```
❯ k get clusterrole datadog-agent -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
annotations:
meta.helm.sh/release-name: datadog-agent
meta.helm.sh/release-namespace: …
```
=> [CONTINT-4500] [helm] Add EKS Clusterrole Rule for EKS control plane metrics

.github/workflows/ci.yaml, .github/workflows/go-test-private-action-runner.yaml, .github/workflows/go-test.yaml, .github/workflows/pr-labeler.yaml, .github/workflows/release.yaml
pin all GitHub Actions by SHA
Pinning 3rd-party GitHub Actions by commit SHA makes them less vulnerable to compromise of the 3rd party. To avoid outdating and non-verbosity, versions are commented after the SHA and updating via dependabot is introduced that will automatically update the commented version tag as well.
In case of a false commit SHA, this change could break the corresponding workflow. Typically, this does not cause major interruptions, but it can for example affect a release pipeline and require restart causing delays.
- fixes #
=> ci: pin all GitHub Actions by SHA and update via dependabot

charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/clusterrole.yaml
This PR is related to https://github.com/DataDog/datadog-operator/pull/1651
This is necessary so that the `datadog-operator` can grant these permissions to the agent or the cluster checks runner
```
❯ helm ls
NAME               	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                 	APP VERSION
my-datadog-operator	default  	1       	2025-02-04 11:21:48.141738 -0500 EST	deployed	datadog-operator-2.5.1	1.11.1
```
```
❯ k get clusterrole datadog-cluster-checks-runner -o yaml | grep -B 1 -A 5 eks
- apiGroups:
- metrics.eks.amazonaws.com
resources:
- kcm/metrics
- ksh/metrics
verbs:
- get
```
```
❯ k get clusterrole datadog-agent -o yaml | grep -B 1 -A 5 eks
- apiGroups:
- metrics.eks.amazonaws.com
resources:
- kcm/metrics
- ksh/metrics
verbs:
- get
```
[Place …
=> [CONTINT-4500] [operator] Add EKS Clusterrole Rule to Operator for EKS control plane metrics

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogpodautoscalers_v1.yaml, crds/datadoghq.com_datadogagentprofiles.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogpodautoscalers.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml
Update CRDs from Operator v1.12.0 tag
- fixes #
=> [datadog-crds] Update CRDs from Operator v1.12.0

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadoggenericresources_v1.yaml, charts/datadog-crds/update-crds.sh, charts/datadog-crds/values.yaml, crds/datadoghq.com_datadoggenericresources.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml
* adds DatadogGenericResources CRD for operator release v1.12.0
- fixes #
=> [datadog-crds] add DatadogGenericResources CRD

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
* update Operator to latest release v1.12.0
* Add DatadogGenericResource configuration.
=> [datadog-operator] Update Operator version to 1.12.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml
* On GKE Autopilot, whitelisted Agent images are on `gcr.io` solely. When using US3 and not providing a registry, we default to Azure registry not whitelisted. We therefore add a condition on this defaulting to prevent using Azure if US3 and Autopilot.
- fixes #1697
QA'd with:
1. Site is US3, Autopilot not provided (defaults to false)
```shell
╰─❯ helm template dd charts/datadog/ --set datadog.site=us3.datadoghq.com --set datadog.apiKey=foo | grep -i "image:"
image: "datadoghq.azurecr.io/agent:7.62.0"
image: "datadoghq.azurecr.io/agent:7.62.0"
image: "datadoghq.azurecr.io/agent:7.62.0"
image: "datadoghq.azurecr.io/agent:7.62.0"
image: "datadoghq.azurecr.io/cluster-agent:7.62.0"
image: "datadoghq.azurecr.io/cluster-agent:7.62.0"
```
2. Site is US3, Autopilot is provided
```shell
╰─❯ helm …
```
=> default to gcr on us3 when autopilot

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml
Bumps the PAR image version to `v0.1.11-beta`
N/A
Also bumped some version numbers e.g. in shields.io that were left forgotten for too long
=> Update private action image version to `v0.1.11-beta`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update fips.image.tag to 1.1.7 updating openSSL version to 3.0.16
- fixes #
=> [AGENTRUN-117] Update FIPS Proxy version to 1.1.7

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
[Jira Ticket](https://datadoghq.atlassian.net/browse/EBPF-581)
This PR adds support for enabling GPU monitoring in system-probe.
- fixes #
This PR does not have automatic support for mixed node clusters (where some nodes have GPU and others don't). However, using the `affinity` value and the [existing documentation to join an existing `clusterAgent`](https://github.com/DataDog/helm-charts/tree/main/charts/datadog#how-to-join-a-cluster-agent-from-another-helm-chart-deployment-linux) this can be done without issues. Assuming we have already a `values.yml` file for a regular, non-GPU deployment, the steps to enable GPU monitoring only on GPU nodes are the following:
1. in …
=> Support GPU monitoring

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/agent-with-additional-rbac-label-values.yaml, charts/datadog/ci/cluster-agent-and-worker-with-dedicated-rbac-label-values.yaml, charts/datadog/templates/agent-clusterchecks-rbac.yaml, charts/datadog/templates/cluster-agent-rbac.yaml, charts/datadog/templates/rbac.yaml, charts/datadog/values.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml
Adding options for additional labels on the RBAC service accounts. Implemented much like the additional annotations.
Example usage: adding workload identity labels within AKS.
- Rebases https://github.com/DataDog/helm-charts/pull/1628 so that commits are signed and verified
=> Add service account additional labels

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml
Fix a bug where setting `datadog.containerImageCollection.enabled` to `false` does not disable image collection
Before, if `datadog.containerImageCollection.enabled` to `false`, it doesn't set `DD_CONTAINER_IMAGE_ENABLED` at all. Unfortunately when the environment variable isn't set, container image collection is still enabled by default in the agent, so we needed to adjust this setting so that if this is explicitly set to `false`, it sets the environment variable to `false` as well.
With this change, even if `datadog.containerImageCollection.enabled` to `false` but they have `datadog.sbom.containerImage.enabled` set to `true`, image collection will be enabled.
=> Fix a bug where setting `datadog.containerImageCollection.enabled` to `false` does not disable image collection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml
Bump to newly released Agent version.
=> Bump Agent version to 7.63

charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This updates the `apm.instrumentation` values documentation to use "preview" instead of "beta" language.
=> Update field documentation from beta to preview

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml
Fixes bug that causes `DD_KUBERNETES_ANNOTATIONS_AS_TAGS` env var to be incorrectly set to the merged value of `.Values.datadog.kubernetesResourcesLabelsAsTags` and `.Values.datadog.kubernetesResourcesAnnotationsAsTags`.
- fixes #
The helm chart creates rbacs for the DCA based on user configuration of kubernetes resources labels and annotations as tags. This is needed so that workloadmeta can list and watch related resources to feed the tagger collector with labels and annotations so that it can generate tags.
The rbac generation is done [here](https://github.com/DataDog/helm-charts/blob/19ce2bcdcef0f909c6d101b4df3402422ac5819c/charts/datadog/templates/cluster-agent-rbac …
=> [CONTP-679] Fix bug in dca rbac generation for annotations and labels as tags: use deepcopy before merging

.github/workflows/no-ci.yaml, test/common/common.go, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/default_all.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml, test/datadog/baseline_test.go
CECO-2006
* Updates baseline test for `datadog` chart to drop dynamic fields like timestamps, checksums etc. from a preconfigured list.
* Adds a 'default' baseline which renders chart with all resources with empty yaml. 
First commit reformats existing baselines using function used for reading/writing the manifests. Second commit adds filtering to make what's getting dropped more obvious for the reviewer. 
- fixes #
=> Filter dynamic fields in datadog chart baseline tests

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog/baseline/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default.yaml, test/datadog/baseline/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/daemonset_default.yaml, test/datadog/baseline/default_all.yaml, test/datadog/baseline/gdc_daemonset_default.yaml, test/datadog/baseline/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/other_default.yaml
Updates default agent to 7.63.2
- fixes #
=> Update agent to 7.63.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-system-probe.yaml
Include the `NVIDIA_VISIBLE_DEVICES` environment variable in the agent and system-probe containers when GPU monitoring is enabled.
This is needed in addition to the `/var/run/nvidia-container-devices` mount, as the latter will only be recognized by the k8s NVIDIA device plugin when `accept-nvidia-visible-devices-as-volume-mount` is enabled in its configuration.
- fixes #
=> Add NVIDIA_VISIBLE_DEVICES env var in GPU monitoring

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 2.4.0
closes [OPA-3022](https://datadoghq.atlassian.net/browse/OPA-3022)
[OPA-3022]: https://datadoghq.atlassian.net/browse/OPA-3022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [observability-pipelines-worker] 2.4.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml
Update Agent/cluster Agent images to `7.63.3` by default
- fixes #
=> [datadog] Update Agent components to `7.63.3`

test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline_test.go
Removes checksum field from otel baseline.
- fixes #
=> Remove checksum field from otel baseline test

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update FIPS Proxy version to 1.1.8 fixing CVEs
- fixes #
=> Update FIPS Proxy version to 1.1.8

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/agent-otel-collector-with-rbac-custom-rules-values.yaml, charts/datadog/ci/agent-otel-collector-with-rbac-values.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/otel-agent-rbac.yaml, charts/datadog/values.yaml
Add support for additional RBAC permissions required by `k8sattributes` processor.
The OpenTelemetry Collector’s [k8sattributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md) requires [specific RBAC permissions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md#role-based-access-control) to connect to the Kubernetes API server in order to enrich telemetry data with Kubernetes metadata. However, the default Service Account created by the Helm chart doesn't have these permissions: node agent (deployed as DaemonSet) retrieves pod information from the Kubelet `/pod` endpoints. This approach avoids overloading the Kubernetes API server in …
=> OTAGENT-254 Add support for enhanced RBAC permissions for otel-agent

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
This PR adds a configuration to control Service Discovery's network stats collection.
The new option is:
```yaml
datadog:
discovery:
networkStats:
enabled: <true/false>
```
The default value is true, as is in the agent.
- fixes #
=> [DSCVR-75] Add config option for Service Discovery network stats collection

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/templates/deployment.yaml, charts/private-action-runner/values.yaml, test/common/common.go, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/baseline_test.go
This makes it possible to pass environment variables that will be received by the PAR container
=> [ACTP] add support for passing environment variables to the PAR container

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/agent-otel-collector-logs-values.yaml, charts/datadog/ci/agent-otel-collector-volume-mounts-values.yaml, charts/datadog/templates/_container-otel-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/values.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/values/otel-agent_logs_collection.yaml, test/datadog/baseline/values/otel-agent_volume_mounts.yaml
To collect logs in Kubernetes environments, the `filelog` receiver requires specific volumes to be mounted to the `otel-agent` container:
- `/var/log/pods`
- `/var/log/containers`
- `/var/lib/docker/containers`
Currently, the Helm chart does not provide a way to mount these additional volumes for the `otel-agent` container.
Introduce new Helm chart parameters to enable filelog receiver support and allow mounting additional volumes in the `otel-agent` container:
- **`datadog.otelCollector.logs.enabled`**:  
When set to `true`, the Helm chart will check the OTel Collector configuration for a `filelog` receiver definition. If the receiver is defined, it mounts the required volumes to collect logs from containers and pods.
- **`agents.containers.otelAgent.volumeMounts`**:  
Specify additional …
=> OTAGENT-286 Add support for filelog receiver

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml, test/datadog/baseline/manifests/default_all_windows.yaml
CECO-2082
PR adds missing `auth-token` mount to `process-agent` when target system is Windows.
- fixes #
=> Add auth-token mount to process-agent on Windows

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.schema.json, test/datadog/apm_instrumentation_test.go, test/datadog/values/instrumentation/enabled_and_disabled_namespaces.yaml, test/datadog/values/instrumentation/extra_instrumentation_key.yaml, test/datadog/values/instrumentation/extra_namespaceselector_key.yaml, test/datadog/values/instrumentation/extra_podselector_key.yaml, test/datadog/values/instrumentation/extra_target_key.yaml, test/datadog/values/instrumentation/libversions_and_targets.yaml, test/datadog/values/instrumentation/namespace_exprs_and_names.yaml, test/datadog/values/instrumentation/namespace_labels_and_names.yaml, test/datadog/values/instrumentation/namespaces_and_targets.yaml, test/datadog/values/instrumentation/valid_enabled.yaml, test/datadog/values/instrumentation/valid_namespace.yaml, test/datadog/values/instrumentation/valid_targets.yaml
I've added a `values.schema.json` to validate the values for `datadog.apm.instrumentation` and unit tests to ensure the validation is working. This is the [blessed way](https://helm.sh/docs/topics/charts/#schema-files) to validate Helm values. While we do [validate these configuration options](https://github.com/DataDog/datadog-agent/blob/9c678234b26c3f68f00bcedda4dc33bd1b1f4c06/pkg/clusteragent/admission/mutate/autoinstrumentation/config.go#L170-L203) in the cluster agent, they simply cause the auto instrumentation webhook to fail to register and it still allows the cluster agent to start. This leaves a pretty glaring issue for a customer. Imagine the following:
* Customer updates config values in Helm with incorrect fields
* Cluster agent starts but fails to register the …
=> feat: add validation for instrumentation values

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Updates the helm charts to refer to the new latest observability pipelines worker
=> [observability-pipelines-worker] 2.4.1 and 2.4.2 releases

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_daemonset-volumes-linux.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
This PR puts the `podResources` socket mount behind the GPU monitoring flag, as it's the only product currently using it.
- fixes #
=> Enable pod-resources socket only with GPU monitoring enabled

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/values.schema.json
It's not possible to use `datadog.apm.errorTrackingStandalone.enabled` without running into this error
`json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string`
This is because the value of the var is `true` where it should've been `"true"`
It also introduces the `errorTrackingStandalone` object into the schema for validation
=> [errortracking] fix error tracking standalone config

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogpodautoscalers_v1.yaml, crds/datadoghq.com_datadogpodautoscalers.yaml
Update DPA storage version to v1alpha2
=> Update DPA storage version to v1alpha2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/autoscaling-values.yaml, charts/datadog/requirements.lock, charts/datadog/requirements.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/_orchestrator_explorer_config.yaml, charts/datadog/values.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/gke_autopilot_daemonset_default.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
The Cluster Agent Agent `7.64` requires new DPA CRD version. bundling the change together.
Will require change from https://github.com/DataDog/helm-charts/pull/1768
- fixes #
=> Update DPA CRD version alongside Agent/Cluster Agent version 7.64. Auto add DPA to orchestrator collection

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/templates/deployment.yaml, charts/private-action-runner/templates/secrets.yaml, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml, test/private-action-runner/baseline_test.go
This allows to retrieve the runner's URN and private key from a kubernetes secret instead of having to store it in the `values.yaml`
=> [ACTP-461] allow to store the runner's identity in a kubernetes secret

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/templates/NOTES.txt, charts/private-action-runner/templates/role.yaml, charts/private-action-runner/templates/rolebinding.yaml, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml, test/private-action-runner/baseline_test.go
Make the PAR less powerful by default and allow for least privileged permissions
=> [ACTP-459] deploy the PAR with a role instead of a cluster role by default

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/templates/deployment.yaml, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml, test/private-action-runner/baseline_test.go
Allow to retrieve credentials files from existing kubernetes secrets in order to be able to manage them outside of the chart
=> [ACTP-462] allow to store PAR credential files outside of the helm chart

Makefile
Create a make command to update the private action runner snapshot tests to facilitate the upgrade process
=> [PAR] Add a makefile entry to update the private-action-runner snapshot tests

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update FIPS Proxy version to 1.1.9 fixing CVEs
- fixes #
=> Update FIPS Proxy version to 1.1.9

README.md
Add the private action runner chart in the repo readme
=> Adds the private action runner to the root readme

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml
New release for the following:
* Bugfix: `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` are now honored for all http requests from the runner
* Feat: more flexible credentials loading.
=> [ACTP] Bump runner version to v1.2.0

.github/workflows/ci.yaml
with the deprecation of ubuntu-20, it is not possible to run the kind create cluster with kubernetes 1.18
- fixes #
=> Deprecated Kubernetes 1.18 from the ci install-chart job

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
This commit removes the preview label for SSI and updates the docs for target based workload selection in preparation for GA.
[INPLAT-545](https://datadoghq.atlassian.net/browse/INPLAT-545)
This is a documentation only change. Because of this, I have not updated the chart version.
[INPLAT-545]: https://datadoghq.atlassian.net/browse/INPLAT-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: remove preview label for SSI

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, crds/datadoghq.com_datadogpodautoscalers.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/gke_autopilot_daemonset_default.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
When running in an openshift cluster, you can use a `DeploymentConfig` to configure your application, this will create a `ReplicationController` instead of a `ReplicaSet`:
https://docs.redhat.com/en/documentation/openshift_container_platform/4.3/html/applications/deployments#what-deployments-are
We don't support this specific kind of resource in our permissions so a user can get this error in the `tagsFromLabels` mutating webhook (depending on the owner of the pod).
```
ERROR | (pkg/clusteragent/admission/mutate/tagsfromlabels/mutator.go:93 in MutatePod) | replicationcontrollers "XXXXXX" is forbidden: User "system:serviceaccount:datadog:datadog-agent-cluster-agent" cannot get resource "replicationcontrollers" in API group "" in the namespace "XXXXXXX"
```
[Place an '[x]' (no spaces) in …
=> admission-controller should have access to `get replicationcontrollers`

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.56.0.
=> [synthetics-private-location]: ⬆️ bump PL version to 1.56.0

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/values.schema.json, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml
A customer requested this so they can use the PAR as a subchart. This requires that a `global` object is allowed in the values. 
=> [ACTP] Allow global object in values

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/ci/kubeconform-values.yaml, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/values.schema.json, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml
Adds special comments / instructions for JSON schema based support in IDEs when using the PAR helm chart.
I get native support in goland 
For VSCode i had to install [this extension](https://marketplace.visualstudio.com/items/?itemName=redhat.vscode-yaml)
=> [ACTP][PAR] Add $schema for completion support in IDEs

.github/workflows/bump-chart-version.yaml
Use robot app token for the `bump-chart-version` workflow so that its commits will properly trigger GH jobs. Previously, the GH status checks would get "stuck" on the required `pr-validated` job. 
- fixes #
=> Fix stuck jobs on `bump-chart-version` workflow

repository.datadog.yml
Give access to MQ for @DataDog/logs-cloudprem team that owns the CloudPrem chart
- fixes #
=> Allow MQ for logs-cloudprem

.github/workflows/release.yaml
Update releaser action to not mark pre-release versions like `X.Y.Z-*` as latest in Github.
- fixes #
=> [tooling] Do not mark pre-release version as latest in Github

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
* 2.5.0 OPW helm chart release
=> [observability-pipelines-worker] 2.5.0 release

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md
=> [datadog-crds] Update CRDs from Operator v1.14.0

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Releases a new chart for Synthetics Private Location Worker latest 1.56.1 version.
- fixes #
=> [SYN]: Update Private Location to 1.56.1

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
[datadog-operator] Update chart for 1.14.0 release
- fixes #
=> [datadog-operator] Update chart for 1.14.0 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-rbac.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_default.yaml, test/datadog/baseline/manifests/gke_autopilot_npm.yaml, test/datadog/baseline/manifests/gke_autopilot_system_probe.yaml, test/datadog/baseline/manifests/gke_autopilot_usm.yaml, test/datadog/baseline/manifests/gke_autopilot_workloadallowlist_default.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
The API Group set for `replicationcontrollers` was incorrect, it is in the core api not the `apps` api.
Fixes #1800 
=> Fix: replicationcontrollers apiGroup

.github/workflows/release.yaml
Allow datadog-csi-driver chart release. The workflow path filter didn't prevent chart updates from getting released with other chart releases. 
- fixes #
=> Allow datadog-csi-driver release

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml
Bump the PAR version to release the experimental dev action `kubernetes.apps.rollbackDeployment`
=> [ACTP] Bump runner version to v1.3.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_default.yaml, test/datadog/baseline/manifests/gke_autopilot_npm.yaml, test/datadog/baseline/manifests/gke_autopilot_system_probe.yaml, test/datadog/baseline/manifests/gke_autopilot_usm.yaml, test/datadog/baseline/manifests/gke_autopilot_workloadallowlist_default.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
* Upgrade default `Agent` anf `Cluster-Agent` versions to `7.64.3` in the `datadog` chart
- fixes #
* Sorry I created this PR as I was doing before. So I ran the `.github/helm-docs.sh` locally and didn't used the new semver label capability.
=> [datadog] Upgrade default Agent anf Cluster-Agent versions to 7.64.3

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-otel-agent.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml
Set `DD_OTELCOLLECTOR_ENABLED` from `datadog.otelCollector.enabled` in values.yaml
- fixes #
=> [OTAGENT-391] Update _container-otel-agent.yaml

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/daemonset.yaml, charts/datadog/templates/otel-configmap.yaml, charts/datadog/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog/baseline/manifests/otel-agent_configmap.yaml, test/datadog/baseline/values/otel-agent_configmap.yaml
Adds support for configuring the DDOT Collector with an existing (external) ConfigMap instead of embedding the YAML in values.yaml.
- `datadog.otelCollector.configMap.name` — name of the ConfigMap to mount
- `datadog.otelCollector.configMap.key` — key in that ConfigMap containing the collector config
If `datadog.otelCollector.configMap.name` is set, the specified ConfigMap is mounted for `otel-agent`, and collector config points to the referenced key (`datadog.otelCollector.configMap.key`).
If `datadog.otelCollector.configMap.name` is not set, the chart falls back to the current inline-config behaviour (fully backward-compatible).
- [OTAGENT-387](https://datadoghq.atlassian.net/browse/OTAGENT-387) …
=> OTAGENT-387 Add support for configuring DDOT with a ConfigMap

charts/cloudprem/CHANGELOG.md, charts/cloudprem/Chart.yaml, charts/cloudprem/README.md, charts/cloudprem/datadog.yaml, charts/cloudprem/templates/_helpers.tpl, charts/cloudprem/templates/configmap.yaml, charts/cloudprem/templates/indexer-statefulset.yaml, charts/cloudprem/values.yaml
* Add pipelinesConfig property to values.yaml https://github.com/DataDog/pomsky-helm-charts/pull/4
* Fix sort order for same-second documents
* Indexing pomsky's traces in pomsky by default
=> Update CloudPrem Helm chart

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 2.2.0
Completes [this](https://datadoghq.atlassian.net/browse/OPA-3225) issue
=> [observability-pipelines-worker] 2.5.1 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml
Update FIPS Proxy version to 1.1.10 fixing CVEs and updating packages
- fixes #
=> Update FIPS Proxy version to 1.1.10

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_default.yaml, test/datadog/baseline/manifests/gke_autopilot_npm.yaml, test/datadog/baseline/manifests/gke_autopilot_system_probe.yaml, test/datadog/baseline/manifests/gke_autopilot_usm.yaml, test/datadog/baseline/manifests/gke_autopilot_workloadallowlist_default.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_configmap.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
Upgrade default agent and cluster-agent versions to 7.65.0.
=> [datadog] Upgrade default agent and cluster-agent versions to 7.65.0

charts/datadog-csi-driver/CHANGELOG.md, charts/datadog-csi-driver/Chart.yaml, charts/datadog-csi-driver/README.md, charts/datadog-csi-driver/templates/daemonset.yaml
=> fix image pull secrets in csi driver chart

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagents_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogpodautoscalers_v1.yaml, crds/datadoghq.com_datadogagents.yaml, crds/datadoghq.com_datadogpodautoscalers.yaml
Update CRDs for operator `1.15.0-rc.1`
- fixes #
=> Update CRDs for operator 1.15.0-rc.1

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
Updates operator charts for 1.15.0-rc.1
- fixes #
=> [datadog-operator] Update operator chart for 1.15.0-rc.1

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_default.yaml, test/datadog/baseline/manifests/gke_autopilot_workloadallowlist_default.yaml, test/datadog/baseline/values/gke_autopilot_allowlistedv2workload_default.yaml, test/datadog/baseline/values/gke_autopilot_workloadallowlist_default.yaml
- fixes https://github.com/DataDog/helm-charts/issues/1859
=> Fix default cluster check runner container resources for GKE Autopilot

Makefile, test/common/common.go
* Makefile change to run helm dependency update before tests.
* Discard `helm template` outputs. 
- fixes #
=> [tooling] discard Go helm test outputs; update chart deps in Makefile

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_default.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_kubelet_apiserver.yaml, test/datadog/baseline/manifests/gke_autopilot_npm.yaml, test/datadog/baseline/manifests/gke_autopilot_system_probe.yaml, test/datadog/baseline/manifests/gke_autopilot_usm.yaml, test/datadog/baseline/manifests/gke_autopilot_workloadallowlist_default.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_configmap.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
Upgrade default agent and cluster-agent versions to 7.65.1.
=> [datadog] Upgrade default agent and cluster-agent versions to 7.65.1

charts/datadog-csi-driver/CHANGELOG.md, charts/datadog-csi-driver/Chart.yaml, charts/datadog-csi-driver/README.md, charts/datadog-csi-driver/templates/daemonset.yaml, charts/datadog-csi-driver/values.yaml
=> add option to configure csi registrar image

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt
Fixes issue where `datadog.apm.hostSocketPath` is not respected by the agent in case apm and dogstatsd sockets are configured with the different host paths but same mount path.
This PR adds an ERROR that shows upon installation of the chart if the configuration results in conflicting hostpath for apm and dogstatsd.
Trying to install the chart with conflicting hostpaths will show the following error:
```
#################################################################
#################################################################
Dogstatsd and APM sockets are configured with different paths on the host (datadog.dogstatsd.hostSocketPath and datadog.apm.hostSocketPath).
However, they have the same parent directory in the mount (datadog.dogstatsd.socketPath and datadog.apm.socketPath).
It …
```
=> fail installation if apm and dogstatsd have different hostpath but same mount path

charts/datadog-csi-driver/CHANGELOG.md, charts/datadog-csi-driver/Chart.yaml, charts/datadog-csi-driver/README.md, charts/datadog-csi-driver/templates/daemonset.yaml
Fixes bugs in datadog csi driver: the dsd and apm socket paths were not passed correctly in the flags to the entrypoint.
=> fix bug in csi driver chart

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Official release for OPW version 2.5.2
Closes out 2.5.2 release [issue](https://datadoghq.atlassian.net/browse/OPA-3256)
Completed [release pipeline](https://gitlab.ddbuild.io/DataDog/observability-pipelines-worker/-/pipelines/64737572)
=> [observability-pipelines-worker] 2.5.2 release

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-system-probe.yaml, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/daemonset.yaml, test/datadog/baseline/manifests/gke_autopilot_npm.yaml, test/datadog/baseline/manifests/gke_autopilot_system_probe.yaml, test/datadog/baseline/manifests/gke_autopilot_usm.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
The apparmor annotation generates warnings on 1.30+ and will be deprecated on 1.36+.
=> use securityContext for AppArmor on k8s 1.30+

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/autoscaling-values.yaml, charts/datadog/values.yaml, test/datadog/baseline/manifests/agent-clusterchecks-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_advanced_AC_injection.yaml, test/datadog/baseline/manifests/cluster-agent-deployment_default_minimal_AC_injection.yaml, test/datadog/baseline/manifests/daemonset_default.yaml, test/datadog/baseline/manifests/default_all.yaml, test/datadog/baseline/manifests/default_all_windows.yaml, test/datadog/baseline/manifests/gdc_daemonset_default.yaml, test/datadog/baseline/manifests/gdc_daemonset_logs_collection.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_default.yaml, test/datadog/baseline/manifests/gke_autopilot_allowlistedv2workload_kubelet_apiserver.yaml, test/datadog/baseline/manifests/gke_autopilot_npm.yaml, test/datadog/baseline/manifests/gke_autopilot_system_probe.yaml, test/datadog/baseline/manifests/gke_autopilot_usm.yaml, test/datadog/baseline/manifests/gke_autopilot_workloadallowlist_default.yaml, test/datadog/baseline/manifests/npm_daemonset_default.yaml, test/datadog/baseline/manifests/otel-agent_configmap.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml, test/datadog/baseline/manifests/other_default.yaml, test/datadog/baseline/manifests/system_probe_daemonset_default.yaml, test/datadog/baseline/manifests/usm_daemonset_default.yaml
* Upgrade default agent and cluster-agent versions to 7.65.2.
* Modify autoscaling values file:
* Remove `beta` tag to instead use default one
* Provide clusterName (will be needed in 7.67: https://github.com/DataDog/datadog-agent/pull/36718)
* Use `datadog.kubelet.tlsVerify` so the hostname can be retrieved from the kubelet (kind, so self-signed certificates)
* Fixes broken CI due to `Error: Failed to start: autoscaling is enabled but no cluster name detected, exiting` (https://github.com/DataDog/helm-charts/actions/runs/15040320968/job/42277882241?pr=1871#step:6:16826)
* Root cause: use of DCA `beta` image tag that incorporates a requirement for cluster name at this date
GitHub CI takes care of the …
=> [datadog] Upgrade default agent and cluster-agent versions to 7.65.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_components-common-env.yaml, charts/datadog/values.yaml
Add support for `secret_refresh_interval` in chart/datadog
=> Add support for secret_refresh_interval in chart/datadog

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
Update operator chart for 1.15.0-rc.2
- fixes #
=> Update operator chart for 1.15.0-rc.2

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/templates/deployment.yaml, charts/private-action-runner/values.schema.json, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/custom-resources.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml, test/private-action-runner/baseline_test.go
Adds support for configurable resource limits and requests in the private-action-runner Helm chart. This allows users to set custom CPU and memory requirements based on their environment needs. Previously, these values were hardcoded in the deployment template.
- fixes #
This change maintains backward compatibility by keeping the default resource values the same as the previously hardcoded values (CPU: 250m, Memory: 1Gi).
=> [ACTP-695] Make PAR Helm chart configurable to limit runner resources

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_kubernetes_state_core_config.yaml, charts/datadog/templates/kube-state-metrics-core-rbac.yaml, charts/datadog/values.yaml, test/datadog/baseline/manifests/kube-state-metrics-custom-resources.yaml, test/datadog/baseline/values/kube-state-metrics-custom-resources.yaml
Add an datadog chart parameter to configure custom resources metrics collection introduced in DataDog/datadog-agent#31715.
=> [CONTINT-4643] Add an option to configure KSM custom resource metrics collection

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-resources.yaml, charts/datadog/templates/_container-system-probe.yaml, test/datadog/baseline/manifests/gke_autopilot_npm.yaml, test/datadog/baseline/manifests/gke_autopilot_system_probe.yaml, test/datadog/baseline/manifests/gke_autopilot_usm.yaml
Adds defaults for resource limits for the system-probe container on GKE Autopilot.
- fixes #
=> Add default resource limits for system-probe on gke autopilot

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/templates/_helpers.tpl, charts/private-action-runner/templates/role.yaml, charts/private-action-runner/values.schema.json, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/custom-resources.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml, test/private-action-runner/baseline_test.go
Add new kubernetes deployment actions support in the helm chart
=> [ACTP] add support for kubernetes deployments actions

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/cluster-agent-deployment.yaml
Ensure local fallback is enabled by default when workload autoscaling is enabled
- fixes #
=> Enable local fallback when workload autoscaling enabled

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
The Synthetics Private Location was updated to version 1.57.0.
None
=> [SYNTH-20069] Bump PL to 1.57.0

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/custom-resources.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml
Bump the private actions runner version to `v1.4.0`
- fixes #
=> [ACTP] Bump private actions runner version to v1.4.0

charts/datadog-csi-driver/CHANGELOG.md, charts/datadog-csi-driver/Chart.yaml, charts/datadog-csi-driver/README.md, charts/datadog-csi-driver/templates/daemonset.yaml
Removes `hostNetwork: true` from CSI driver nodeserver daemonset.
This option is not needed for the driver to operate as expected.
Validation done using e2e:
* clone [csi driver repo](https://github.com/DataDog/datadog-csi-driver)
* update [this](https://github.com/DataDog/datadog-csi-driver/blob/b005d4de4f69d3a08a751715233047f33c0ece61/test/e2e/setup-env.sh#L36) line to reference the patched helm chart branch
* run `make e2e`
- Related to [this](https://github.com/DataDog/datadog-gke-workload-allowlist/pull/4#discussion_r2136257946).
=> [CONTP-812] remove hostnetwork true from csi driver nodeserver daemonset

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/requirements.lock, charts/datadog/requirements.yaml
Bump datadog chart datadog-crds dependency version to 2.8.0
- fixes #
=> Bump datadog chart datadog-crds dependency version to 2.8.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, test/common/common.go, test/datadog/apparmor_test.go
If no custom/default `securityContext` was provided, then the seccomp/apparmor sections of the `securityContext` were not generated
=> fix seccomp/apparmor for agent container

Makefile, charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
=> [datadog-operator] Update chart for 1.15.1 release

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/README.md.gotmpl, charts/private-action-runner/UPGRADING.md, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/templates/deployment.yaml, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/custom-pod-scheduling.yaml, test/private-action-runner/__snapshot__/custom-resources.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml, test/private-action-runner/data/old-values-file.yaml
We want to change the location used by runner configuration files from `/etc/dd-action-runner` to `/etc/dd-action-runner/config` so we're updating all places where we specify the value. This PR change the configuration for the helm chart.
ACTP-745
=> [ACTP-745] update PAR configuration file location

.github/workflows/go-test-operator.yaml
=> Operator Go test matrix update, add 1.33

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/agent-clusterchecks-deployment.yaml
Enable `DD_USE_DOGSTATSD` fo the cluster checks runner whenever a user uses the `-jmx` Datadog Agent image so that JMX based checks can run properly.
CONS-7381
=> Enable dogstatsd in clusterchecks when jmx image is used for cluster check runners

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/values.schema.json, charts/datadog/values.yaml, test/datadog/apm_instrumentation_test.go, test/datadog/values/instrumentation/values_from.yaml, test/datadog/values/instrumentation/values_from_invalid.yaml
This adds support for `valueFrom` for `apm.instrumentation`.
- https://github.com/DataDog/datadog-agent/pull/35487
This is a combination of a few changes that can be split out if needed:
- refactoring `values.json.schema` to use [`$defs` for common components](https://github.com/DataDog/datadog-agent/pull/35487)
- adding support for `valueFrom` 
- adding tests for `valueFrom` (and cleaning up existing APM tests)
This will be shipped in agent `7.66` so I'm not sure when we want to land this specifically the helm charts.
=> feat(instrumentation): support valueFrom

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-otel-agent.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml
This PR adds support for providing multiple items in otelCollector.configMap.items. Each item is an otel config, and the appropriate volume/ volume mounts will be created. The otel agent command will also be updated to pass all configs.
OTAGENT-352
=> Otel Agent: add support for multi items in configmap

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/ci/agent-with-lifecycle-handler-values.yaml, charts/datadog/ci/agent-with-termination-grace-period-seconds-values.yaml, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-otel-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/templates/cluster-agent-deployment.yaml, charts/datadog/templates/daemonset.yaml, charts/datadog/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog/baseline/manifests/otel-agent_config_ports.yaml, test/datadog/baseline/manifests/otel-agent_configmap.yaml, test/datadog/baseline/manifests/otel-agent_container_ports.yaml, test/datadog/baseline/manifests/otel-agent_logs_collection.yaml, test/datadog/baseline/manifests/otel-agent_volume_mounts.yaml, test/datadog/baseline/manifests/otel_enabled.yaml
copy of https://github.com/DataDog/helm-charts/pull/1716:
> agents.lifecycle, if defined, will provide us with a way to inject a [Lifecycle](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#lifecycle-v1-core) block into the agents PodSpecs
> agents.terminationGracePeriodSeconds, when set, alters the amount of time Kubernetes waits until forcibly terminating the agents pods.
> 
> Why?
> 
> When a Kubernetes node is being terminated, the kubelet signals everything non-critical at the same time. It is possible for the agent to finish the shutdown faster than the application pods, which leaves us with no metrics while app connections are drained.
- fixes …
=> Added agent lifecycle enhancements

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/kube-state-metrics-core-rbac.yaml, charts/datadog/values.yaml, test/datadog/baseline/manifests/kube-state-metrics-custom-resources.yaml, test/datadog/baseline/values/kube-state-metrics-custom-resources.yaml
RBACs for the KSM custom resources metric collection need to be updated to properly use the entity "resource" type instead of "kind + "s".
We will expose the option for the user to provide the **_resource_** type of the CRD so that RBACs can be generated using the specified resource name.
- fixes #
CONS-7448
=> Update RBAC for CRDs metric collection

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/deployment.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
Update datadog-operator chart for 1.17.0-rc.1 (dev version)
- fixes #
=> [datadog-operator] update operator chart for 1.17.0-rc.1

charts/datadog-csi-driver/CHANGELOG.md, charts/datadog-csi-driver/Chart.yaml, charts/datadog-csi-driver/README.md, charts/datadog-csi-driver/templates/daemonset.yaml
This PR modifies the following volume mounts to be read-only mounts:
- apm-sock and dsd-sock volume mounts on the csi node server container
- plugin-dir volume mount on the node registrar container.
Added comments to the daemonset to explain what each volume / volume mount does.
=> Make some volume mounts readonly

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/templates/clusterrole.yaml, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
Update Helm chart (dev version) for Datadog Operator 1.17.0-rc.2
=> [datadog-operator] Update chart for 1.17.0-rc.2

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-security-agent.yaml, charts/datadog/templates/system-probe-configmap.yaml, charts/datadog/values.yaml
=> Allow excluding containers from security signals generation

charts/observability-pipelines-worker/CHANGELOG.md, charts/observability-pipelines-worker/Chart.yaml, charts/observability-pipelines-worker/README.md, charts/observability-pipelines-worker/values.yaml
Release for or OPW 2.7.0
https://datadoghq.atlassian.net/browse/OPA-3561
=> [observability-pipelines-worker] release 2.7.0

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/custom-pod-scheduling.yaml, test/private-action-runner/__snapshot__/custom-resources.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml
Adds support for script actions for the private action runner
ACTP-757
=> [PAR] add support for script action

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
Update datadog operator helm chart version (dev version) for operator release v1.17.0-rc.3
- fixes #
=> [datadog-operator] Update chart for 1.17.0-rc.3

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md
=> Update datadog-crds for operator v1.17.0 tag

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/values.yaml
This PR adds tunables related to number of workers/performance/throttling in Network Traffic Paths. This is needed because a customer has noted they hit the upper limit that their default 4 workers can process.
=> [netpath] Add tunables for Network Traffic Paths

charts/synthetics-private-location/CHANGELOG.md, charts/synthetics-private-location/Chart.yaml, charts/synthetics-private-location/README.md, charts/synthetics-private-location/values.yaml
Bump the Synthetics private location chart to `0.17.12` for the new PL `1.59.0` release.
=> [synthetics] Update PL chart for 1.59.0 release

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
* Release Operator 1.18.0-rc.2
- fixes #
=> [datadog-operator] `v1.18.0-rc.2`

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/gke_autopilot_allowlist_synchronizer.yaml
This PR adds the new GKE autopilot allowlist that supports the otel agent, see: https://github.com/DataDog/datadog-gke-workload-allowlist/pull/6. It also removes the otel agent limitation in GKE Autopilot.
- fixes #
=> Add new allowlist

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
Enable the orchestrator check to collect the following custom resources if autoscaling is enabled: `karpenter.azure.com/*`, `karpenter.k8s.aws/*`, `karpenter.sh/*`, and `argoproj.io/rollouts`.
=> enable orchestrator automatic custom resources collection if autoscaling enabled

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
* Release 1.18.0 through Helm chart
- fixes #
=> [datadog-operator] 1.18.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/NOTES.txt, charts/datadog/templates/_container-agent.yaml, charts/datadog/templates/_container-process-agent.yaml, charts/datadog/templates/_container-trace-agent.yaml, charts/datadog/values.yaml
Add `agents.lifecycle` support for GKE Autopilot. 
Note: The `exec` lifecycle handler is not supported in GKE Autopilot.
- closes #2007
=> Add agents.lifecycle support for GKE Autopilot

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/cluster-agent-deployment.yaml
revert https://github.com/DataDog/helm-charts/pull/2025/files
- fixes #
=> Revert the change that enables OOTB CR collections when autoscaling is enabled

charts/private-action-runner/CHANGELOG.md, charts/private-action-runner/Chart.yaml, charts/private-action-runner/README.md, charts/private-action-runner/examples/values.yaml, charts/private-action-runner/values.schema.json, charts/private-action-runner/values.yaml, test/private-action-runner/__snapshot__/config-overrides.yaml, test/private-action-runner/__snapshot__/custom-pod-scheduling.yaml, test/private-action-runner/__snapshot__/custom-resources.yaml, test/private-action-runner/__snapshot__/default.yaml, test/private-action-runner/__snapshot__/deprecated-modes.yaml, test/private-action-runner/__snapshot__/enable-kubernetes-actions.yaml, test/private-action-runner/__snapshot__/example.yaml, test/private-action-runner/__snapshot__/external-secrets.yaml, test/private-action-runner/__snapshot__/scripts-configuration.yaml, test/private-action-runner/baseline_test.go
- Bump PAR version to `v1.9.0` and deprecate old runner modes
=> [ACTP] Bump private actions runner version to v1.9.0

charts/datadog/CHANGELOG.md, charts/datadog/Chart.yaml, charts/datadog/README.md, charts/datadog/templates/_helpers.tpl, charts/datadog/templates/daemonset.yaml, test/datadog/apparmor_test.go
A customer pointed that system-probe was not running correctly on GKE with kubernetes version > 1.33. This issue was introduced in https://github.com/DataDog/helm-charts/pull/1865, where the `semverCompare` function was used in a way such as prereleases will not match. In GKE, kubernetes versions have the suffix `-gke` so the `semverCompare` was not matching in any case. 
https://datadoghq.atlassian.net/browse/EBPF-823
Added two unit tests to ensure correctness.
=> fix security context generation on GKE

charts/datadog-crds/CHANGELOG.md, charts/datadog-crds/Chart.yaml, charts/datadog-crds/README.md, charts/datadog-crds/templates/datadoghq.com_datadogagentinternals_v1.yaml, charts/datadog-crds/templates/datadoghq.com_datadogagentprofiles_v1.yaml, crds/datadoghq.com_datadogagentinternals.yaml, crds/datadoghq.com_datadogagentprofiles.yaml
=> [datadog-crds] Update operator crds from 1.19.0-rc.2

charts/datadog-operator/CHANGELOG.md, charts/datadog-operator/Chart.lock, charts/datadog-operator/Chart.yaml, charts/datadog-operator/README.md, charts/datadog-operator/templates/_helpers.tpl, charts/datadog-operator/values.yaml, test/datadog-operator/baseline/DatadogAgent_CRD_default.yaml, test/datadog-operator/baseline/Operator_Deployment_default.yaml, test/datadog-operator/operator_deployment_test.go
=> [datadog-operator] Update Datadog Operator chart for 1.19.0-rc.2

test/common/common.go, tools/yaml-mapper/mapping_datadog_helm_to_datadogagent_crd_v2.yaml, tools/yaml-mapper/pkg/yamlmapper/yaml_mapper.go, tools/yaml-mapper/pkg/yamlmapper/yaml_mapper_test.go
=> [AGENTONB-2560] use full helm values in mapper integration test

.github/chainguard/self.stale.manage-stale.sts.yaml, .github/workflows/check-issue-status.yaml
- Add missing parenthesis on the check_issue_state workflow
- Add a name in this workflow
- Fix the typo related to the file extension which prevents current execution of the job
Fixes [failed workflow](https://github.com/DataDog/helm-charts/actions/runs/18277235095/job/52032051290) for stale management
This is a follow-up of #2073
=> fix(octo-sts): Adapt the chainguard and fix the issue state check
